export type ForgeTaskGuide = {
  navigationPath: string;
  steps: string[];
};

const guide = (navigationPath: string, steps: string[]): ForgeTaskGuide => ({
  navigationPath,
  steps,
});

const TASK_GUIDES: Record<string, ForgeTaskGuide> = {
  "complete-setup-journey": guide("Forge Dashboard", [
    "**Open the setup journey:** Use the left navigation to work through Setup, Process & Engineering, Production, and Traceability in order.",
    "**Create the factory records:** Create Sites, Lines, operation Stations, Repair Stations, and Shift Definitions.",
    "**Create the product records:** Create the Project, Product Family, Components, Product, Variants, and BOM Version.",
    "**Prepare execution:** Activate the BOM, create and validate the Routing, and assign the Product to eligible Lines.",
    "**Launch a trial order:** Create a small Work Order, confirm unit serials, select capacity and Routing, run validation, and select Release.",
  ]),
  sites: guide("Manufacturing → Factory setup → Sites", [
    "**Open Sites:** In the Forge left navigation, open Factory setup and select Sites.",
    "**Start a new record:** Select **Create Site** in the upper-right corner.",
    "**Enter the identity:** Complete **Name**, a unique **Code**, **Address**, and **Timezone**.",
    "**Select ownership:** Choose the Plant that owns and operates this Site.",
    "**Save and verify:** Select **Save**, then confirm the Site appears in the Sites list.",
  ]),
  lines: guide("Manufacturing → Process & Engineering → Line", [
    "**Open Lines:** In the Forge left navigation, open **Process & Engineering** and select **Line**.",
    "**Start a new line:** Select **Create Line** in the upper-right corner.",
    "**Enter Line Details:** Complete **Name**, unique **Code**, **Type**, and select the Site when the Line belongs to one.",
    "**Set capacity:** Enter **Capacity Per Hour**, **Capacity Per Shift**, and **Task Queue Capacity** using realistic production limits.",
    "**Choose the starting behavior:** Turn on **Is Starting Line** only when newly released Production Tasks may begin on this Line.",
    "**Create the line:** Keep the Line active, review the values, and select **Create Line**.",
  ]),
  "stations-and-repair-stations": guide(
    "Manufacturing → Process & Engineering → Stations",
    [
      "**Open Stations:** Open **Process & Engineering** and select **Stations**.",
      "**Create an operation Station:** Select **Create Station**, then enter its **Name**, unique **Code**, and description.",
      "**Place and classify it:** Select the correct **Site**, production area, and **Station Category** or Station type.",
      "**Configure execution:** Add devices, tools, or automation settings only when the Station requires them.",
      "**Create the Repair Station:** Repeat the process and choose the Repair type for the dedicated failure-handling Station.",
      "**Save and verify:** Select **Save** and confirm both Stations are active and available in Routing operations.",
    ],
  ),
  shifts: guide("Manufacturing → Shifts & Labor → Shift Definitions", [
    "**Open Shift Definitions:** Open **Shifts & Labor** and select **Shift Definitions**.",
    "**Start a shift:** Select **Create Shift**.",
    "**Enter the schedule:** Add a clear **Name**, **Start Time**, **End Time**, and break information when required.",
    "**Add calendar rules:** Use **Shift Schedules** or **Shift Calendar** when the working pattern changes by day.",
    "**Save the shift:** Select **Create Shift** or **Save**, then confirm it is available in the Shift list.",
  ]),
  "factory-readiness": guide("Manufacturing → Factory setup and Process & Engineering", [
    "**Check Sites:** Open **Sites** and confirm every physical manufacturing location is represented.",
    "**Check Lines:** Open **Line** and confirm the intended first production Line has **Is Starting Line** enabled.",
    "**Check capacity:** Open each Line and review **Task Queue Capacity**, hourly capacity, and shift capacity.",
    "**Check Stations:** Open **Stations** and confirm every Routing operation and failure path has an active Station.",
    "**Run a small validation:** Use a small Work Order quantity to confirm the factory model can accept and route Production Tasks.",
  ]),
  "projects-and-product-families": guide("Manufacturing → Setup → Projects", [
    "**Open Projects:** Open **Setup** and select **Projects**.",
    "**Create a Project:** Select **Create Project**, enter the Project identity and ownership details, then save it.",
    "**Open the Project:** Select the new Project and find its **Product Families** section.",
    "**Create a Product Family:** Select **Create Product Family**, enter its name and code, and save.",
    "**Verify the hierarchy:** Confirm the Product Family appears under the intended Project and can be selected during Product creation.",
  ]),
  components: guide("Manufacturing → Production → Products → Components", [
    "**Open Components:** Open the Product or component catalogue and select **Components**.",
    "**Start a component:** Select **Create Component/Part** or **Create Components**.",
    "**Enter the identity:** Complete the component **Name**, unique **Code/SKU**, unit of measure, and description.",
    "**Select tracking:** Choose serial tracking for individually identified parts or quantity/lot tracking for bulk material.",
    "**Save the component:** Select **Create Component**, then confirm it can be searched while editing a BOM.",
  ]),
  "products-and-variants": guide("Manufacturing → Production → Products", [
    "**Open Products:** Open **Production** and select **Products**.",
    "**Start a product:** Select **Create Product**.",
    "**Enter basic information:** Complete **Name**, unique **SKU/Code**, Product Family, and the required unit or category fields.",
    "**Add Variants:** Add each meaningful configuration and complete the identifying values for every Variant.",
    "**Configure production:** Add the shared or Variant BOM entries and a serial-number template when required.",
    "**Create the product:** Review validation messages and select **Create Product**.",
  ]),
  "bill-of-materials": guide("Manufacturing → Production → Products → Product detail → BOM", [
    "**Open the Product:** Open **Production → Products**, search for the Product, and select it.",
    "**Open the BOM:** Select the Product's **BOM** or **BOM Versions** section and open the draft version.",
    "**Add Components:** Select **Add Component**, search for each Component, and enter the required quantity.",
    "**Set coverage:** Use shared entries for common material and Variant entries only where requirements differ.",
    "**Review quantities:** Confirm units of measure, quantities per finished unit, effective dates, and substitutes when used.",
    "**Save the version:** Select **Save** and resolve any missing-coverage validation before activation.",
  ]),
  "activate-bom": guide("Manufacturing → Production → Products → Product detail → BOM Versions", [
    "**Open BOM Versions:** Open the Product and select **BOM Versions**.",
    "**Choose the draft:** Open the version that production should use.",
    "**Review the items:** Confirm at least one Component exists and every Variant has valid BOM coverage.",
    "**Activate the version:** Select **Activate**, **Approve**, or the available release action and confirm the dialog.",
    "**Verify the result:** Confirm the status shows **Active** before creating or activating a Routing.",
  ]),
  "material-tracking": guide("Inventory → Inventory and Manufacturing → Production", [
    "**Open the Component:** Search the component catalogue and open the required Component.",
    "**Choose its tracking rule:** Select serial tracking for individual identities or lot/quantity tracking for bulk material.",
    "**Receive inventory:** Use the inventory receipt flow to capture serials, supplier lots, internal lots, and quantities.",
    "**Add it to the BOM:** Open the Product BOM, select the Component, and enter the required quantity.",
    "**Test consumption:** Run a small operation and scan a serial or enter a quantity to confirm genealogy is recorded.",
  ]),
  "create-routing": guide("Manufacturing → Process & Engineering → Routing", [
    "**Open Routing:** Open **Process & Engineering** and select **Routing**.",
    "**Start a Routing:** Select **Create Routing**, then choose the Product, active BOM Version, name, and applicable Variants.",
    "**Build the flow:** Add one **Start** node, the required operation nodes, and one **End** node.",
    "**Assign Stations:** Select a main Station and a different Repair Station for every operation that can fail.",
    "**Connect and configure:** Connect all nodes, then add required Components, tools, instructions, quality checks, and packaging settings.",
    "**Validate and activate:** Select **Validate**, resolve every error, save the Routing, and set it to **Active**.",
  ]),
  "product-line-assignment": guide("Manufacturing → Production → Products → Product detail → Lines", [
    "**Open the Product:** Open **Production → Products**, search for the Product, and select it.",
    "**Find Line assignments:** Open the **Lines**, **Assigned Lines**, or production assignment section.",
    "**Add a Line:** Select **Assign Line** or **Add Line**, then choose an active Line that can build the Product.",
    "**Add alternatives carefully:** Select additional Lines only when the same Product may start or run on them.",
    "**Save and verify:** Save the assignment and confirm at least one eligible Line has **Is Starting Line** enabled.",
  ]),
  "starting-lines-and-capacity": guide("Manufacturing → Process & Engineering → Line", [
    "**Open the Line:** Open **Process & Engineering → Line**, search for the Line, and select **Edit**.",
    "**Set starting eligibility:** Turn on **Is Starting Line** only if Production Tasks may begin there.",
    "**Set queue capacity:** Enter **Task Queue Capacity** for the maximum pending and active tasks the Line can safely hold.",
    "**Set production capacity:** Review **Capacity Per Hour** and **Capacity Per Shift** and enter realistic values.",
    "**Save and test:** Select **Save**, then open Work Order capacity planning and confirm the Line shows the expected headroom.",
  ]),
  "product-identifiers": guide("Manufacturing → Production → Work Orders → Identifier Management", [
    "**Open Identifier Management:** Open **Production → Work Orders** and select **Identifier Management**.",
    "**Create a mapping:** Select the create action and choose the Product and identifier type.",
    "**Choose the source:** Select a generation **Template**, controlled **Range**, or preloaded **Bundle**.",
    "**Set requirements:** Mark the mapping required when every finished unit must receive a value.",
    "**Save and verify availability:** Save the mapping and confirm enough unused values exist for the planned Work Order quantity.",
  ]),
  "create-work-order": guide("Manufacturing → Production → Work Orders", [
    "**Open Work Orders:** Open **Production** and select **Work Orders**.",
    "**Start an order:** Select **Create Work Order**.",
    "**Select demand:** Choose the Production Order when used, then select the Client, Product, and Variant.",
    "**Enter execution details:** Complete the unique name, quantity, priority, future due date, and at least one Shift.",
    "**Review readiness:** Confirm the Product has an active BOM, active Routing, and eligible Line assignment.",
    "**Create the order:** Select **Create Work Order** and open the new record to continue the start journey.",
  ]),
  "generate-unit-serials": guide("Manufacturing → Production → Work Orders → Work Order detail", [
    "**Open the Work Order:** Search the Work Orders list and select the draft Work Order.",
    "**Open the start journey:** Select **Start**, **Prepare**, or the available production-start action.",
    "**Generate serials:** Open **Serial Numbers** and select **Generate** using the configured Product template or supported method.",
    "**Review the batch:** Check every generated value, remove invalid duplicates, and select **Confirm**.",
    "**Match the quantity:** Verify the confirmed serial count exactly equals the final Work Order quantity.",
  ]),
  "capacity-and-routing": guide("Manufacturing → Production → Work Orders → Work Order start journey", [
    "**Open Capacity and Lines:** Open the draft Work Order's start journey and select **Capacity and Lines**.",
    "**Review eligible Lines:** Compare current task load and available headroom on Starting Lines.",
    "**Choose assignment mode:** Select automatic balancing or choose manual assignment.",
    "**Complete manual assignments:** When manual mode is used, select **Add Line Assignment** until the full quantity is allocated.",
    "**Select the Routing:** Choose the active Routing that applies to the selected Product and Variant, then save the plan.",
  ]),
  "pre-start-validation": guide("Manufacturing → Production → Work Orders → Work Order start journey", [
    "**Open Pre-start validation:** Open the prepared Work Order and select the validation step.",
    "**Run validation:** Select **Validate** after serials, Line capacity, and Routing are complete.",
    "**Resolve blockers:** Open each failed check and correct Product, BOM, serial, identifier, inventory, or capacity data.",
    "**Re-run the checks:** Select **Validate** again until no blocking result remains.",
    "**Release production:** Review warnings, then select **Release Work Order** and confirm the action.",
  ]),
  "production-tasks": guide("Manufacturing → Production → Production Tasks", [
    "**Open Production Tasks:** Open **Production** and select **Production Tasks**.",
    "**Find a unit:** Search by finished-unit serial, Work Order, Product, Line, or status.",
    "**Open the Task:** Select the task to view its current operation, assigned Line, Station, and Routing position.",
    "**Review status and history:** Open status details and Route Logs to see completed and pending operations.",
    "**Take the valid action:** Use the available start, hold, repair, reassign, or completion action based on the current state.",
  ]),
  "operator-flow": guide("Manufacturing → Station work area", [
    "**Open the Station work area:** Select the operator's Station and scan or enter the finished-unit serial.",
    "**Review the operation:** Read the instructions, required Components, tools, and quality gates.",
    "**Capture inputs:** Scan each serialised Component and enter the exact quantity for bulk Components.",
    "**Record the result:** Complete required checks and select the pass, fail, hold, or repair outcome.",
    "**Finish the operation:** Select **Complete** so Forge records the Route Log and moves the unit to its next valid step.",
  ]),
  "material-consumption": guide("Manufacturing → Station work area → Current operation", [
    "**Open the unit:** At the Station work area, scan the finished-unit serial and open the current operation.",
    "**Open Materials:** Select the Components or material-consumption section.",
    "**Scan serialised material:** Scan every required Component serial and verify the matched Component.",
    "**Enter bulk quantities:** Select the lot or location and enter the quantity consumed for non-serialised material.",
    "**Complete the operation:** Review the captured material and select **Complete** to write consumption and genealogy.",
  ]),
  "statuses-and-route-logs": guide("Manufacturing → Production → Work Orders or Production Tasks", [
    "**Find the record:** Search for the Work Order or Production Task and open it.",
    "**Review the current status:** Check the status chip and current Routing operation.",
    "**Open Route Logs:** Select the history, timeline, or **Route Logs** tab.",
    "**Inspect an event:** Open an entry to review Station, operator, result, timestamps, Components, and exceptions.",
    "**Filter or export:** Apply the available filters or export the history when it is needed for investigation.",
  ]),
  "quality-controls": guide("Manufacturing → Quality → Quality Settings or Quality Inspections", [
    "**Open Quality:** Open **Quality** and select **Quality Settings** or **Quality Inspections**.",
    "**Create the control:** Select the create action and enter the inspection or sampling name and criteria.",
    "**Select the scope:** Choose the Product, Station, Routing operation, or other supported trigger.",
    "**Define outcomes:** Configure pass, fail, escalation, hold, defect, or sampling behavior.",
    "**Save and test:** Save the control and run a small unit through the operation to confirm it appears.",
  ]),
  "inspection-to-capa": guide("Manufacturing → Quality", [
    "**Open the inspection:** Select **Quality Inspections**, search for the relevant record, and open it.",
    "**Record the result:** Complete every criterion and select the pass or fail result.",
    "**Capture the issue:** On failure, create or link a **Defect** with evidence and affected quantity.",
    "**Control the output:** Open **NCR Reports** and create or link an NCR, then record the Disposition.",
    "**Escalate when required:** Open **CAPA**, create the corrective/preventive action, assign ownership, and save.",
  ]),
  "repair-and-rework": guide("Manufacturing → Repair & Rework", [
    "**Open the repair queue:** Open **Repair & Rework** and select **Repair Queue**.",
    "**Find the unit:** Search by serial or Work Order and open the failed Production Task.",
    "**Record diagnosis:** Enter symptoms, failure diagnosis, repair actions, and replacement Components.",
    "**Validate the repair:** Complete the required checks and select the valid repair result.",
    "**Return or rework:** Send the unit back to the allowed Routing point or create the controlled Rework action.",
  ]),
  "hold-scrap-teardown": guide("Manufacturing → Quality or Scrap & Teardown", [
    "**Open the affected unit:** Find the Production Task, quality record, or material record.",
    "**Choose the exception:** Select **Hold**, **Scrap**, or **Teardown** according to the approved decision.",
    "**Enter the reason:** Select the configured reason and add notes, evidence, affected quantity, and ownership.",
    "**Confirm the action:** Review the irreversible impact before selecting **Confirm**.",
    "**Complete follow-up:** Release a Hold only after resolution, or record recovered Components during Teardown.",
  ]),
  packaging: guide("Manufacturing → Packaging & Shipping → Packaging", [
    "**Open Packaging:** Open **Packaging & Shipping** and select **Packaging**.",
    "**Start or find a container:** Scan an existing container or select the action to create one using the correct Container Type.",
    "**Add finished units:** Scan each eligible finished-unit serial into the container.",
    "**Run checks:** Complete configured component, count, weight, and label verification.",
    "**Close the container:** Review its contents, print the label, and select the close or complete action.",
  ]),
  "containers-and-labels": guide("Manufacturing → Packaging & Shipping", [
    "**Open packaging configuration:** Open the Container Type, packaging rules, or label-template area.",
    "**Create the Container Type:** Enter its name, code, capacity, and allowed parent/child relationships.",
    "**Create the label:** Select the label-template action and add the serial, product, quantity, and shipment fields required for scanning.",
    "**Select printing behavior:** Choose printer, copies, and reprint permissions.",
    "**Save and test:** Save the configuration and print a test label before production use.",
  ]),
  "shipment-verification": guide("Manufacturing → Packaging & Shipping → Shipment Verification", [
    "**Open Shipment Verification:** Open **Packaging & Shipping** and select **Shipment Verification**.",
    "**Find the shipment:** Search by shipment, ASN, order, or container and open the record.",
    "**Scan the contents:** Scan every container or finished unit expected in the shipment.",
    "**Resolve differences:** Review missing, extra, duplicate, quantity, and status exceptions.",
    "**Complete verification:** Confirm the final population and select the complete or approve action.",
  ]),
  "traceability-genealogy-recall": guide("Manufacturing → Traceability → Master Traceability", [
    "**Open Master Traceability:** Open **Traceability** and select **Master Traceability**.",
    "**Choose the lookup:** Select finished-unit, Component serial, material lot, or container search.",
    "**Enter or scan the identity:** Submit the serial, batch, lot, or container value.",
    "**Review history:** Inspect the Work Order, operation timeline, Stations, quality events, packaging, and shipment.",
    "**Follow genealogy:** Expand upstream consumed material and downstream affected units.",
    "**Start containment when needed:** Use the verified result to export the population or create a Recall Notice.",
  ]),
  dashboards: guide("Insights → Dashboards", [
    "**Open Insights:** Select **Insights** in the main navigation and open **Dashboards**.",
    "**Choose a dashboard:** Select Production, Work Order, Station, Operator, Quality, Downtime, or another relevant view.",
    "**Set the scope:** Select Plant, Site, Line, Shift, Product, Work Order, status, and date filters as available.",
    "**Inspect the result:** Select a metric, chart segment, or row to open the underlying records.",
    "**Refresh or export:** Refresh after operational changes or use the available export action for controlled sharing.",
  ]),
  "shift-operations": guide("Manufacturing → Shifts & Labor → Shift Handovers", [
    "**Open Shift Handovers:** Open **Shifts & Labor** and select **Shift Handovers**.",
    "**Create a handover:** Select **Create Shift Handover** and choose the outgoing and incoming Shift details.",
    "**Record current conditions:** Add active Work Orders, WIP, holds, downtime, material risk, and quality issues.",
    "**Assign unresolved actions:** Select the owner and due action for every open item.",
    "**Save and acknowledge:** Save the handover and have the incoming Shift review or acknowledge it.",
  ]),
  "tools-and-maintenance": guide("Manufacturing → Process & Engineering → Tools", [
    "**Open Tools:** Open **Process & Engineering** and select **Tools**.",
    "**Create or find the Tool:** Select the create action or search for the existing Tool record.",
    "**Enter control details:** Complete identity, type, status, location, calibration, and maintenance fields.",
    "**Move it to the Station:** Use the transfer or assignment action to place the Tool at its operating Station.",
    "**Connect and monitor:** Assign it to the Routing operation and review maintenance or calibration alerts before use.",
  ]),
  "reports-and-audit": guide("Insights and Settings → Audit Trail", [
    "**Open the required report:** Open **Insights** or the module's report page and choose the relevant report.",
    "**Set filters:** Select Plant, date range, Product, Line, Work Order, status, or other required scope.",
    "**Review the records:** Open suspicious totals or rows to inspect the underlying operational record.",
    "**Export when required:** Select **Export** or **Download** and retain the chosen filters with the file.",
    "**Check changes:** Open **Settings → Audit Trail**, search for the entity, and review who changed it and when.",
  ]),
  "first-production-run": guide("Manufacturing → Production → Work Orders", [
    "**Create a trial Work Order:** Select **Create Work Order** and use a small but realistic quantity.",
    "**Prepare and release:** Confirm serials, capacity, Routing, material, and identifiers, then select **Release Work Order**.",
    "**Run the normal path:** Complete at least one unit through every required operation.",
    "**Test an exception:** Fail one controlled operation and complete its Repair or Rework path.",
    "**Finish and trace:** Complete applicable quality, packaging, and shipment steps, then search the unit in **Master Traceability**.",
  ]),
  troubleshooting: guide("The affected Forge module", [
    "**Open the failed record:** Return to the Product, Routing, Work Order, Production Task, or shipment showing the error.",
    "**Read the validation message:** Expand the failed check and note the exact missing field, relationship, status, or quantity.",
    "**Check prerequisites:** Verify active BOM, Stations, Repair Stations, Shift, Line assignment, capacity, serials, inventory, and identifiers as applicable.",
    "**Correct the source record:** Open the linked configuration, make the required change, and select **Save**.",
    "**Retry the action:** Return to the original record and select **Validate**, **Create**, **Release**, or **Complete** again.",
  ]),
};

export function getForgeTaskGuide(slug: string): ForgeTaskGuide | undefined {
  return TASK_GUIDES[slug];
}
