import type { ForgeTaskGuide } from "./forge-task-guides";

const guide = (navigationPath: string, steps: string[]): ForgeTaskGuide => ({
  navigationPath,
  steps,
});

export const TASK_GUIDES_TA: Record<string, ForgeTaskGuide> = {
  "complete-setup-journey": guide("Fynd ERP Dashboard", [
    "**Manufacturing பயணத்தைத் திறங்கள்:** உங்கள் process-க்கு தேவையான வரிசையில் Production, Process & Engineering, Quality, மற்றும் அடுத்த manufacturing modules வழியாக வேலை செய்ய இடது navigation-ஐ பயன்படுத்துங்கள்.",
    "**தொழிற்சாலைப் பதிவுகளை உருவாக்குங்கள்:** Sites, Lines, operation Stations, Repair Stations, மற்றும் Shift Definitions-ஐ உருவாக்குங்கள்.",
    "**தயாரிப்புப் பதிவுகளை உருவாக்குங்கள்:** Project, Product Family, Components, Product, Variants, மற்றும் BOM Version-ஐ உருவாக்குங்கள்.",
    "**செயலாக்கத்தைத் தயார் செய்யுங்கள்:** BOM-ஐச் செயலில் ஆக்கி, Routing-ஐ உருவாக்கி சரிபார்த்து, Product-ஐ தகுதியான Lines-க்கு ஒதுக்குங்கள்.",
    "**ஒரு சோதனை ஆர்டரைத் தொடங்குங்கள்:** ஒரு சிறிய Work Order-ஐ உருவாக்கி, அலகு சீரியல்களை உறுதிப்படுத்தி, திறனையும் Routing-ஐயும் தேர்ந்தெடுத்து, சரிபார்ப்பை இயக்கி, Release-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  sites: guide("Masters → Sites", [
    "**Sites-ஐத் திறங்கள்:** Fynd ERP இடது வழிசெலுத்தலில் **Masters**-ஐத் திறந்து **Sites**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு புதிய பதிவைத் தொடங்குங்கள்:** மேல்-வலது மூலையில் **Create Site**-ஐத் தேர்ந்தெடுங்கள்.",
    "**உருவாக்கும் முறையைத் தேர்ந்தெடுங்கள்:** Form-ஐ நீங்களே நிரப்ப **Create Manually**-ஐத் தேர்ந்தெடுக்கவும்; prompt மூலம் விவரங்களை வரைவு செய்ய AI-assisted விருப்பத்தையும் பயன்படுத்தலாம்.",
    "**தேவையான அடையாளத்தை உள்ளிடுங்கள்:** **Name** மற்றும் **Code** கட்டாயம். Code-இல் எழுத்துகள், எண்கள், மற்றும் hyphen மட்டுமே அனுமதிக்கப்படும்.",
    "**தேவைப்பட்டால் இருப்பிடத்தைச் சேர்க்குங்கள்:** Address fields விருப்பமானவை. **State / Province / Region**-க்கு முன் **Country**-ஐத் தேர்ந்தெடுக்கவும்; தேர்ந்தெடுத்த இடத்தின் அடிப்படையில் City values வடிகட்டப்படும்.",
    "**விருப்ப metadata-ஐ கவனமாகச் சேர்க்குங்கள்:** Metadata 32 KB வரம்புக்குள் இருக்க வேண்டும்; தேடலுக்கு உதவும்போது மட்டும் tags சேர்க்குங்கள்.",
    "**உருவாக்கி சரிபார்க்குங்கள்:** **Create**-ஐத் தேர்ந்தெடுத்து, Site பட்டியலில் புதிய Site தோன்றுவதையும் Station உருவாக்கும்போது அதைத் தேர்ந்தெடுக்க முடிவதையும் உறுதிப்படுத்துங்கள்.",
  ]),
  lines: guide("Mfg → Process & Engineering → Line", [
    "**Lines-ஐத் திறங்கள்:** **Mfg**-ஐத் திறந்து, **Process & Engineering**-ஐ விரித்து, **Line**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு புதிய line-ஐத் தொடங்குங்கள்:** மேல்-வலது மூலையில் **Create Line**-ஐத் தேர்ந்தெடுங்கள்.",
    "**உருவாக்கும் முறையைத் தேர்ந்தெடுங்கள்:** Form-ஐ நிரப்ப **Create Manually**-ஐத் தேர்ந்தெடுக்கவும்; prompt மூலம் Line draft செய்ய AI-assisted விருப்பத்தையும் பயன்படுத்தலாம்.",
    "**தேவையான விவரங்களை உள்ளிடுங்கள்:** **Name**, **Code**, மற்றும் **Line Type** கட்டாயம். **Site** விருப்பமானது; Line ஒரு குறிப்பிட்ட இடத்துக்குச் சேர்ந்தால் அதைத் தேர்ந்தெடுக்கவும்.",
    "**திறனை அமைக்குங்கள்:** **Capacity Per Shift**, **Capacity Per Hour**-ஐ விட அதிகமாக இருக்க வேண்டும்; **Task Queue Capacity** 1 முதல் 100,000 வரையிலான முழு எண்ணாக இருக்க வேண்டும்.",
    "**தொடக்க நடத்தையைத் தேர்வுசெய்யுங்கள்:** Capacity planning-இல் இந்த Line ஆரம்ப task assignment-ஐப் பெறக்கூடியபோது மட்டுமே **Is Starting Line**-ஐ இயக்குங்கள். தகுதியான SMT மற்றும் BLT starting Lines-க்கு form இதை உறுதிப்படுத்தும்.",
    "**Line-ஐ உருவாக்குங்கள்:** Line-ஐ active-ஆக வைத்திருந்து மதிப்புகளை மதிப்பாய்வு செய்து **Create**-ஐத் தேர்ந்தெடுக்கவும். புதிய Line அதன் Site, type, status, மற்றும் hourly capacity உடன் பட்டியலில் தோன்றுவதை உறுதிப்படுத்துங்கள்.",
  ]),
  "stations-and-repair-stations": guide(
    "Mfg → Process & Engineering → Stations",
    [
      "**Stations-ஐத் திறங்கள்:** **Mfg**-ஐத் திறந்து, **Process & Engineering**-ஐ விரித்து, **Stations**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Station-ஐத் தொடங்குங்கள்:** **Create Station**-ஐத் தேர்ந்தெடுத்து **Create Manually**-ஐத் தேர்வு செய்யவும்; AI-assisted விருப்பத்தின் மூலம் record draft செய்யவும் முடியும்.",
      "**தேவையான விவரங்களை உள்ளிடுங்கள்:** **Station Name**, **Station Code**, **Site Location**, மற்றும் **Station Category** கட்டாயம்.",
      "**Station-ஐ வகைப்படுத்துங்கள்:** **Station Type** அதன் production behavior-ஐ நிர்ணயிக்கும்; **Station Category** production பயன்பாட்டிற்காக அதை ஒழுங்குபடுத்தும். புதிய Stations **Idle** மற்றும் **Regular** ஆக default ஆகும்.",
      "**Operation Station-ஐ உருவாக்குங்கள்:** SMT placement Station-க்கு Assembly Site மற்றும் category-ஐத் தேர்ந்தெடுத்து **Create Station**-ஐத் தேர்வு செய்யவும்.",
      "**Repair Station-ஐ உருவாக்குங்கள்:** Flow-ஐ மீண்டும் செய்து **Station Type** மற்றும் **Station Category** இரண்டையும் **Repair** ஆக அமைக்கவும்.",
      "**இரண்டு records-ஐயும் சரிபார்க்குங்கள்:** Regular Assembly Station மற்றும் Repair Station சரியான Site, type, category, மற்றும் Idle status உடன் பட்டியலில் உள்ளன என்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  shifts: guide("Mfg → Shifts & Labor → Shift Definitions", [
    "**Shift Definitions-ஐத் திறங்கள்:** **Mfg**-ஐத் திறந்து, **Shifts & Labor**-ஐ விரித்து, **Shift Definitions**-ஐத் தேர்ந்தெடுங்கள்.",
    "**Shift-ஐத் தொடங்குங்கள்:** **Create Shift**-ஐத் தேர்ந்தெடுத்து **Create Manually**-ஐத் தேர்வு செய்யவும்; AI-assisted விருப்பத்தின் மூலம் schedule draft செய்யவும் முடியும்.",
    "**தேவையான schedule-ஐ உள்ளிடுங்கள்:** **Shift Name**, **Code**, **Shift Type**, **Start Time**, மற்றும் **End Time** கட்டாயம். Code-இல் uppercase எழுத்துகள், எண்கள், மற்றும் hyphen மட்டுமே அனுமதிக்கப்படும்.",
    "**பொருத்தமான Shift Type-ஐப் பயன்படுத்துங்கள்:** Morning, Afternoon, Night, General, Rotational, அல்லது Split-ஐத் தேர்ந்தெடுக்கவும். தேர்ந்தெடுத்த type-க்கு form பொருத்தமான default color-ஐ வழங்கும்.",
    "**செல்லுபடியாகும் நேரத்தை அமைக்குங்கள்:** Duration மற்றும் net working time தானாக கணக்கிடப்படும். Overnight Shifts-க்கு end time அடுத்த நாளில் இருக்கலாம்.",
    "**Breaks-ஐ அமைக்குங்கள்:** **Add Break**-ஐத் தேர்ந்தெடுத்து பெயர், type, மற்றும் குறைந்தது ஒரு நிமிட duration-ஐ உள்ளிடவும். Break start time விருப்பமானது; unpaid breaks net working time-ஐக் குறைக்கும்.",
    "**உருவாக்கி சரிபார்க்குங்கள்:** Shift-ஐ active-ஆக வைத்திருந்து **Create**-ஐத் தேர்ந்தெடுத்து, overview-இல் identity, type, timing, net working time, மற்றும் breaks சரியாக உள்ளன என்பதை உறுதிப்படுத்துங்கள்.",
  ]),
  "factory-readiness": guide(
    "Manufacturing → Factory setup and Process & Engineering",
    [
      "**Sites-ஐச் சரிபார்க்குங்கள்:** **Sites**-ஐத் திறந்து ஒவ்வொரு இயற்பியல் உற்பத்தி இருப்பிடமும் பிரதிநிதித்துவப்படுத்தப்படுகிறது என்பதை உறுதிப்படுத்துங்கள்.",
      "**Lines-ஐச் சரிபார்க்குங்கள்:** **Line**-ஐத் திறந்து நோக்கம் கொண்ட முதல் உற்பத்தி Line-க்கு **Is Starting Line** இயக்கப்பட்டுள்ளதை உறுதிப்படுத்துங்கள்.",
      "**திறனைச் சரிபார்க்குங்கள்:** ஒவ்வொரு Line-ஐயும் திறந்து **Task Queue Capacity**, மணிநேரத் திறன், மற்றும் shift திறனை மதிப்பாய்வு செய்யுங்கள்.",
      "**Stations-ஐச் சரிபார்க்குங்கள்:** **Stations**-ஐத் திறந்து ஒவ்வொரு Routing operation மற்றும் தோல்விப் பாதைக்கும் ஒரு செயலில் உள்ள Station உள்ளதை உறுதிப்படுத்துங்கள்.",
      "**ஒரு சிறிய சரிபார்ப்பை இயக்குங்கள்:** தொழிற்சாலை மாதிரி Production Tasks-ஐ ஏற்று வழிநடத்த முடியும் என்பதை உறுதிப்படுத்த ஒரு சிறிய Work Order அளவைப் பயன்படுத்துங்கள்.",
    ],
  ),
  "projects-and-product-families": guide("Mfg → Production → Product Families", [
    "**Product Families-ஐத் திறங்கள்:** **Mfg**-ஐத் திறந்து, **Production**-ஐ விரித்து, **Product Families**-ஐத் தேர்ந்தெடுங்கள்.",
    "**List-ஐ review செய்யுங்கள்:** புதிய Family உருவாக்கும் முன் search மற்றும் filters மூலம் ஏற்கனவே உள்ளதா பாருங்கள்.",
    "**Product Family-ஐ தொடங்குங்கள்:** Available create action-ஐத் தேர்வு செய்து required **Name** மற்றும் **Code** உள்ளிடுங்கள்.",
    "**Classification சேர்க்கவும்:** Product group-க்கு பொருந்தினால் மட்டும் Type, Status, Project, அல்லது வேறு context-ஐ தேர்வு செய்யுங்கள்.",
    "**Create செய்து verify செய்யுங்கள்:** Product Family-ஐ save செய்து code, status, type, Project context, மற்றும் product count list-ல் சரியா என்று பாருங்கள்.",
    "**Project context-ஐச் சரிபார்க்குங்கள்:** **Mfg → Production** கீழ் Projects தனி option தெரியாவிட்டால், Product Family screen-ல் கிடைக்கும் Project field அல்லது linked Project context-ஐ மட்டும் பயன்படுத்துங்கள்.",
  ]),
  components: guide("Masters → Item Master", [
    "**Item Master-ஐத் திறங்கள்:** **Masters**-ஐத் திறந்து **Item Master**-ஐத் தேர்ந்தெடுத்து, பின்னர் **Add Item**-ஐத் தேர்வு செய்யுங்கள்.",
    "**கட்டாய அடையாளத்தை உள்ளிடுங்கள்:** **Name**, தனித்துவமான **Code**, மற்றும் **Unit**-ஐ நிரப்புங்கள். Code-இல் எழுத்துகள், எண்கள், மற்றும் hyphen அனுமதிக்கப்படும்.",
    "**நிரந்தர அமைப்புகளை மதிப்பாய்வு செய்யுங்கள்:** Unit, Track by Serial Number, Consumable Component, Fixed Serial, மற்றும் Track by Non-Serialized ஆகியவற்றை உருவாக்கிய பின் மாற்ற முடியாது.",
    "**Tracking-ஐ அமைக்குங்கள்:** **Track by Serial Number**-ஐ இயக்கினால் Consumable மற்றும் Fixed Serial முடக்கப்படும். Mixed serial மற்றும் lot tracking-க்கு **Track by Non-Serialized** அதே நேரத்தில் இயக்கப்பட்டிருக்கலாம்.",
    "**Stock வரம்புகளை அமைக்குங்கள்:** Reorder point, maximum stock-ஐ மீறக்கூடாது; minimum stock-ஐ reorder point-க்கு சமமாகவோ அதற்குக் குறைவாகவோ வைத்திருங்கள்.",
    "**உருவாக்கிச் சரிபாருங்கள்:** **Create Component/Part**-ஐத் தேர்ந்தெடுத்து code, unit, serialized status, மற்றும் non-serialized tracking உள்ள success summary-ஐ மதிப்பாய்வு செய்யுங்கள்.",
    "**மாற்றக்கூடிய விவரங்களை update செய்யுங்கள்:** **Item Master**-இல் material-ஐ மீண்டும் திறந்து, அனுமதிக்கப்பட்ட identity, stock, supplier, அல்லது description fields-ஐ தேவைக்கேற்ப edit செய்யுங்கள். Unit மற்றும் permanent tracking controls creation-க்குப் பிறகு locked ஆக இருக்கும்.",
    "**Inventory activity-ஐ track செய்யுங்கள்:** Inventory Lots, Serials, Usage History, மற்றும் தொடர்புடைய inventory views மூலம் stock receive செய்து, lot, serial, quantity, மற்றும் consumption history-ஐப் பின்தொடருங்கள்.",
  ]),
  "products-and-variants": guide("Mfg → Production → Products", [
    "**Products-ஐத் திறங்கள்:** **Mfg**-ஐத் திறந்து **Production**-ஐ விரித்து **Products**-ஐத் தேர்ந்தெடுங்கள்.",
    "**Product-ஐத் தொடங்குங்கள்:** **Create Product**-ஐத் தேர்ந்தெடுத்து **Create Manually**-ஐத் தேர்வு செய்யுங்கள்; AI-assisted விருப்பத்தையும் பயன்படுத்தலாம்.",
    "**கட்டாயத் தகவலை உள்ளிடுங்கள்:** **Product Name** மற்றும் தனித்துவமான **SKU** கட்டாயம். Product Description மற்றும் Product Family விருப்பமானவை.",
    "**Batch multiplier-ஐ அமைக்குங்கள்:** Multiplier ஒரு batch-இல் உருவாகும் units-ஐ வரையறுக்கிறது; அது 1 அல்லது அதற்கு மேற்பட்ட முழு எண்ணாக இருக்க வேண்டும்.",
    "**தேவைப்பட்டால் Variants-ஐச் சேர்க்குங்கள்:** Variants விருப்பமானவை. ஒவ்வொரு வேறுபட்ட configuration-க்கும் தனித்துவமான Variant SKU, Status, மற்றும் Storage/Color போன்ற optional key-value attributes-ஐ உள்ளிடுங்கள்.",
    "**BOM prerequisite-ஐ பூர்த்தி செய்யுங்கள்:** குறைந்தது ஒரு Shared BOM component-ஐச் சேர்க்கவும் அல்லது ஒவ்வொரு Variant-க்கும் BOM சேர்க்கவும். இவற்றில் ஒன்று இல்லாமல் Product-ஐ உருவாக்க முடியாது.",
    "**உருவாக்கிச் சரிபாருங்கள்:** **Create Product**-ஐத் தேர்ந்தெடுத்து Products பட்டியலில் Product, SKU, active status, மற்றும் Variant count-ஐ உறுதிப்படுத்துங்கள்.",
  ]),
  "bill-of-materials": guide(
    "Mfg → Production → Products → Product detail → BOM Versions",
    [
      "**Product-ஐத் திறங்கள்:** **Mfg → Production → Products**-ஐத் திறந்து Product-ஐக் கண்டுபிடித்து **View** மூலம் details-ஐத் திறங்கள்.",
      "**Draft version-ஐத் திறங்கள்:** **BOM Versions** கீழ் **View Version Details** மூலம் **Initial Version (V1)**-ஐத் திறந்து, Product உருவாக்கும்போது சேர்த்த BOM items Draft-இல் உள்ளனவா உறுதிப்படுத்துங்கள்.",
      "**BOM item-ஐச் சேர்க்குங்கள்:** **Add Item**-ஐத் தேர்ந்தெடுங்கள். Version Draft நிலையில் இருக்கும் போது items-ஐச் சேர்க்கலாம்.",
      "**Scope-ஐத் தேர்ந்தெடுங்கள்:** எல்லா Variants-க்கும் பொதுவான material-க்கு **Shared** பயன்படுத்துங்கள். Configuration-specific material-க்கு மட்டும் Variant BOM-ஐத் தேர்ந்தெடுங்கள்.",
      "**Quantity மற்றும் unit-ஐ அமைக்குங்கள்:** Quantity குறைந்தது 1. Production வேறு compatible unit-ஐப் பயன்படுத்தும் போது மட்டும் optional **Unit Override**-ஐப் பயன்படுத்துங்கள்.",
      "**Components-ஐத் தேர்ந்தெடுத்துச் சேர்க்குங்கள்:** **Select Components** அல்லது **Bulk Upload** மூலம் Component records-ஐத் தேர்ந்தெடுத்து **Add Items**-ஐத் தேர்வு செய்யுங்கள்.",
      "**Draft-ஐச் சரிபார்க்குங்கள்:** Total Items மற்றும் Shared/Variant BOM table-இல் ஒவ்வொரு Component, code, tracking type, quantity, மற்றும் unit தோன்றுவதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "activate-bom": guide(
    "Mfg → Production → Products → Product detail → BOM Versions",
    [
      "**BOM Version-ஐத் திறங்கள்:** Product-இல் production பயன்படுத்த வேண்டிய Draft version-க்கு **View Version Details**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Draft-ஐ மதிப்பாய்வு செய்யுங்கள்:** Usage Type, effective dates, Total Items, மற்றும் Shared/Variant coverage சரியாக உள்ளதா என உறுதிப்படுத்துங்கள்.",
      "**Version-ஐ release செய்யுங்கள்:** **Release**-ஐத் தேர்ந்தெடுத்து **Release BOM Version**-ஐ உறுதிப்படுத்துங்கள். Release செய்த பின் version-ஐத் திருத்த முடியாது.",
      "**Active-version நடத்தையைப் புரிந்துகொள்ளுங்கள்:** வேறு active version பாதிக்கப்படுமா என்பதை confirmation காட்டும். இந்த workflow-இல் V1 Product-இன் ஒரே active BOM version ஆகிறது.",
      "**முடிவைச் சரிபார்க்குங்கள்:** Status **Active**, item editing controls அகற்றப்பட்டுள்ளன, release audit fields பதிவாகியுள்ளன, மற்றும் **Create Routing** கிடைக்கிறது என்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "material-tracking": guide(
    "Masters → Item Master → Component detail",
    [
      "**உருவாக்குவதற்கு முன் tracking-ஐ அமைக்குங்கள்:** Track by Serial Number மற்றும் Track by Non-Serialized ஆகியவை Component உருவாக்கிய பின் மாற்ற முடியாதவை. இரண்டையும் இயக்குவது inventory lots-க்குள் தனிப்பட்ட serial identity-ஐ வழங்கும்.",
      "**Component-ஐத் திறங்கள்:** **Masters → Item Master**-ஐத் திறந்து Component-ஐக் கண்டுபிடித்து அதன் details-ஐத் திறங்கள். Tracking Type மற்றும் **Inventory Lots**, **Serials** tabs-ஐ உறுதிப்படுத்துங்கள்.",
      "**Lot receipt-ஐத் தொடங்குங்கள்:** **Inventory Lots**-ஐத் திறந்து **Add Lot**-ஐத் தேர்ந்தெடுத்து **Create Manually** அல்லது AI-assisted விருப்பத்தைப் பயன்படுத்துங்கள்.",
      "**கட்டாய receipt fields-ஐ உள்ளிடுங்கள்:** Lot Number, Quantity Received, Vendor, Location Type, மற்றும் Storage Location கட்டாயம். Vendor மற்றும் destination location முன்கூட்டியே இருக்க வேண்டும்.",
      "**Lot-ஐ உருவாக்குங்கள்:** Batch Number, dates, invoice, manufacturer data, notes, dimensions, மற்றும் metadata விருப்பமானவை. மதிப்பாய்வுக்குப் பின் **Create**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Serialized stock-ஐ பதிவு செய்யுங்கள்:** Serialized Component-க்கு serials பதிவு செய்யும் வரை received quantity கிடைக்காது. **Add Component Serials**-இல் **Manual Entry** அல்லது **Bulk Entry** பயன்படுத்துங்கள்.",
      "**Availability-ஐச் சரிபார்க்குங்கள்:** Lot-இல் received serial count, available quantity, Vendor, மற்றும் Storage Location-ஐ உறுதிப்படுத்துங்கள்; consumption மற்றும் genealogy-க்கு Usage History-ஐ பயன்படுத்துங்கள்.",
    ],
  ),
  "create-routing": guide("Masters → Products → Product detail → Create Routing", [
    "**Product-இலிருந்து தொடங்குங்கள்:** Product detail-ஐத் திறந்து **Create Routing**-ஐத் தேர்ந்தெடுங்கள். Routing configurator அந்த Product-ஐத் தானாகப் பயன்படுத்தும்.",
    "**கட்டாய configuration-ஐத் தேர்ந்தெடுங்கள்:** குறைந்தது ஒரு Variant-ஐத் தேர்ந்தெடுத்து தொடருங்கள்; பின்னர் **Active** BOM Version-ஐத் தேர்ந்தெடுங்கள். Inactive BOM versions இங்கு கிடைக்காது.",
    "**Workflow-க்கு பெயரிடுங்கள்:** கட்டாய Workflow Name-ஐ உள்ளிட்டு, விருப்பமான description-ஐச் சேர்த்து, production-க்கு route கிடைக்க வேண்டும் என்றால் **Active**-ஐ இயக்கியவாறு வையுங்கள்.",
    "**Operation-ஐச் சேர்க்குங்கள்:** **Add Stage → Create Manually**-ஐத் தேர்ந்தெடுத்து main Station-ஐத் தேர்வு செய்து unique Operation Name-ஐ உள்ளிடுங்கள். Repair Station கட்டாயம்; அது main Station-இலிருந்து வேறாக இருக்க வேண்டும்.",
    "**BOM-ஐ முழுமையாக cover செய்யுங்கள்:** **Components**-இல் தேவையான Components மற்றும் quantities-ஐ ஒதுக்குங்கள். இரு BOM coverage indicators-மும் **100%** அடைய வேண்டும்.",
    "**இணைத்து validate செய்யுங்கள்:** Stage-ஐச் save செய்து, தேவையானால் nodes-ஐ arrange செய்து, **Start → ஒவ்வொரு stage → End** என இணைக்குங்கள். Editor தானாக validate செய்து workflow valid ஆன பிறகே **Save**-ஐ இயக்கும்.",
    "**Creation-ஐ உறுதிப்படுத்துங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து workflow summary-ஐப் பரிசீலித்து **Confirm & Save**-ஐத் தேர்ந்தெடுங்கள். Routing detail page-இல் Active status, Product, Variants, BOM Version, மற்றும் Workflow Preview-ஐ உறுதிப்படுத்துங்கள்.",
  ]),
  "product-line-assignment": guide(
    "Manufacturing → Production → Products → Product detail → Assigned Lines",
    [
      "**Product-ஐத் திறங்கள்:** **Production → Products**-ஐத் திறந்து, Product-ஐத் தேடி, அதைத் தேர்ந்தெடுங்கள்.",
      "**Assigned Lines-ஐக் கண்டறியுங்கள்:** **Assigned Lines** பகுதிக்கு scroll செய்யுங்கள். இந்த Product-level section multi-line Work Order execution-ஐ இயலுமைப்படுத்தும்.",
      "**Line-ஐ assign செய்யுங்கள்:** **Assign Line**-ஐத் தேர்ந்தெடுத்து **Select Line**-ஐத் திறந்து தகுதியான manufacturing Line-ஐத் தேர்வு செய்து **Assign**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Availability-ஐச் சரியாகப் புரிந்துகொள்ளுங்கள்:** Selector **Available Lines** மற்றும் ஏற்கனவே **Assigned to Other Products** ஆன Lines-ஐப் பிரித்து, Line code மற்றும் Site-ஐக் காட்டும்.",
      "**செல்லுபடியாகும் alternatives-ஐச் சேர்க்குங்கள்:** அதே Product-ஐ உண்மையாக manufacture செய்யக்கூடிய கூடுதல் Lines-க்கு மட்டும் assignment-ஐ மீண்டும் செய்யுங்கள்.",
      "**Table-ஐச் சரிபார்க்குங்கள்:** Assigned Line name, code, status, capacity per hour, Site, மற்றும் actions-ஐ உறுதிப்படுத்துங்கள். Starting-Line eligibility தனியாக Line-இல் configure செய்யப்படுகிறது.",
    ],
  ),
  "starting-lines-and-capacity": guide(
    "Manufacturing → Process & Engineering → Line → Line detail → Edit",
    [
      "**Line-ஐத் திறங்கள்:** **Process & Engineering → Line**-ஐத் திறந்து Line name அல்லது code மூலம் தேடி, Line detail-ஐத் திறந்து **Edit**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Throughput-ஐ அமைக்குங்கள்:** **Capacity Per Hour** மற்றும் **Capacity Per Shift** optional. இரண்டையும் உள்ளிடும்போது Capacity Per Shift, Capacity Per Hour-ஐ விட அதிகமாக இருக்க வேண்டும்.",
      "**Task queue-ஐ வரையறுக்குங்கள்:** **Task Queue Capacity** optional; அது Line-இல் அனுமதிக்கப்படும் pending மற்றும் active tasks-இன் அதிகபட்ச எண்ணிக்கையை அமைக்கும். மதிப்பு இருந்தால் 1 முதல் 100,000 வரை முழு எண்ணைப் பயன்படுத்துங்கள்.",
      "**Starting eligibility-ஐ அமைக்குங்கள்:** Capacity planning-இல் Line initial task-ஐப் பெற வேண்டியபோது மட்டும் **Is Starting Line**-ஐ இயக்குங்கள். UI phase order: SMT → BLT → ASSEMBLY → TESTING → PACKING.",
      "**Save செய்து verify செய்யுங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து Line detail-இல் status, Site, Capacity Per Hour, Capacity Per Shift, மற்றும் assigned Products சரியாக உள்ளதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  templates: guide("Mfg → Process & Engineering → Templates", [
    "**Templates-ஐத் திறங்கள்:** **Mfg** திறந்து, **Process & Engineering** விரிவாக்கி, **Templates** தேர்ந்தெடுங்கள்.",
    "**Template தொடங்குங்கள்:** **Create Template** தேர்ந்தெடுத்து, **Create Manually** தேர்வு செய்யுங்கள் அல்லது AI-assisted option மூலம் draft உருவாக்குங்கள்.",
    "**கட்டாய identity உள்ளிடுங்கள்:** **Template Name** மற்றும் **Template Type** கட்டாயம். Description விருப்பமானது.",
    "**Data scope தேர்ந்தெடுங்கள்:** **Context Type** விருப்பமானது; எந்த data sources variables-ஆக கிடைக்கும் என்பதை இது கட்டுப்படுத்துகிறது. அதிக flexibility தேவைப்பட்டால் மட்டும் அதை காலியாக விடுங்கள்.",
    "**Template உருவாக்குங்கள்:** தேர்ந்தெடுத்த type-க்கு தேவையான content, pattern, parser அல்லது validation rule சேர்க்குங்கள். PDF/HTML, HTML, CSS மற்றும் Nunjucks variables-ஐ ஆதரிக்கிறது; starter தேவைப்பட்டால் **Load Sample** பயன்படுத்துங்கள்.",
    "**Activate செய்வதற்கு முன் preview செய்யுங்கள்:** Editor, Variables மற்றும் Data Preview மூலம் realistic data கொண்டு output-ஐ சரிபாருங்கள். Template பயன்படுத்தத் தயாராக இருந்தால் மட்டும் **Active** on-இல் இருக்கட்டும்.",
    "**Save செய்து சரிபார்க்கவும்:** **Save** தேர்ந்தெடுத்து Templates list-இல் சரியான name, type, status, creator மற்றும் creation date இருக்கிறதா பாருங்கள். Governance தேவைப்பட்டால் **My Approvals** மற்றும் change history பயன்படுத்துங்கள்.",
  ]),
  "product-identifiers": guide(
    "Manufacturing → Process & Engineering → Identifier Management; Production → Products → Product detail → Product Identifiers",
    [
      "**Identifier definition-ஐ உருவாக்குங்கள்:** **Process & Engineering → Identifier Management**-ஐத் திறந்து **Create Identifier Range → Create Manually**-ஐத் தேர்ந்தெடுத்து கட்டாய Name-ஐ உள்ளிடுங்கள். Description மற்றும் Active status optional controls.",
      "**Source மற்றும் type-ஐத் தேர்ந்தெடுங்கள்:** **Range**, **Template**, **External**, அல்லது **Manual**-ஐத் தேர்ந்தெடுங்கள். Range source-க்கு identifier Type மற்றும் **Range** அல்லது **File Upload**-ஐத் தேர்வு செய்யுங்கள்; ஒரே operation-இல் அதிகபட்சம் 10,000 identifiers process செய்யலாம்.",
      "**Pool-ஐ வரையறுக்குங்கள்:** IMEI Range-க்கு கட்டாய Start மற்றும் End values-ஐ உள்ளிட்டு calculated identifier count மற்றும் optional Range Preview-ஐ உறுதிப்படுத்தி **Create**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Product Identifiers-ஐத் திறங்கள்:** **Production → Products**-இல் Product detail-ஐத் திறந்து **Product Identifiers** பகுதிக்கு scroll செய்து **Add Identifier**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Mapping-ஐ configure செய்யுங்கள்:** Identifier definition-ஐத் தேர்ந்தெடுத்து கட்டாய Identifier Key மற்றும் Display Name-ஐ உள்ளிட்டு **Generated** அல்லது **External**-ஐத் தேர்ந்தெடுங்கள். Keys uppercase-ஆக store செய்யப்படும்.",
      "**Assignment behavior-ஐ அமைக்குங்கள்:** **On Task Creation**, **On Task Start**, அல்லது **At Route Step**-ஐத் தேர்ந்தெடுங்கள். Generated IMEI-க்கு தேவைக்கேற்ப **Auto-generate** மற்றும் **Must be Unique**-ஐ இயக்குங்கள்.",
      "**Save செய்து verify செய்யுங்கள்:** **Add Identifier**-ஐத் தேர்ந்தெடுத்து Product table-இல் key, display name, type, source, assignment timing, மற்றும் linked range-ஐ உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "create-production-order": guide(
    "Mfg → Production → Production Orders",
    [
      "**Production Orders-ஐத் திறங்கள்:** **Mfg** திறந்து, **Production** விரிவாக்கி, **Production Orders** தேர்ந்தெடுங்கள்.",
      "**Order தொடங்குங்கள்:** **Create Production Order** தேர்ந்தெடுத்து, **Create Manually** தேர்வு செய்யுங்கள் அல்லது AI-assisted option மூலம் draft உருவாக்குங்கள்.",
      "**கட்டாய identity உள்ளிடுங்கள்:** **Name** மற்றும் **Order Number** கட்டாயம். இந்த grouping record-ஐ தனியாக அடையாளம் காட்டும் Order Number பயன்படுத்துங்கள்.",
      "**விருப்ப Client scope அமைக்கவும்:** இந்த Production Order ஒரு Client-ன் Work Orders-க்கு மட்டும் என்றால் **Client** தேர்ந்தெடுங்கள். Client தேர்வு eligible Work Orders-ஐ கட்டுப்படுத்தும்.",
      "**Planning context சேர்க்கவும்:** Description, Start Date, End Date மற்றும் metadata விருப்பமானவை. Scheduling, search அல்லது reporting-க்கு உதவும்போது சேர்க்குங்கள்.",
      "**Grouping record உருவாக்குங்கள்:** Fields-ஐ review செய்து **Create Production Order** தேர்ந்தெடுங்கள். Production Order work-ஐ group செய்கிறது; அது தனியாக executable quantity அல்லது Production Tasks உருவாக்காது.",
      "**Work Orders-ஐ இணைத்து கண்காணிக்கவும்:** Production Order திறந்து, தகுதியான தொடர்புடைய Work Orders-ஐ இணைத்து, combined progress, status மற்றும் planned date range-ஐ கண்காணியுங்கள்.",
    ],
  ),
  "create-work-order": guide("Manufacturing → Production → Work Orders", [
    "**Work Orders-ஐத் திறங்கள்:** **Production**-ஐத் திறந்து **Work Orders**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு ஆர்டரைத் தொடங்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுத்து, தேவையான தனித்துவமான Work Order Name-ஐ உள்ளிடுங்கள்.",
    "**Product-ஐத் தேர்ந்தெடுங்கள்:** Routing configure செய்யப்பட்ட Product-ஐத் தேர்ந்தெடுத்து, தேவையான Product Variant-ஐத் தேர்ந்தெடுங்கள். Project மற்றும் Product Family தானாக பெறப்படும்.",
    "**செயலாக்க விவரங்களை உள்ளிடுங்கள்:** Positive Input Quantity, தேவையான Priority, மற்றும் கடந்த காலத்தில் இல்லாத Due Date-ஐ உள்ளிடுங்கள். Total Computed Quantity = Input Quantity × Product Multiplier என UI கணக்கிடும்.",
    "**உற்பத்தி நேரத்தை ஒதுக்குங்கள்:** தெரிந்திருந்தால் ஒன்று அல்லது அதற்கு மேற்பட்ட Shifts-ஐத் தேர்ந்தெடுங்கள். Record உருவாக்கும்போது Shift optional; ஆனால் Work Order start ஆக குறைந்தது ஒரு Shift தேவை.",
    "**Availability மற்றும் test நடத்தையை மதிப்பாய்வு செய்யுங்கள்:** Component Availability-ஐப் பாருங்கள். Line setup அல்லது workflow testing-க்கு மட்டும் **Test Order**-ஐ இயக்குங்கள்; Test Orders analytics-இல் சேர்க்கப்படாது.",
    "**உருவாக்கி சரிபார்க்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுத்து, success dialog-ல் Work Order ID, Product hierarchy, quantity, due date, priority, மற்றும் **PENDING** status இருப்பதை உறுதிப்படுத்துங்கள்.",
  ]),
  "generate-unit-serials": guide(
    "Manufacturing → Production → Work Orders → Work Order detail",
    [
      "**Work Order-ஐத் திறங்கள்:** Work Orders பட்டியலைத் தேடி வரைவு Work Order-ஐத் தேர்ந்தெடுங்கள்.",
      "**தொடக்கப் பயணத்தைத் திறங்கள்:** **Start Work Order**-ஐத் தேர்ந்தெடுங்கள். Confirmed serials Work Order quantity-க்கு சமமாகும் வரை **Serial Numbers** படி progress-ஐத் தடுக்கும்.",
      "**Generation முறையைத் தேர்ந்தெடுங்கள்:** **Generate Serial Numbers**-ஐத் தேர்ந்தெடுங்கள். Configure செய்யப்பட்டால் Product Template, வேறு available Template, அல்லது CSV/Excel மதிப்புகளுக்கு **Manual Upload** பயன்படுத்துங்கள்.",
      "**Preview-ஐ மதிப்பாய்வு செய்யுங்கள்:** Preview count Work Order quantity-க்கு சமமாக இருப்பதை உறுதிப்படுத்தி **Validate Uniqueness**-ஐத் தேர்ந்தெடுங்கள். ஒவ்வொரு proposed serial-உம் unique ஆக இருக்க வேண்டும்.",
      "**Batch-ஐ உருவாக்குங்கள்:** **Generate _n_ Serial Numbers**-ஐத் தேர்ந்தெடுத்து batch number, quantity, மற்றும் **GENERATED** status-ஐப் பாருங்கள்.",
      "**Batch-ஐ உறுதிப்படுத்துங்கள்:** **Confirm & Complete**-ஐத் தேர்ந்தெடுங்கள். GENERATED batch confirm ஆகும் வரை production-க்கு ready அல்ல.",
      "**Gate-ஐச் சரிபார்க்குங்கள்:** Start journey-ல் **CONFIRMED**, சரியான _n_/_n_ serial count, மற்றும் enabled **Next** இருப்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "capacity-and-routing": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**முதலில் serials-ஐ உறுதிப்படுத்துங்கள்:** Confirmed serials Work Order quantity-க்கு பொருந்திய பிறகே start wizard **Capacity & Lines**-ஐ enable செய்கிறது.",
      "**Capacity-ஐ configure செய்யுங்கள்:** **Configure Capacity Planning**-ஐத் தேர்ந்தெடுத்து Total Quantity, Available Capacity, Available Lines, மற்றும் eligible Starting Lines-ன் projected capacity-ஐப் பாருங்கள்.",
      "**Assignment mode-ஐத் தேர்ந்தெடுங்கள்:** Default system-optimized distribution-ஐப் பயன்படுத்துங்கள் அல்லது manual assignment-க்கு மாறுங்கள். System mode-ல் **Proceed with System Assignment**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Capacity gate-ஐச் சரிபார்க்குங்கள்:** **Capacity planning completed** மற்றும் enabled **Next** இருப்பதை உறுதிப்படுத்துங்கள்.",
      "**Routing-ஐத் தேர்ந்தெடுங்கள்:** **Production Route**-ல் eligible active Routing-ஐத் தேர்ந்தெடுங்கள். Option associated BOM status, route type, மற்றும் item count-ஐக் காட்டும்.",
      "**Route gate-ஐச் சரிபார்க்குங்கள்:** Routing படி checked ஆகவும் overall progress 60% ஆகவும் **Next** enabled ஆகவும் இருப்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "pre-start-validation": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**Validation-ஐத் திறங்கள்:** Serial Numbers, Capacity & Lines, மற்றும் Routing முடிந்ததும் **Next → Run Pre-Start Validation**-ஐத் தேர்ந்தெடுங்கள்.",
      "**அனைத்து gates-ஐப் பாருங்கள்:** Product assignment, BOM, generated/confirmed serials, Component Inventory, Station-Level Inventory, மற்றும் Identifier Availability validate செய்யப்படும்.",
      "**Blocking shortage-ஐத் தீர்க்குங்கள்:** Plant-level Component Inventory போதுமானதாக இருந்தாலும் first-stage Station shortage start-ஐத் தடுக்கும். **Transfer All** அல்லது component transfer action பயன்படுத்துங்கள்.",
      "**கவனமாக transfer செய்யுங்கள்:** Transfer All storage locations, பின்னர் non-routing Stations-க்கு priority கொடுக்கும்; full coverage இல்லாவிட்டால் partial transfer ஏற்படலாம். Remaining quantity-க்கு **Auto-Fill Shortage** பயன்படுத்துங்கள்.",
      "**PASS-ஐ உறுதிப்படுத்துங்கள்:** அனைத்து gates-உம் pass ஆகி **Proceed to Start** enabled ஆகும் வரை validation-ஐ refresh செய்யுங்கள்.",
      "**Production-ஐ release செய்யுங்கள்:** **Proceed to Start** உடனடியாக release செய்து Production Tasks உருவாக்கி Work Order-ஐ **PENDING** இலிருந்து **IN PROGRESS**-க்கு மாற்றும்.",
    ],
  ),
  "production-tasks": guide("Manufacturing → Production → Production Tasks", [
    "**Work Order-ல் tasks-ஐப் பாருங்கள்:** Released Work Order-ஐத் திறந்து **Production Tasks**-ஐத் தேர்ந்தெடுங்கள். Confirmed finished-unit serial ஒவ்வொன்றுக்கும் ஒரு task உருவாகும்.",
    "**Distribution-ஐச் சரிபார்க்குங்கள்:** Task count, serial coverage, Line Type, assigned Line, மற்றும் pending/completed distribution capacity planning-க்கு பொருந்துவதை உறுதிப்படுத்துங்கள்.",
    "**Unit Task-ஐத் திறங்கள்:** Task detail action-ஐத் தேர்ந்தெடுங்கள். Header Task status, assigned serial, Work Order, Product, Line, மற்றும் Line Type-ஐக் காட்டும்.",
    "**Execution readiness-ஐப் பாருங்கள்:** **Stage Progress** தற்போதைய Routing stage மற்றும் Station-ஐக் காட்டும்; **Bound Identifiers** assigned unit identifier-ஐக் காட்டும்.",
    "**Material readiness-ஐப் பாருங்கள்:** **BOM Progress** required மற்றும் used quantities-ஐப் பட்டியலிடும். Execution-ல் consume ஆகும் வரை Components Pending ஆக இருக்கும்.",
    "**Process context-ஐப் பாருங்கள்:** Active Routing, process step, மற்றும் assigned Station-ஐ உறுதிப்படுத்த **Routing and Process Details**-ஐத் திறங்கள்.",
  ]),
  "operator-flow": guide("Manufacturing → Station work area", [
    "**Mapped Station-களை வடிகட்டுங்கள்:** **Operator**-ல் முதலில் Product-ஐத் தேர்ந்தெடுத்து **Mapped**-ஐ அழுத்துங்கள்; default **Running** view-ல் Station தெரியாவிட்டால் Status filter-ஐ பயன்படுத்துங்கள்.",
    "**Production context-ஐத் தேர்ந்தெடுங்கள்:** Station-ஐத் திறந்து active Work Order மற்றும் eligible Production Line-ஐத் தேர்ந்தெடுங்கள்.",
    "**Task-ஐத் திறங்கள்:** Production Task ID அல்லது confirmed finished-unit serial-ஐ scan அல்லது enter செய்து **Start Task**-ஐத் தேர்ந்தெடுங்கள்.",
    "**Required inputs-ஐ validate செய்யுங்கள்:** ஒவ்வொரு serialised BOM Component-க்கும் available serial-ஐ உள்ளிடுங்கள். Identifier validators பொருந்தும்; Battery Pack-க்கு GS1 AI 01 மற்றும் AI 10 தேவை.",
    "**Operation-ஐ முடிக்குங்கள்:** Result-ஐ உறுதிப்படுத்தி **Complete & Next**-ஐத் தேர்ந்தெடுங்கள். Operator, Station, material identities, result, timestamps, மற்றும் Route progress பதிவு செய்யப்படும்.",
  ]),
  "material-consumption": guide(
    "Manufacturing → Station work area → Current operation",
    [
      "**Material-ஐ available ஆக்குங்கள்:** Operation-ஐத் திறப்பதற்கு முன் required stock-ஐ execution Station-க்கு transfer செய்யுங்கள்; Station inventory panel available quantity மற்றும் lots-ஐக் காட்டும்.",
      "**Production Task-ஐத் திறங்கள்:** Station work area-ல் Task ID அல்லது confirmed finished-unit serial-ஐ scan அல்லது enter செய்யுங்கள்.",
      "**Serialised material-ஐப் பதிவு செய்யுங்கள்:** ஒவ்வொரு serialised BOM requirement-க்கும் ஒரு available, unconsumed serial-ஐ உள்ளிடுங்கள்.",
      "**Identifier validators-ஐ பூர்த்தி செய்யுங்கள்:** Configured identifier format-ஐப் பயன்படுத்துங்கள். தேர்ந்தெடுத்த Component-க்கு GS1 AI 01, AI 10, அல்லது பிற validators configure செய்யப்பட்டிருந்தால் தேவையான அனைத்தையும் பூர்த்தி செய்யுங்கள்.",
      "**Consumption-ஐப் பதிவு செய்யுங்கள்:** Required inputs அனைத்தும் validate ஆன பிறகு **Complete & Next**-ஐத் தேர்ந்தெடுங்கள். Completed Task material identities, inventory use, மற்றும் genealogy-ஐப் பதிவு செய்யும்.",
    ],
  ),
  "statuses-and-route-logs": guide(
    "Manufacturing → Work Orders மற்றும் Route Execution Logs",
    [
      "**Work Order-ஐச் சரிபார்க்குங்கள்:** Overall status, progress, Production Metrics, மற்றும் task distribution-ஐப் பார்க்க Work Order-ஐத் திறங்கள். எல்லா Production Tasks-மும் முடிந்த பிறகே அது **COMPLETED** ஆகும்.",
      "**Route Execution Logs-ஐத் திறங்கள்:** Operation-level execution evidence-ஐப் பார்க்க **Route Execution Logs**-ஐப் பயன்படுத்துங்கள்.",
      "**Counters-ஐப் படியுங்கள்:** தனிப்பட்ட rows-ஐ ஆய்வு செய்வதற்கு முன் **Total Logs**, **Passed**, **Failed**, மற்றும் **In Progress**-ஐ ஒப்பிடுங்கள்.",
      "**History-ஐ filter செய்யுங்கள்:** Status, date range, Work Order, Product, Routing, அல்லது Station மூலம் filter செய்யுங்கள். தேவைப்பட்டால் log ID, notes, அல்லது Product மூலம் search செய்யுங்கள்.",
      "**ஒவ்வொரு result-ஐயும் பாருங்கள்:** Log timestamp, Work Order, Product, Routing, Line, Station, operator, quality result, மற்றும் execution status-ஐப் பதிவு செய்கிறது. தொடர்புடைய production context-க்கு **View Details**-ஐப் பயன்படுத்துங்கள்.",
    ],
  ),
  "quality-controls": guide("Manufacturing → Quality → Control Points", [
    "**Control Points-ஐத் திறங்கள்:** **Quality → Control Points**-ஐத் திறந்து **Create Control Point**-ஐத் தேர்ந்தெடுங்கள்.",
    "**Required identity-ஐ உள்ளிடுங்கள்:** Unique **Code** மற்றும் **Name**-ஐ உள்ளிடுங்கள். தேவையான **Control Type**, **Frequency**, மற்றும் **On Failure** action-ஐத் தேர்ந்தெடுங்கள்.",
    "**Conditional scope-ஐ அமைக்குங்கள்:** முதலில் **Production Line**-ஐத் தேர்ந்தெடுங்கள்; Line தேர்ந்தெடுக்கப்படும் வரை **Station** கிடைக்காது.",
    "**Failure behavior-ஐ வரையறுங்கள்:** **Stop Line**, **Quarantine**, **Hold Lot**, **Escalate**, அல்லது **Alert Only**-ஐத் தேர்ந்தெடுங்கள். Failed output தானாக பாதுகாக்கப்பட வேண்டுமெனில் **Auto-hold failed units**-ஐ இயக்குங்கள்.",
    "**Inspection evidence-ஐச் சேருங்கள்:** Checklist questions மற்றும் response type-ஐச் சேர்த்து control-ஐ உருவாக்குங்கள். Configuration tab-ல் Active status, scope, failure action, மற்றும் saved checklist-ஐ உறுதிப்படுத்துங்கள்.",
  ]),
  "inspection-to-capa": guide("Manufacturing → Quality", [
    "**முதலில் inspections-ஐ configure செய்யுங்கள்:** பொருந்தும் inspection configuration-ஐ உருவாக்கி activate செய்யுங்கள். Plant configuration fallback ஆகும்; அதிக specificity கொண்ட scopes அதை override செய்யும்.",
    "**ஒரே production source-ஐத் தேர்ந்தெடுங்கள்:** **Work Order** அல்லது available, non-expired **Lot**—இரண்டில் ஒன்றிலிருந்து மட்டும் inspection-ஐ உருவாக்குங்கள். Required total quantity மற்றும் sampling quantity-ஐ உள்ளிடுங்கள்.",
    "**ஒவ்வொரு sample-ஐயும் பதிவு செய்யுங்கள்:** Serial அல்லது lot sample-ஐ உள்ளிட்டு checks-ஐ முடிக்குங்கள். Failed sample-ஐ save செய்ய **Defect code** மற்றும் **Severity** தேவை.",
    "**Hold scope-ஐத் தேர்ந்தெடுங்கள்:** Inspection-ஐ reject செய்யும்போது failed serials மட்டும் அல்லது முழு lot-ஐ hold செய்யுங்கள். Inspection-இன் local defects மற்றும் plant **Defects** list records தனித்தனி.",
    "**Deployment availability-ஐ உறுதிசெய்யவும்:** NCR மற்றும் CAPA actions deployment மற்றும் permission-ஐப் பொறுத்து மாறலாம். Working create action இல்லையெனில் workflow available என்று கூறாமல் implementation owner-உடன் enablement-ஐ உறுதிசெய்யவும்.",
  ]),
  "repair-and-rework": guide(
    "Mfg → Repair & Rework → Debug Queue, Repair Queue, Repair Out, மற்றும் Rework Board",
    [
      "**Failed RSN-ஐ Repair-க்கு அனுப்புங்கள்:** **Debug Queue**-ல் RSN-ஐ திறந்து failure evidence, route context, மற்றும் previous attempts-ஐ review செய்யுங்கள். Forge **Send to Repair** காட்டினால் மட்டும் அதைத் தேர்ந்தெடுத்து Repair Level, available 4M cause details, diagnosis notes ஆகியவற்றை பதிவு செய்து submit செய்யுங்கள்; status **Queued for Repair** ஆனதா உறுதிசெய்யுங்கள்.",
      "**Repair-ஐ தொடங்குங்கள்:** **Repair Queue**-ல் அதே RSN-ஐத் திறந்து failure evidence, Repair Station, attempt history, மற்றும் status-ஐ சரிபார்க்கவும். **Start Repair** தேர்ந்தெடுத்து prompted fields-ஐ முடித்து job **In Repair** ஆனதா பார்க்கவும்.",
      "**Repair-ஐ complete செய்யுங்கள்:** Work முடிந்த பிறகே **Complete Repair** தேர்ந்தெடுக்கவும். **Repair Successful** அல்லது **No Fault Found**, confirmed 4M category, repair minutes, cost, notes, மற்றும் evidence-ஐ பதிவு செய்யுங்கள். Submit செய்து **Pending QC** ஆனதா பார்க்கவும். Completion-ஏ QC handoff; தனி Send to QC action தேவையில்லை.",
      "**QC-ல் approve செய்யுங்கள்:** **Repair Out**-ல் **Pending QC** RSN-ஐத் திறந்து timeline, result, costs, notes, மற்றும் evidence-ஐ review செய்யுங்கள். Forge காட்டினால் **QC Pass** தேர்ந்தெடுத்து required notes சேர்த்து refresh செய்த பின் **QC Passed** status மற்றும் timeline-ல் உள்ளதா உறுதிசெய்யுங்கள்.",
      "**QC பிறகு release செய்யுங்கள்:** QC-passed record-க்கு Forge **Release** காட்டினால் மட்டும் பயன்படுத்துங்கள். Destination அல்லது next step-ஐ உறுதிசெய்து ஒருமுறை submit செய்து resulting status-ஐ verify செய்யுங்கள்.",
      "**QC-ல் reject செய்யுங்கள்:** Verification fail ஆனால் available **QC Reject** action-ஐப் பயன்படுத்தி required reason மற்றும் notes-ஐ பதிவு செய்யுங்கள். Refresh செய்து resulting status மற்றும் timeline-ஐப் பார்க்கவும்; RSN Repair அல்லது Rework-க்கு திரும்பியது என்று assume செய்யாதீர்கள்.",
      "**Repair-க்கு திரும்பிய RSN:** Post-rejection status அல்லது displayed action Repair-க்கு அனுப்பினால் **Repair Queue**-ல் new attempt-ஐ தொடங்கி issue-ஐ சரிசெய்து new evidence பதிவு செய்து complete செய்து மீண்டும் **Pending QC** வந்ததா பார்க்கவும்.",
      "**Rework-க்கு அனுப்பி complete செய்யுங்கள்:** Approved RSN-க்கு Forge காட்டும் Rework disposition மட்டும் பயன்படுத்துங்கள். Controlled symptom, reason, மற்றும் routing information-ஐ பதிவு செய்து **Rework Board**-ல் card-ஐ track செய்யுங்கள். **Record work** மூலம் attempt மற்றும் evidence-ஐ பதிவு செய்து displayed result column-க்கு சென்றதா verify செய்யுங்கள்.",
      "**Approved disposition-க்கு மட்டும் Scrap:** **Report Scrap** அல்லது Scrap action available மற்றும் approved ஆக இருந்தால் மட்டும் பயன்படுத்தி controlled reason, evidence, மற்றும் approval trail-ஐப் பதிவு செய்யுங்கள்; Scrap Register status-ஐ verify செய்யுங்கள்.",
      "**Forge error வந்தால் நிறுத்துங்கள்:** State-changing action-ஐ repeat செய்யாதீர்கள்; success என்று assume செய்யாதீர்கள். RSN மற்றும் visible status-ஐ வைத்துக் கொண்டு error-ஐ report செய்யுங்கள்.",
    ],
  ),
  "hold-scrap-teardown": guide("Manufacturing → Quality or Scrap & Teardown", [
    "**சரியான hold-ஐ உருவாக்குங்கள்:** **Quality → Hold Management → Create Hold**-ஐத் திறங்கள். முதலில் Hold Level-ஐத் தேர்ந்தெடுங்கள்; இது required target மற்றும் operational impact-ஐ மாற்றும்.",
    "**Required hold fields-ஐ முடிக்குங்கள்:** Target மற்றும் **Reason**-ஐத் தேர்ந்தெடுங்கள். Notes optional; Work Order hold-க்கு optional expected release date சேர்க்கலாம்.",
    "**Approval விதிகளைப் பின்பற்றுங்கள்:** Inventory lot, vendor, மற்றும் date-code holds **Submit for Approval**-ஐப் பயன்படுத்தும்; Quality approve செய்யும் வரை அவை inactive. Work Order hold அந்த order-இன் அனைத்து production-ஐயும் pause செய்கிறது.",
    "**Scrap-ஐ upstream-இல் track செய்யுங்கள்:** முதலில் **Scrap Reasons**-ஐ configure செய்யுங்கள். **Scrap Register** Pending Approval, Approved, Executed, மற்றும் Rejected dispatches-ஐ track செய்கிறது; இதில் create action இல்லை.",
    "**Teardown-ஐ சரியாகத் தொடங்குங்கள்:** Executed Scrap dispatch **Send to teardown** உடன் அனுப்பப்பட்ட பிறகே Teardown order தோன்றும். Donor serial மற்றும் scrap dispatch recovered Components உடன் linked ஆக இருக்கும்.",
  ]),
  "scrap-register": guide("Mfg → Scrap & Teardown → Scrap Register", [
    "**Register-ஐத் திறக்கவும்:** **Scrap & Teardown** திறந்து **Scrap Register** தேர்ந்தெடுக்கவும். இது review queue; create action இல்லை.",
    "**Status view தேர்ந்தெடுக்கவும்:** சரியான dispatch state-ஐப் பார்க்க **All**, **Pending Approval**, **Approved**, **Executed**, அல்லது **Rejected** பயன்படுத்தவும்.",
    "**Scope அமைக்கவும்:** Source, Category, Reason, Line, Station, Work Order, Product, அல்லது Date Range மூலம் filter செய்து, source data மாறியிருந்தால் **Refresh** பயன்படுத்தவும்.",
    "**Dispatch evidence review செய்யவும்:** Action எடுக்கும் முன் dispatch number, source, unit அல்லது quantity, Product, Work Order, Station, reason, proposer, status, மற்றும் age சரியா என உறுதிசெய்யவும்.",
    "**Approval flow-ஐ பாதுகாக்கவும்:** Record eligible state-ல் இருந்து required evidence review செய்யப்பட்டால் மட்டுமே approve, execute, reject, அல்லது teardown-க்கு அனுப்பவும். ஒவ்வொரு action-க்கும் முன் status மற்றும் evidence current ஆக உள்ளதா உறுதிப்படுத்தவும்.",
  ]),
  "scrap-reasons": guide("Mfg → Scrap & Teardown → Scrap Reasons", [
    "**Scrap Reasons திறக்கவும்:** **Scrap & Teardown → Scrap Reasons** செல்லவும். Obsolete categories அல்லது reasons பார்க்க வேண்டியபோது மட்டும் **Show inactive** பயன்படுத்தவும்.",
    "**Taxonomy தொடங்கும் முறையைத் தேர்ந்தெடுக்கவும்:** Standard categories உருவாக்க **Seed industry defaults** தேர்ந்தெடுக்கவும்; manual category-க்கு **Add category** தேர்ந்தெடுக்கவும்.",
    "**Manual category நிரப்பவும்:** **Code** மற்றும் **Name** required. Description optional; Sort Order category எந்த இடத்தில் வர வேண்டும் என்பதை நிர்ணயிக்கிறது.",
    "**Category கீழ் reason codes பராமரிக்கவும்:** Duplicate அல்லாத தெளிவான reasons சேர்த்து, தற்போது select செய்ய வேண்டிய entries மட்டும் active ஆக வைத்திருக்கவும்.",
    "**Current taxonomy-ஐச் சரிபார்க்கவும்:** Empty state தெரிந்தால் defaults seed செய்வதா அல்லது manual category சேர்ப்பதா என்பதைத் தேர்ந்தெடுக்கவும். Existing data உள்ளதா filters மற்றும் refresh மூலம் உறுதிப்படுத்திய பிறகே மாற்றம் செய்யவும்.",
  ]),
  packaging: guide("Manufacturing → Packaging & Shipping → Packaging", [
    "**Packaging-ஐத் திறங்கள்:** **Packaging & Shipping**-ஐத் திறந்து **Packaging**-ஐத் தேர்ந்தெடுங்கள்.",
    "**Product hierarchy-ஐ கட்டமைக்குங்கள்:** **Packing Configuration**-ஐத் திறந்து Product-ஐத் தேர்ந்தெடுத்து product-specific container type-ஐ வரையறுக்குங்கள். **Product**, **Name**, மற்றும் **Code** கட்டாயம்; Code 2–10 alphanumeric எழுத்துகளை ஏற்கும்.",
    "**Leaf அல்லது parent நடத்தையைத் தேர்ந்தெடுங்கள்:** Finished-unit serial-களை நேரடியாக bind செய்யும் leaf-க்கு **Child Container Type**-ஐ காலியாக விடுங்கள்; இல்லையெனில் Device → Box → Carton → Pallet hierarchy-க்கான child-ஐத் தேர்ந்தெடுங்கள்.",
    "**Container-ஐ உருவாக்குங்கள்:** Packaging Dashboard-க்கு திரும்பி **Create Container**-ஐத் தேர்ந்தெடுங்கள். Product-ஐத் தேர்ந்தெடுத்து, கட்டாயமான **Container Type** மற்றும் **Work Order ID**-ஐ தேர்ந்தெடுங்கள்; இரண்டும் இல்லாமல் Create enable ஆகாது.",
    "**Packaging-ஐ மதிப்பாய்வு செய்து முடிக்குங்கள்:** உருவாக்கப்பட்ட UID-ஐத் திறந்து device count, weight and dimensions, linked Work Order, label state, மற்றும் History-ஐச் சரிபாருங்கள். UID template optional; இல்லையெனில் Fynd ERP default format-ஐப் பயன்படுத்தும்.",
  ]),
  shipments: guide("Mfg → Packaging & Shipping → Shipments", [
    "**Shipments திறக்கவும்:** **Packaging & Shipping** திறந்து **Shipments** தேர்ந்தெடுக்கவும்.",
    "**Existing shipment தேடவும்:** ASN அல்லது destination மூலம் search செய்யவும்; Work Order, Product, Status, மற்றும் Date Range filters பயன்படுத்தவும். List-ல் ASN, Work Order, destination, contents, carrier, status, dates, மற்றும் actions வரும்.",
    "**Valid source data இருந்தால் மட்டும் shipment தொடங்கவும்:** **New Shipment** தேர்ந்தெடுக்கவும். Work Order optional; **Product** மற்றும் **Address line 1** required. Destination, carrier, optional invoice அல்லது vendor-lot details, மற்றும் notes நிரப்பவும்.",
    "**Created record verify செய்யவும்:** Shipment verification செல்லும் முன் புதிய record எதிர்பார்த்த destination, contents, carrier, status, மற்றும் dates-உடன் list-ல் வருகிறதா பார்க்கவும்.",
    "**Creation-to-verification handoff-ஐச் சரிபார்க்கவும்:** Shipment save ஆனதும் அது list-ல் தோன்றுகிறதா, தேர்ந்தெடுக்க முடிகிறதா, மற்றும் verification page-ல் அதன் source மற்றும் container context கிடைக்கிறதா உறுதிப்படுத்தவும்.",
  ]),
  "containers-and-labels": guide("Manufacturing → Packaging & Shipping", [
    "**Container hierarchy-ஐ உருவாக்குங்கள்:** **Packing Configuration**-இல் முதலில் leaf-ஐ உருவாக்கி, பின்னர் ஒவ்வொரு parent-க்கும் அனுமதிக்கப்பட்ட **Child Container Type**-ஐத் தேர்ந்தெடுங்கள். Child-ஐத் தேர்ந்தெடுத்ததும் **Max child count** கட்டாயமாகும்.",
    "**Identity மற்றும் limits-ஐ configure செய்யுங்கள்:** Container-க்கு தனித்த **UID Template**, sequence reset scope, dimensions, weight range, மற்றும் tolerance-ஐத் தேர்ந்தெடுங்கள். Unit-serial pattern-ஐ மீண்டும் பயன்படுத்தினால் UID collision ஏற்படலாம்.",
    "**Parent container-ஐ உருவாக்குங்கள்:** Packaging Dashboard-இல் Product, parent Container Type, மற்றும் completed Work Order-ஐத் தேர்ந்தெடுங்கள். Generated UID தேர்ந்தெடுத்த template-ஐப் பின்பற்றும்.",
    "**Eligible identity-ஐ pack செய்யுங்கள்:** **Pack by UID**-இல் finished serial, device UID, child UID, identifier, அல்லது task ID-ஐ scan செய்யுங்கள். Valid unit configured leaf container-ஐ தானாக உருவாக்கி parent-இல் pack செய்யும்; capacity enforce செய்யப்படும்.",
    "**Label-ஐ print செய்து verify செய்யுங்கள்:** Carton label-ஐ print செய்து carton UID, model, quantity, unit serial, மற்றும் QR codes-ஐச் சரிபாருங்கள். Source records-இல் இல்லாத values காலியாக இருக்கும்; traceability-க்கு History மற்றும் Reprint-ஐப் பயன்படுத்துங்கள்.",
  ]),
  "shipment-verification": guide(
    "Manufacturing → Packaging & Shipping → Shipment Verification",
    [
      "**முதலில் Shipment-ஐத் தேர்ந்தெடுங்கள்:** **Shipment Verification**-ஐத் திறங்கள். **Shipment** கட்டாயம்; Shipment தேர்ந்தெடுக்கப்படும் வரை **Container Type**, verification counts, container rows, மற்றும் Export கிடைக்காது.",
      "**Governing rule-ஐப் பின்பற்றுங்கள்:** Active **Shipment Rule** selected container configuration-ஐ கொண்டிருக்க வேண்டும்; container count மற்றும் maximum-weight limits-ஐ அனுமதிக்க வேண்டும். Priority எந்த rule apply ஆகும் என்பதைத் தீர்மானிக்கும்.",
      "**Shipping Gate-ஐச் சரிபாருங்கள்:** Verification முன் applicable approved Purchase Order quantity-ல் positive remaining balance உள்ளதா உறுதிசெய்யவும்.",
      "**தேவைப்பட்டால் ASN export-ஐ configure செய்யுங்கள்:** ASN Excel columns client- அல்லது product-scoped template-இலிருந்து வரும். Export செய்வதற்கு முன் selected scope-க்கு required template configure செய்யப்பட்டுள்ளதா உறுதிசெய்யவும்.",
      "**Prerequisite path-ஐ verify செய்யுங்கள்:** Approved source records கொண்டு shipment creation, rule matching, positive gate balance, container verification, மற்றும் ASN output ஆகிய முழுப் பாதையையும் சரிபார்க்கவும்.",
    ],
  ),
  "traceability-genealogy-recall": guide(
    "Manufacturing → Traceability → Master Traceability",
    [
      "**கட்டாயமான dossier scope-ஐ அமைக்குங்கள்:** **Master Traceability**-இல் filters ஒன்றாகச் செயல்படும்; parent selection செய்த பின் dependent Product filters திறக்கும். Specific identifier list மற்ற filters-ஐ override செய்யும்; குறைந்தது ஒரு scope தேர்ந்தெடுக்கப்படும் வரை **Generate Dossier** disabled ஆக இருக்கும்.",
      "**Report output-ஐத் தேர்ந்தெடுங்கள்:** தேவையான unit, route, quality, genealogy, identifier, tool, checklist, packaging, அல்லது shipment sheets மட்டும் தேர்ந்தெடுங்கள். Generation asynchronous; completed files **Recent exports**-இல் இருக்கும். Download செய்வதற்கு முன் status, scope, மற்றும் unit count-ஐ உறுதிப்படுத்துங்கள்.",
      "**Stage Timeline requirements அனைத்தையும் பூர்த்தி செய்யுங்கள்:** Date range, குறைந்தது ஒரு Work Order, மற்றும் 1–50 Operations தேவை. Generate செய்வதற்கு முன் இந்த required fields அனைத்தும் நிரப்பப்பட்டுள்ளனவா உறுதிப்படுத்துங்கள்.",
      "**சரியான திசையில் genealogy-ஐப் பின்தொடருங்கள்:** Full tree pallet, carton, box, device, product, Component, அல்லது batch identifiers-ஐ ஏற்கும். **Downstream** finished identity-யிலிருந்து Components/lots-க்கு செல்கிறது; **Upstream** lot-இலிருந்து finished units-க்கு செல்கிறது.",
      "**Affected population-ஐக் கண்டறியுங்கள்:** **Find Affected Units**-இல் Batch/Lot Number அல்லது Component Serial மூலம் தேடுங்கள். கிடைக்கும் finished-unit results சரியான Product மற்றும் Work Order context-க்கு பொருந்துகின்றனவா உறுதிப்படுத்துங்கள்.",
      "**Recall assignment-ஐ நம்பும் முன் verify செய்யவும்:** Recall உருவாக்க Title மற்றும் Severity கட்டாயம். Selected batch அல்லது tasks affected units-ஐ populate செய்கிறதா, saved notice அவற்றை record செய்கிறதா உறுதிசெய்த பிறகே recall response-ஐத் தொடங்குங்கள்.",
    ],
  ),
  dashboards: guide(
    "Manufacturing → Dashboard, Work Orders, Production Tasks, and Route Logs",
    [
      "**Current Plant-இலிருந்து தொடங்குங்கள்:** Dashboard selected Plant-க்கான setup readiness, active Work Orders, production Stations, active Products, Clients, Projects, production completion, மற்றும் quality targets-ஐக் காட்டுகிறது.",
      "**Schedule risk-ஐக் கண்டறியுங்கள்:** **Work Orders**-இல் Status, Priority, மற்றும் Due Date-ஐ ஒன்றாகப் பாருங்கள். Past-due active records **Delayed** எனக் குறிக்கப்படும்; original மற்றும் repair Work Orders-ஐ அவற்றின் status, type, மற்றும் linked unit context மூலம் வேறுபடுத்துங்கள்.",
      "**Work Order metrics-ஐப் புரிந்துகொள்ளுங்கள்:** Task completion, units/hour, takt/cycle time, yield, மற்றும் total execution time-ஐ ஒன்றாகப் பாருங்கள். Yield என்பது passed quality steps ÷ completed steps; அதை configured quality target-உடன் ஒப்பிடுங்கள்.",
      "**Live progress board-ஐப் பயன்படுத்துங்கள்:** **Track Progress** default ஆக 30 seconds-க்கு ஒருமுறை auto-refresh ஆகும்; Station filter, completed highlight, samples-only, sorting, மற்றும் fullscreen controls உள்ளன.",
      "**Task context-ஐ உறுதிப்படுத்துங்கள்:** Production Tasks Serial, task ID, grouping, Work Order, Line, Product/Routing, மற்றும் status-ஐக் காட்டுகிறது. ஒரே serial-க்கு later repair task உட்பட ஒன்றுக்கு மேற்பட்ட task records இருக்கலாம்; செயல்படுவதற்கு முன் Work Order மற்றும் Line-ஐ உறுதிப்படுத்துங்கள்.",
      "**Execution evidence-ஐச் சரிபார்க்குங்கள்:** Route Log totals current filters-ஐப் பிரதிபலிக்கும். ஒவ்வொரு log-மும் Work Order, Product, Routing, Line, Station, operator, timestamp, quality status, மற்றும் execution status-ஐச் சேமிக்கும்; இந்த values operation result-க்கு பொருந்துகின்றனவா உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "shift-operations": guide("Manufacturing → Shifts & Labor", [
    "**Net working time-ஐ உறுதிப்படுத்துங்கள்:** Unpaid breaks Shift duration-இலிருந்து கழிக்கப்படும். Shift times அல்லது break durations update செய்த பின் calculated net working time-ஐ மதிப்பாய்வு செய்யுங்கள்.",
    "**Schedule coverage-ஐச் சரிபார்க்குங்கள்:** புதிய Shift Schedules activate செய்யப்படும் வரை Draft. Status மட்டும் coverage-ஐ நிரூபிக்காது; generated shifts per week மற்றும் calendar coverage-ஐ உறுதிசெய்யவும்.",
    "**Required Handover fields-ஐப் பூர்த்தி செய்யுங்கள்:** **Shift** மற்றும் **Handover Date** கட்டாயம். Line, outgoing/incoming operators, production/quality/equipment summaries, notes, pending tasks, மற்றும் checklist items optional.",
    "**Connected operating context-ஐப் பதிவு செய்யுங்கள்:** Handover-ஐ தொடர்புடைய Line-உடன் இணைத்து completed production, Route Logs, equipment state, safety, மற்றும் pending tasks-ஐப் பதிவு செய்யுங்கள்.",
    "**Complete செய்வதற்கு முன் review செய்யுங்கள்:** புதிய Handover **Draft**. Outgoing மற்றும் Incoming Supervisors-ஐ explicit-ஆக உறுதிசெய்து, அடுத்த Shift review செய்த பின் மட்டுமே **Complete** பயன்படுத்துங்கள்.",
    "**Break Compliance-ஐ கவனமாகப் புரிந்துகொள்ளுங்கள்:** Zero Break Logs இருக்கும்போது 100% compliance மற்றும் 0 violations காட்டப்படலாம்; ஆனால் அந்த percentage compliant breaks நடந்ததற்கான evidence அல்ல. Underlying logs-ஐ உறுதிப்படுத்துங்கள்; export செய்யக்கூடிய records இருந்தால் மட்டுமே **Export CSV** கிடைக்கும்.",
  ]),
  "tools-and-maintenance": guide(
    "Manufacturing → Process & Engineering → Tools and Equipments",
    [
      "**Tool register-ஐத் திறங்கள்:** **Process & Engineering → Tools and Equipments**-ஐ expand செய்து, child **Tools and Equipments** page-ஐத் திறங்கள்.",
      "**தேவையான identity-ஐ முடிக்குங்கள்:** **Tool Name, Tool Code, Tool Category, Manufacturer, Model, Station, மற்றும் Status** required. Tool-ஐ அது பயன்படுத்தப்படும் Station-க்கு assign செய்து, code தனித்துவமாக உள்ளதா உறுதிப்படுத்துங்கள்.",
      "**Governed Tool-க்கு மட்டும் calibration அமைக்குங்கள்:** **Requires Calibration** enable செய்தால் optional interval மற்றும் provider fields தோன்றும். Required **Calibration Date, Next Calibration Date, மற்றும் Result** உள்ள record உருவாகும் வரை governed Tool **Unknown** ஆக இருக்கும்.",
      "**Readiness evidence-ஐப் பதிவு செய்யுங்கள்:** Calibration Date, Result, certificate அல்லது reference, மற்றும் next due date-ஐப் பதிவு செய்யுங்கள். Override பயன்படுத்தப்பட்டால் அது calibration override history-இல் இருக்கும்.",
      "**Maintenance Alerts-ஐ மதிப்பிடுங்கள்:** **Trigger Maintenance Check** configured maintenance rules-ஐ evaluate செய்கிறது. 0 alerts என்பது rule match ஆகவில்லை அல்லது required rules/source data இல்லை என்பதைக் குறிக்கலாம்; result-ஐ நம்பும் முன் இரண்டையும் verify செய்யுங்கள். Alert rows இருந்தால் மட்டுமே **Export** கிடைக்கும்.",
      "**Maintenance Work Order-ஐ control செய்யுங்கள்:** **Tool** மற்றும் **Title** மட்டும் required; Priority **Medium** ஆகவும் Maintenance Type **Corrective** ஆகவும் default ஆகும். Connected preventive order **Draft → Submitted → Approved** என நகர்ந்து, பின்னர் **Start** கிடைக்கும்.",
      "**Production timing-ஐ பாதுகாக்குங்கள்:** Tool status, calibration, மற்றும் maintenance readiness current ஆக இருக்கட்டும். Future approved maintenance order-ஐ planned window-க்கு முன் start செய்யாதீர்கள்.",
    ],
  ),
  "reports-and-audit": guide(
    "Traceability → Master Traceability; Production → Work Orders",
    [
      "**Dossier scope-ஐ அமைக்குங்கள்:** **Traceability → Master Traceability → Dossier**-ஐத் திறங்கள். Scope filters optional மற்றும் combine ஆகும்; **Specific identifiers**-இல் paste அல்லது upload செய்யும் serial-number list மற்ற scope filters-ஐ override செய்கிறது.",
      "**Report sheets-ஐத் தேர்ந்தெடுங்கள்:** தேவையான Unit Summary, Route Detail, tests, sampling, NCR/defects, repair, genealogy, identifiers, Tool Usage, checklist, packaging, மற்றும் shipment sheets-ஐத் தேர்ந்தெடுங்கள். Selected scope மற்றும் expected unit count report-க்கு பொருந்துகின்றனவா உறுதிப்படுத்துங்கள்.",
      "**Dossier-ஐ generate செய்து verify செய்யுங்கள்:** **Generate Dossier**-ஐத் தேர்ந்தெடுத்து, download செய்வதற்கு முன் **Recent exports**-இல் **COMPLETED**, unit count, மற்றும் XLSX filename இருப்பதை உறுதிப்படுத்துங்கள்.",
      "**Work Order export உருவாக்குங்கள்:** **Production → Work Orders**-இல் **Export Work Orders**-ஐத் தேர்ந்தெடுங்கள். **Create Data Export** dialog-ல் Search, Status, மற்றும் Priority values-ஐ மதிப்பாய்வு செய்து, list-page filters carry over ஆகவில்லை என்றால் அவற்றை மீண்டும் apply செய்யுங்கள்.",
      "**Export evidence-ஐ verify செய்யுங்கள்:** Export Details type, format, status, file size, மற்றும் applied filters-ஐ வைத்திருக்கும். Job **COMPLETED** ஆனாலும் Processed மற்றும் Progress 0 ஆக இருக்கலாம்; பயன்படுத்தும் முன் processed count மற்றும் file contents-ஐ உறுதிப்படுத்துங்கள்.",
      "**கிடைக்கும் audit history-ஐப் பயன்படுத்துங்கள்:** **View all changes** மற்றும் **Recent Changes** கிடைக்கும் actor, action, affected record, மற்றும் timestamp evidence-ஐக் காட்டும். History view-ஐத் திறந்து தேவையான date range மற்றும் record changes கிடைக்கின்றனவா உறுதிசெய்யவும்.",
    ],
  ),
  "first-production-run": guide("Manufacturing → Production → Work Orders", [
    "**ஒரு சோதனை Work Order-ஐ உருவாக்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுத்து ஒரு சிறிய ஆனால் யதார்த்தமான அளவைப் பயன்படுத்துங்கள்.",
    "**தயார் செய்து வெளியிடுங்கள்:** சீரியல்கள், திறன், Routing, பொருள், மற்றும் அடையாளங்காட்டிகளை உறுதிப்படுத்தி, பின்னர் **Release Work Order**-ஐத் தேர்ந்தெடுங்கள்.",
    "**சாதாரண பாதையை இயக்குங்கள்:** குறைந்தது ஒரு அலகை ஒவ்வொரு தேவையான operation வழியாகவும் முடிக்குங்கள்.",
    "**ஒரு விதிவிலக்கைச் சோதியுங்கள்:** ஒரு கட்டுப்படுத்தப்பட்ட operation-ஐ தோல்வியடையச் செய்து அதன் Repair அல்லது Rework பாதையை முடிக்குங்கள்.",
    "**முடித்து கண்காணியுங்கள்:** பொருந்தும் தரம், packaging, மற்றும் shipment படிகளை முடித்து, பின்னர் **Master Traceability**-இல் அலகைத் தேடுங்கள்.",
  ]),
  troubleshooting: guide("The affected Fynd ERP module", [
    "**தோல்வியுற்ற பதிவைத் திறங்கள்:** பிழையைக் காட்டும் Product, Routing, Work Order, Production Task, அல்லது shipment-க்குத் திரும்புங்கள்.",
    "**சரிபார்ப்புச் செய்தியைப் படியுங்கள்:** தோல்வியுற்ற சரிபார்ப்பை விரிவுபடுத்தி, சரியான இல்லாத புலம், உறவு, நிலை, அல்லது அளவைக் குறித்துக்கொள்ளுங்கள்.",
    "**முன்நிபந்தனைகளைச் சரிபார்க்குங்கள்:** பொருந்தும்படி செயலில் உள்ள BOM, Stations, Repair Stations, Shift, Line ஒதுக்கீடு, திறன், சீரியல்கள், இருப்பு, மற்றும் அடையாளங்காட்டிகளைச் சரிபார்க்குங்கள்.",
    "**மூலப் பதிவைச் சரிசெய்யுங்கள்:** இணைக்கப்பட்ட கட்டமைப்பைத் திறந்து, தேவையான மாற்றத்தைச் செய்து, **Save**-ஐத் தேர்ந்தெடுங்கள்.",
    "**செயலை மீண்டும் முயற்சியுங்கள்:** அசல் பதிவுக்குத் திரும்பி **Validate**, **Create**, **Release**, அல்லது **Complete**-ஐ மீண்டும் தேர்ந்தெடுங்கள்.",
  ]),
};

export function getForgeTaskGuide(slug: string): ForgeTaskGuide | undefined {
  return TASK_GUIDES_TA[slug];
}
