import type { ForgeTaskGuide } from "./forge-task-guides";

const guide = (navigationPath: string, steps: string[]): ForgeTaskGuide => ({
  navigationPath,
  steps,
});

export const TASK_GUIDES_TE: Record<string, ForgeTaskGuide> = {
  "complete-setup-journey": guide("Fynd ERP Dashboard", [
    "**Setup journey తెరవండి:** Setup, Process & Engineering, Production, మరియు Traceability విభాగాలను వరుసగా పూర్తి చేయడానికి ఎడమ నావిగేషన్‌ను ఉపయోగించండి.",
    "**Factory రికార్డులను సృష్టించండి:** Sites, Lines, operation Stations, Repair Stations, మరియు Shift Definitions సృష్టించండి.",
    "**Product రికార్డులను సృష్టించండి:** Project, Product Family, Components, Product, Variants, మరియు BOM Version సృష్టించండి.",
    "**Execution కోసం సిద్ధం చేయండి:** BOM ను activate చేసి, Routing ను సృష్టించి validate చేసి, Product ను eligible Lines కు assign చేయండి.",
    "**ఒక trial order ప్రారంభించండి:** ఒక చిన్న Work Order సృష్టించి, unit serials నిర్ధారించి, capacity మరియు Routing ఎంచుకుని, validation రన్ చేసి, Release ఎంచుకోండి.",
  ]),
  sites: guide("Manufacturing → Setup → Sites", [
    "**Sites తెరవండి:** Fynd ERP ఎడమ నావిగేషన్‌లో **Setup** తెరిచి **Sites** ఎంచుకోండి.",
    "**కొత్త రికార్డు ప్రారంభించండి:** కుడి పైభాగంలో ఉన్న **Create Site** ఎంచుకోండి.",
    "**అవసరమైన identity నమోదు చేయండి:** **Name** మరియు ప్రత్యేకమైన **Code** పూర్తి చేయండి. Code లో uppercase అక్షరాలు, సంఖ్యలు, hyphen మాత్రమే ఉపయోగించండి.",
    "**అవసరమైతే location వివరాలు జోడించండి:** **Country** ఎంచుకున్న తర్వాత **State**, తరువాత **City** enable అవుతాయి.",
    "**Optional metadata జాగ్రత్తగా జోడించండి:** Metadata 32 KB పరిమితిలో ఉండాలి; search లేదా grouping కు ఉపయోగపడితే మాత్రమే tags జోడించండి.",
    "**Save చేసి verify చేయండి:** **Save** ఎంచుకుని, తర్వాత Site, Sites జాబితాలో కనిపిస్తుందని నిర్ధారించండి.",
  ]),
  lines: guide("Manufacturing → Process & Engineering → Line", [
    "**Lines తెరవండి:** Fynd ERP ఎడమ నావిగేషన్‌లో, **Process & Engineering** తెరిచి **Line** ఎంచుకోండి.",
    "**కొత్త line ప్రారంభించండి:** కుడి పైభాగంలో ఉన్న **Create Line** ఎంచుకోండి.",
    "**అవసరమైన వివరాలు నమోదు చేయండి:** **Name**, ప్రత్యేకమైన **Code**, మరియు **Line Type** పూర్తి చేసి, అవసరమైతే Site ఎంచుకోండి.",
    "**Capacity సెట్ చేయండి:** **Capacity Per Shift**, **Capacity Per Hour** కంటే ఎక్కువగా ఉండాలి; **Task Queue Capacity** 1 నుండి 100,000 మధ్య పూర్తి సంఖ్యగా ఉండాలి.",
    "**ప్రారంభ ప్రవర్తనను ఎంచుకోండి:** కొత్తగా release చేసిన Production Tasks ఈ Line పై ప్రారంభం కావచ్చు అనుకున్నప్పుడు మాత్రమే **Is Starting Line** ఆన్ చేయండి.",
    "**Line సృష్టించండి:** Line ను active గా ఉంచి, విలువలను సమీక్షించి, **Create Line** ఎంచుకోండి.",
  ]),
  "stations-and-repair-stations": guide(
    "Manufacturing → Process & Engineering → Stations",
    [
      "**Stations తెరవండి:** **Process & Engineering** తెరిచి **Stations** ఎంచుకోండి.",
      "**ఒక operation Station సృష్టించండి:** **Create Station** ఎంచుకుని, అవసరమైన **Name**, ప్రత్యేకమైన **Code**, **Site**, మరియు **Station Category** నమోదు చేయండి.",
      "**Identity validate చేయండి:** Name కనీసం రెండు అక్షరాలు ఉండాలి. Code లో అక్షరాలు, సంఖ్యలు, hyphen మాత్రమే ఉండాలి; name మరియు code Plant లో ప్రత్యేకంగా ఉండాలి.",
      "**Location మరియు type ఎంచుకోండి:** సరైన **Site** మరియు పని విధానానికి సరిపోయే Station type ఎంచుకోండి.",
      "**Execution ను configure చేయండి:** Station కు అవసరమైనప్పుడు మాత్రమే devices, tools, లేదా automation settings జోడించండి.",
      "**Repair Station సృష్టించండి:** ప్రక్రియను పునరావృతం చేసి, ప్రత్యేక failure-handling Station కోసం Repair type ఎంచుకోండి.",
      "**Save చేసి verify చేయండి:** **Save** ఎంచుకుని, రెండు Stations active గా ఉండి Routing operations లో అందుబాటులో ఉన్నాయని నిర్ధారించండి.",
    ],
  ),
  shifts: guide("Manufacturing → Shifts & Labor → Shift Definitions", [
    "**Shift Definitions తెరవండి:** **Shifts & Labor** తెరిచి **Shift Definitions** ఎంచుకోండి.",
    "**ఒక shift ప్రారంభించండి:** **Create Shift** ఎంచుకోండి.",
    "**అవసరమైన schedule నమోదు చేయండి:** **Name**, ప్రత్యేకమైన **Code**, **Shift Type**, **Start Time**, మరియు **End Time** అవసరం. Code లో uppercase అక్షరాలు, సంఖ్యలు, hyphen ఉపయోగించండి.",
    "**సరైన time format ఉపయోగించండి:** 24-hour **HH:mm** format ఉపయోగించండి; overnight Shifts కు support ఉంది.",
    "**Breaks configure చేయండి:** ప్రతి break కు name, type, మరియు కనీసం ఒక నిమిషం అవసరం. Unpaid breaks net working time నుండి తగ్గుతాయి.",
    "**Calendar నియమాలు జోడించండి:** పని విధానం రోజువారీగా మారినప్పుడు **Shift Schedules** లేదా **Shift Calendar** ఉపయోగించండి.",
    "**Shift ను save చేయండి:** **Create Shift** లేదా **Save** ఎంచుకుని, తర్వాత అది Shift జాబితాలో అందుబాటులో ఉందని నిర్ధారించండి.",
  ]),
  "factory-readiness": guide(
    "Manufacturing → Factory setup and Process & Engineering",
    [
      "**Sites తనిఖీ చేయండి:** **Sites** తెరిచి, ప్రతి భౌతిక manufacturing స్థానం ప్రాతినిధ్యం వహించబడిందని నిర్ధారించండి.",
      "**Lines తనిఖీ చేయండి:** **Line** తెరిచి, ఉద్దేశించిన మొదటి production Line కు **Is Starting Line** ప్రారంభించబడిందని నిర్ధారించండి.",
      "**Capacity తనిఖీ చేయండి:** ప్రతి Line తెరిచి, **Task Queue Capacity**, గంటవారీ capacity, మరియు shift capacity సమీక్షించండి.",
      "**Stations తనిఖీ చేయండి:** **Stations** తెరిచి, ప్రతి Routing operation మరియు failure path కు ఒక active Station ఉందని నిర్ధారించండి.",
      "**ఒక చిన్న validation రన్ చేయండి:** factory model, Production Tasks ను స్వీకరించి route చేయగలదని నిర్ధారించడానికి ఒక చిన్న Work Order quantity ఉపయోగించండి.",
    ],
  ),
  "projects-and-product-families": guide("Manufacturing → Setup → Projects", [
    "**Projects తెరవండి:** **Setup** తెరిచి **Projects** ఎంచుకోండి.",
    "**ఒక Project సృష్టించండి:** **Create Project** ఎంచుకుని, Project identity మరియు ownership వివరాలు నమోదు చేసి, save చేయండి.",
    "**Project తెరవండి:** కొత్త Project ఎంచుకుని, దాని **Product Families** విభాగాన్ని కనుగొనండి.",
    "**ఒక Product Family సృష్టించండి:** **Create Product Family** ఎంచుకుని, దాని name మరియు code నమోదు చేసి, save చేయండి.",
    "**Hierarchy ను verify చేయండి:** Product Family, ఉద్దేశించిన Project కింద కనిపిస్తుందని మరియు Product సృష్టి సమయంలో ఎంచుకోగలదని నిర్ధారించండి.",
  ]),
  components: guide("Manufacturing → Setup → Item Master", [
    "**Item Master తెరవండి:** **Setup** తెరిచి **Item Master** ఎంచుకోండి.",
    "**ఒక component ప్రారంభించండి:** Create action ఎంచుకుని manual item creation ఎంచుకోండి.",
    "**అవసరమైన identity నమోదు చేయండి:** **Name**, ప్రత్యేకమైన **Code**, మరియు **Unit** అవసరం; name మరియు code కనీసం రెండు అక్షరాలు ఉండాలి.",
    "**Create చేయడానికి ముందు tracking ఎంచుకోండి:** **Serialized**, **Consumable**, లేదా **Fixed Serial** లో ఒక్కదాన్ని మాత్రమే ఎంచుకోవచ్చు. Fixed Serial కు శాశ్వత barcode లేదా QR value అవసరం.",
    "**Stock limits సెట్ చేయండి:** Maximum stock, minimum stock కంటే ఎక్కువగా ఉండాలి; reorder level వాటి మధ్య ఉండాలి.",
    "**Locked settings సమీక్షించండి:** Component create చేసిన తర్వాత Unit మరియు tracking settings మార్చలేరు.",
    "**Component ను save చేయండి:** **Create Component** ఎంచుకుని, తర్వాత BOM ను edit చేస్తున్నప్పుడు దానిని వెతకగలదని నిర్ధారించండి.",
  ]),
  "products-and-variants": guide("Manufacturing → Production → Products", [
    "**Products తెరవండి:** **Production** తెరిచి **Products** ఎంచుకోండి.",
    "**ఒక product ప్రారంభించండి:** **Create Product** ఎంచుకోండి.",
    "**ప్రాథమిక సమాచారం నమోదు చేయండి:** కనీసం రెండు అక్షరాల ప్రత్యేకమైన **Name** మరియు కనీసం మూడు అక్షరాల ప్రత్యేకమైన **SKU** నమోదు చేయండి; ఉపయోగిస్తే Product Family ఎంచుకోండి.",
    "**అవసరమైతే Variants జోడించండి:** Variants optional; enable చేస్తే కనీసం రెండు అవసరం.",
    "**Production configure చేయండి:** Shared BOM లేదా ప్రతి Variant కు BOM coverage ఇవ్వండి. Shared rows అన్ని Variants కు వర్తిస్తాయి; matching Variant rows వాటి quantities ను override చేస్తాయి.",
    "**Product సృష్టించండి:** validation సందేశాలను సమీక్షించి **Create Product** ఎంచుకోండి.",
  ]),
  "bill-of-materials": guide(
    "Manufacturing → Production → Products → Product detail → BOM",
    [
      "**Product తెరవండి:** **Production → Products** తెరిచి, Product ను వెతికి, దానిని ఎంచుకోండి.",
      "**BOM తెరవండి:** Product యొక్క **BOM** లేదా **BOM Versions** విభాగాన్ని ఎంచుకుని draft version తెరవండి.",
      "**Components జోడించండి:** **Add Component** ఎంచుకుని, ప్రతి Component ను వెతికి, అవసరమైన quantity నమోదు చేయండి.",
      "**Coverage సెట్ చేయండి:** సాధారణ material కోసం shared ఎంట్రీలు మరియు అవసరాలు భిన్నంగా ఉన్న చోట మాత్రమే Variant ఎంట్రీలు ఉపయోగించండి.",
      "**Quantities సమీక్షించండి:** ప్రతి quantity positive గా ఉండాలి. ఒకే scope లో ఒక Component ను రెండుసార్లు జోడించలేరు; optional unit override production అవసరానికి సరిపోవాలి.",
      "**Version ను save చేయండి:** **Save** ఎంచుకుని, activation కు ముందు ఏదైనా missing-coverage validation పరిష్కరించండి.",
    ],
  ),
  "activate-bom": guide(
    "Manufacturing → Production → Products → Product detail → BOM Versions",
    [
      "**BOM Versions తెరవండి:** Product తెరిచి **BOM Versions** ఎంచుకోండి.",
      "**Draft ను ఎంచుకోండి:** production ఉపయోగించాల్సిన version తెరవండి.",
      "**అంశాలను సమీక్షించండి:** కనీసం ఒక Component ఉందని మరియు ప్రతి Variant కు చెల్లుబాటు అయ్యే BOM coverage ఉందని నిర్ధారించండి.",
      "**Version ను release చేయండి:** **Release BOM Version** ఎంచుకుని warning నిర్ధారించండి. Release చేసిన తర్వాత editing lock అవుతుంది; ఒక Product కు ఒక BOM Version మాత్రమే Active గా ఉంటుంది.",
      "**ఫలితాన్ని verify చేయండి:** Status **Active** గా, editing controls తొలగించబడి, **Create Routing** అందుబాటులో ఉందని నిర్ధారించండి.",
    ],
  ),
  "material-tracking": guide(
    "Inventory → Inventory and Manufacturing → Production",
    [
      "**Component తెరవండి:** component catalogue వెతికి అవసరమైన Component తెరవండి.",
      "**దాని tracking నియమాన్ని ఎంచుకోండి:** వ్యక్తిగత identities కోసం serial tracking లేదా bulk material కోసం lot/quantity tracking ఎంచుకోండి.",
      "**Inventory స్వీకరించండి:** serials, supplier lots, internal lots, మరియు quantities సంగ్రహించడానికి inventory receipt flow ఉపయోగించండి.",
      "**దానిని BOM కు జోడించండి:** Product BOM తెరిచి, Component ఎంచుకుని, అవసరమైన quantity నమోదు చేయండి.",
      "**Consumption పరీక్షించండి:** ఒక చిన్న operation రన్ చేసి, genealogy రికార్డు చేయబడిందని నిర్ధారించడానికి ఒక serial స్కాన్ చేయండి లేదా quantity నమోదు చేయండి.",
    ],
  ),
  "create-routing": guide("Manufacturing → Process & Engineering → Routing", [
    "**Routing తెరవండి:** **Process & Engineering** తెరిచి **Routing** ఎంచుకోండి.",
    "**ఒక Routing ప్రారంభించండి:** **Create Routing** ఎంచుకుని, Product, active BOM Version, name, మరియు వర్తించే Variants ఎంచుకోండి.",
    "**Flow ను నిర్మించండి:** ఒక **Start** node, అవసరమైన operation nodes, మరియు ఒక **End** node జోడించండి.",
    "**Stations ను assign చేయండి:** విఫలం కాగల ప్రతి operation కోసం ఒక ప్రధాన Station మరియు వేరే Repair Station ఎంచుకోండి.",
    "**కనెక్ట్ చేసి configure చేయండి:** ప్రతి operation ను **Start** నుండి **End** వరకు connect చేసి, ప్రత్యేకమైన operation name ఉపయోగించి, అవసరమైన ప్రతి Component కు పూర్తి BOM quantity assign చేయండి.",
    "**Validate చేసి activate చేయండి:** **Validate** ఎంచుకుని అన్ని blocking errors పరిష్కరించండి. Validation pass అయ్యే వరకు **Save** అందుబాటులో ఉండదు; తరువాత save చేసి **Active** గా సెట్ చేయండి.",
  ]),
  "product-line-assignment": guide(
    "Manufacturing → Production → Products → Product detail → Lines",
    [
      "**Product తెరవండి:** **Production → Products** తెరిచి, Product ను వెతికి, దానిని ఎంచుకోండి.",
      "**Line assignments కనుగొనండి:** **Lines**, **Assigned Lines**, లేదా production assignment విభాగాన్ని తెరవండి.",
      "**ఒక Line జోడించండి:** **Assign Line** లేదా **Add Line** ఎంచుకుని, Product ను నిర్మించగల ఒక active Line ఎంచుకోండి.",
      "**ప్రత్యామ్నాయాలను జాగ్రత్తగా జోడించండి:** అదే Product వాటిపై ప్రారంభం కావచ్చు లేదా రన్ కావచ్చు అనుకున్నప్పుడు మాత్రమే అదనపు Lines ఎంచుకోండి.",
      "**Save చేసి verify చేయండి:** assignment ను save చేసి, కనీసం ఒక eligible Line కు **Is Starting Line** ప్రారంభించబడిందని నిర్ధారించండి.",
    ],
  ),
  "starting-lines-and-capacity": guide(
    "Manufacturing → Process & Engineering → Line",
    [
      "**Line తెరవండి:** **Process & Engineering → Line** తెరిచి, Line ను వెతికి, **Edit** ఎంచుకోండి.",
      "**Starting eligibility సెట్ చేయండి:** Production Tasks అక్కడ ప్రారంభం కావచ్చు అనుకున్నప్పుడు మాత్రమే **Is Starting Line** ఆన్ చేయండి.",
      "**Queue capacity సెట్ చేయండి:** **Task Queue Capacity** 1 నుండి 100,000 మధ్య పూర్తి సంఖ్యగా ఉండాలి.",
      "**Production capacity సెట్ చేయండి:** **Capacity Per Shift**, **Capacity Per Hour** కంటే ఎక్కువగా ఉండాలి; వాస్తవిక విలువలను నమోదు చేయండి.",
      "**Save చేసి పరీక్షించండి:** **Save** ఎంచుకుని, తర్వాత Work Order capacity planning తెరిచి, Line ఆశించిన headroom చూపిస్తుందని నిర్ధారించండి.",
    ],
  ),
  "product-identifiers": guide(
    "Manufacturing → Process & Engineering → Identifier Management",
    [
      "**Identifier Management తెరవండి:** **Process & Engineering** తెరిచి **Identifier Management** ఎంచుకోండి.",
      "**ఒక mapping సృష్టించండి:** అవసరమైన key, display name, మరియు definition లేదా range నమోదు చేయండి.",
      "**Key validate చేయండి:** Uppercase అక్షరాలు, సంఖ్యలు, మరియు underscores మాత్రమే ఉపయోగించండి.",
      "**Source ఎంచుకోండి:** Generated values కోసం **Range** ఉపయోగించండి; external identifiers auto-generation ను disable చేస్తాయి.",
      "**Generation timing సెట్ చేయండి:** Task creation, task start, లేదా configured Routing step వద్ద generate చేయండి; value మళ్లీ వాడకూడదంటే uniqueness enable చేయండి.",
      "**Save చేసి availability verify చేయండి:** mapping ను save చేసి, ప్రణాళిక చేసిన Work Order quantity కు తగినన్ని ఉపయోగించని విలువలు ఉన్నాయని నిర్ధారించండి.",
    ],
  ),
  "create-work-order": guide("Manufacturing → Production → Work Orders", [
    "**Work Orders తెరవండి:** **Production** తెరిచి **Work Orders** ఎంచుకోండి.",
    "**ఒక order ప్రారంభించండి:** **Create Work Order** ఎంచుకోండి.",
    "**Demand ఎంచుకోండి:** ఉపయోగించినప్పుడు Production Order ఎంచుకుని, తర్వాత Client, Product, మరియు Variant ఎంచుకోండి.",
    "**Execution వివరాలు నమోదు చేయండి:** ప్రత్యేకమైన name, quantity, priority, భవిష్యత్ due date, మరియు కనీసం ఒక Shift పూర్తి చేయండి.",
    "**Schedule validate చేయండి:** Quantity positive whole number గా, due date గతంలో కాకుండా ఉండాలి; start చేయడానికి కనీసం ఒక active Shift అవసరం.",
    "**Readiness సమీక్షించండి:** Product కు active BOM, active Routing, మరియు eligible Line assignment ఉన్నాయని నిర్ధారించండి. Inventory shortfall ఉన్నా creation అనుమతిస్తుంది; release కు ముందు పరిష్కరించాలి.",
    "**Order సృష్టించండి:** **Create Work Order** ఎంచుకుని, start journey కొనసాగించడానికి కొత్త రికార్డు తెరవండి.",
  ]),
  "generate-unit-serials": guide(
    "Manufacturing → Production → Work Orders → Work Order detail",
    [
      "**Work Order తెరవండి:** Work Orders జాబితా వెతికి draft Work Order ఎంచుకోండి.",
      "**Start journey తెరవండి:** **Start**, **Prepare**, లేదా అందుబాటులో ఉన్న production-start action ఎంచుకోండి.",
      "**Serials generate చేయండి:** **Serial Numbers** తెరిచి, configure చేసిన Product template లేదా మద్దతు ఉన్న method ఉపయోగించి **Generate** ఎంచుకోండి.",
      "**Batch సమీక్షించండి:** ప్రతి proposed value కు uniqueness validate చేసి invalid duplicates తొలగించి batch సృష్టించండి.",
      "**Batch confirm చేయండి:** Generated serials, batch confirm అయ్యే వరకు ఉపయోగించలేరు.",
      "**Quantity ను సరిపోల్చండి:** నిర్ధారించిన serial count ఖచ్చితంగా చివరి Work Order quantity కు సమానమని verify చేయండి.",
    ],
  ),
  "capacity-and-routing": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**ముందుగా serials confirm చేయండి:** Line capacity allocate చేయడానికి లేదా Routing ఎంచుకోవడానికి ముందు unit-serial batch confirm చేయండి.",
      "**Capacity and Lines తెరవండి:** draft Work Order యొక్క start journey తెరిచి **Capacity and Lines** ఎంచుకోండి.",
      "**Eligible Lines సమీక్షించండి:** Starting Lines పై ప్రస్తుత task load మరియు అందుబాటులో ఉన్న headroom పోల్చండి.",
      "**Assignment mode ఎంచుకోండి:** automatic balancing ఎంచుకోండి లేదా manual assignment ఎంచుకోండి.",
      "**Manual assignments పూర్తి చేయండి:** manual mode ఉపయోగించినప్పుడు, పూర్తి quantity కేటాయించే వరకు **Add Line Assignment** ఎంచుకోండి.",
      "**Routing ఎంచుకోండి:** ఎంచుకున్న Product మరియు Variant ను cover చేసే active Routing ఎంచుకుని, plan save చేసి inventory, identifier, మరియు Station blockers సమీక్షించండి.",
    ],
  ),
  "pre-start-validation": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**Pre-start validation తెరవండి:** సిద్ధం చేసిన Work Order తెరిచి validation step ఎంచుకోండి.",
      "**Validation రన్ చేయండి:** serials, Line capacity, మరియు Routing పూర్తయిన తర్వాత **Validate** ఎంచుకోండి.",
      "**Blockers పరిష్కరించండి:** ప్రతి failed check తెరిచి, Product, BOM, serial, identifier, inventory, లేదా capacity డేటాను సరిచేయండి.",
      "**Checks మళ్ళీ రన్ చేయండి:** ఏ blocking ఫలితం మిగలని వరకు మళ్ళీ **Validate** ఎంచుకోండి.",
      "**Production ను release చేయండి:** warnings సమీక్షించి, తర్వాత **Release Work Order** ఎంచుకుని action నిర్ధారించండి.",
    ],
  ),
  "production-tasks": guide("Manufacturing → Production → Production Tasks", [
    "**Production Tasks తెరవండి:** **Production** తెరిచి **Production Tasks** ఎంచుకోండి.",
    "**ఒక unit కనుగొనండి:** finished-unit serial, Work Order, Product, Line, లేదా status ద్వారా వెతకండి.",
    "**Task తెరవండి:** దాని ప్రస్తుత operation, assign చేసిన Line, Station, మరియు Routing position చూడటానికి task ఎంచుకోండి.",
    "**Status మరియు history సమీక్షించండి:** పూర్తయిన మరియు pending operations చూడటానికి status వివరాలు మరియు Route Logs తెరవండి.",
    "**సరైన action తీసుకోండి:** ప్రస్తుత state ఆధారంగా అందుబాటులో ఉన్న start, hold, repair, reassign, లేదా completion action ఉపయోగించండి.",
  ]),
  "operator-flow": guide("Manufacturing → Station work area", [
    "**Station work area తెరవండి:** operator యొక్క Station ఎంచుకుని finished-unit serial స్కాన్ చేయండి లేదా నమోదు చేయండి.",
    "**Operation సమీక్షించండి:** instructions, అవసరమైన Components, tools, మరియు quality gates చదవండి.",
    "**Inputs సంగ్రహించండి:** ప్రతి serialised Component స్కాన్ చేసి, bulk Components కోసం ఖచ్చితమైన quantity నమోదు చేయండి.",
    "**ఫలితాన్ని రికార్డు చేయండి:** అవసరమైన checks పూర్తి చేసి, pass, fail, hold, లేదా repair ఫలితం ఎంచుకోండి.",
    "**Operation ముగించండి:** **Complete** ఎంచుకోండి, తద్వారా Fynd ERP, Route Log ను రికార్డు చేసి unit ను దాని తదుపరి సరైన step కు తరలిస్తుంది.",
  ]),
  "material-consumption": guide(
    "Manufacturing → Station work area → Current operation",
    [
      "**Unit తెరవండి:** Station work area వద్ద, finished-unit serial స్కాన్ చేసి ప్రస్తుత operation తెరవండి.",
      "**Materials తెరవండి:** Components లేదా material-consumption విభాగాన్ని ఎంచుకోండి.",
      "**Serialised material స్కాన్ చేయండి:** ప్రతి అవసరమైన Component serial స్కాన్ చేసి, సరిపోలిన Component ను verify చేయండి.",
      "**Bulk quantities నమోదు చేయండి:** lot లేదా location ఎంచుకుని, non-serialised material కోసం వినియోగించిన quantity నమోదు చేయండి.",
      "**Operation పూర్తి చేయండి:** సంగ్రహించిన material సమీక్షించి, consumption మరియు genealogy రాయడానికి **Complete** ఎంచుకోండి.",
    ],
  ),
  "statuses-and-route-logs": guide(
    "Manufacturing → Production → Work Orders or Production Tasks",
    [
      "**రికార్డు కనుగొనండి:** Work Order లేదా Production Task వెతికి తెరవండి.",
      "**ప్రస్తుత status సమీక్షించండి:** status chip మరియు ప్రస్తుత Routing operation తనిఖీ చేయండి.",
      "**Route Logs తెరవండి:** history, timeline, లేదా **Route Logs** tab ఎంచుకోండి.",
      "**ఒక event పరిశీలించండి:** Station, operator, ఫలితం, timestamps, Components, మరియు exceptions సమీక్షించడానికి ఒక ఎంట్రీ తెరవండి.",
      "**Filter లేదా export చేయండి:** అందుబాటులో ఉన్న filters వర్తింపజేయండి లేదా investigation కోసం అవసరమైనప్పుడు history ను export చేయండి.",
    ],
  ),
  "quality-controls": guide("Manufacturing → Quality → Control Points", [
    "**Control Points తెరవండి:** **Quality** తెరిచి **Control Points** ఎంచుకోండి.",
    "**Control సృష్టించండి:** Inspection name మరియు అవసరమైన **Control Type**, **Frequency**, **Failure Action** నమోదు చేయండి.",
    "**Scope ఎంచుకోండి:** Control ను Product, production Line, Station, లేదా Routing operation కు bind చేయండి.",
    "**Outcomes నిర్వచించండి:** కొలవగల pass criteria మరియు quarantine లేదా automatic Hold వంటి failure behavior configure చేయండి.",
    "**Save చేసి పరీక్షించండి:** control ను save చేసి, అది కనిపిస్తుందని నిర్ధారించడానికి operation ద్వారా ఒక చిన్న unit రన్ చేయండి.",
  ]),
  "inspection-to-capa": guide("Manufacturing → Quality", [
    "**Inspection సృష్టించండి:** **Quality Inspections** తెరిచి production source నుండి Inspection ప్రారంభించండి.",
    "**Valid production ఎంచుకోండి:** Started Work Order లేదా valid lot ఎంచుకుని affected quantity నమోదు చేయండి.",
    "**సమస్యను సంగ్రహించండి:** Failure వచ్చినప్పుడు symptom, severity, source, evidence, మరియు affected unit తో **Defect** సృష్టించండి లేదా link చేయండి.",
    "**Output ను నియంత్రించండి:** **NCR Reports** లో non-conformance నమోదు చేసి Disposition రికార్డు చేయండి.",
    "**అవసరమైతే escalate చేయండి:** **CAPA** లో corrective లేదా preventive action assign చేసి verification వరకు track చేయండి.",
  ]),
  "repair-and-rework": guide("Manufacturing → Repair & Rework", [
    "**Decision రికార్డు చేయండి:** **Quality → Dispositions** తెరిచి affected record కు అవసరమైన rationale మరియు action నమోదు చేయండి.",
    "**Source link కాపాడండి:** Original serial, Defect, మరియు Disposition linked గా ఉన్నాయని నిర్ధారించండి.",
    "**Rework Board తెరవండి:** **Repair & Rework → Rework Board** లో tracked Rework job లేదా Work Order సృష్టించండి.",
    "**Work రికార్డు చేయండి:** Symptoms, diagnosis, repair/rework actions, మరియు అవసరమైన replacement Components నమోదు చేయండి.",
    "**Reinspect చేసి close చేయండి:** Allowed Routing point కు పంపే ముందు లేదా job close చేసే ముందు required reinspection పూర్తి చేయండి.",
  ]),
  "hold-scrap-teardown": guide("Manufacturing → Quality or Scrap & Teardown", [
    "**ప్రభావిత unit తెరవండి:** Production Task, quality రికార్డు, లేదా material రికార్డు కనుగొనండి.",
    "**Exception ఎంచుకోండి:** ఆమోదించిన నిర్ణయం ప్రకారం **Hold**, **Scrap**, లేదా **Teardown** ఎంచుకోండి.",
    "**కారణం నమోదు చేయండి:** configure చేసిన కారణం ఎంచుకుని, notes, evidence, affected quantity, మరియు ownership జోడించండి.",
    "**Action నిర్ధారించండి:** తిరిగి మార్చలేని ప్రభావాన్ని సమీక్షించండి; Scrap approval మరియు execution states ద్వారా సాగుతుంది.",
    "**Follow-up పూర్తి చేయండి:** పరిష్కారం తర్వాత మాత్రమే Hold release చేయండి. Executed Scrap dispatch అయిన తర్వాత Teardown అందుబాటులో ఉంటుంది; recovered Components ను donor-unit context తో రికార్డు చేయండి.",
  ]),
  packaging: guide("Manufacturing → Packaging & Shipping → Packaging", [
    "**Packaging తెరవండి:** **Packaging & Shipping** తెరిచి **Packaging** ఎంచుకోండి.",
    "**ఒక container ప్రారంభించండి లేదా కనుగొనండి:** ఇప్పటికే ఉన్న container స్కాన్ చేయండి లేదా సరైన Container Type ఉపయోగించి ఒకటి సృష్టించే action ఎంచుకోండి.",
    "**Finished units జోడించండి:** ప్రతి eligible finished-unit serial ను container లోకి స్కాన్ చేయండి.",
    "**Checks రన్ చేయండి:** Configured Container Type, quantity, weight, declarations, మరియు label verification పూర్తి చేయండి.",
    "**Container మూసివేయండి:** అన్ని configured checks pass అయ్యే వరకు container open గా ఉంచి, తరువాత label print చేసి close లేదా complete action ఎంచుకోండి.",
  ]),
  "containers-and-labels": guide("Manufacturing → Packaging & Shipping", [
    "**Packaging configuration తెరవండి:** Product కు సంబంధించిన Container Types, packaging rules, మరియు label templates తెరవండి.",
    "**Hierarchy నిర్మించండి:** Unit, box, carton, pallet వంటి అనుమతించిన leaf-to-parent క్రమాన్ని configure చేయండి.",
    "**Identities bind చేయండి:** Leaf container finished-unit serial ను bind చేస్తుంది; ప్రతి parent configured child UID ను మాత్రమే అంగీకరిస్తుంది.",
    "**Label సృష్టించండి:** Product, unit, container, quantity, మరియు shipment scanning కు అవసరమైన template variables జోడించండి.",
    "**Test చేసి audit చేయండి:** Test label print చేసి label history మరియు reprints traceable గా ఉన్నాయని నిర్ధారించండి.",
  ]),
  "shipment-verification": guide(
    "Manufacturing → Packaging & Shipping → Shipment Verification",
    [
      "**Shipment Verification తెరవండి:** **Packaging & Shipping** తెరిచి **Shipment Verification** ఎంచుకోండి.",
      "**ముందుగా Shipment ఎంచుకోండి:** Shipment ఎంచుకునే వరకు verification ప్రారంభం కాదు; అప్పటి వరకు **Container Type** అందుబాటులో ఉండదు.",
      "**Container Type ఎంచుకుని verify చేయండి:** Expected container UIDs scan చేసి Verified, Mismatched, మరియు Pending counts సమీక్షించండి.",
      "**నియమాలను సమీక్షించండి:** Active Shipment Rule container count మరియు weight ను అనుమతిస్తుందో, Shipping Gate లో తగిన approved PO quantity ఉందో నిర్ధారించండి.",
      "**తేడాలను పరిష్కరించండి:** Completion కు ముందు mismatches సరిచేసి, export అవసరమైతే client-specific ASN template ఉపయోగించండి.",
    ],
  ),
  "traceability-genealogy-recall": guide(
    "Manufacturing → Traceability → Master Traceability",
    [
      "**Master Traceability తెరవండి:** **Traceability** తెరిచి **Master Traceability** ఎంచుకోండి.",
      "**Dossier scope సెట్ చేయండి:** Filters combine చేయండి లేదా identifier list paste చేయండి; identifier list ఇతర scope filters ను override చేస్తుంది.",
      "**Report sheets ఎంచుకోండి:** అవసరమైన unit, route, quality, genealogy, packaging, shipment, లేదా audit sheets ఎంచుకుని dossier generate చేయండి.",
      "**Stage Timeline సరిగ్గా ఉపయోగించండి:** Start/end dates, కనీసం ఒక Work Order, మరియు 1–50 Operations ఎంచుకోండి.",
      "**Genealogy అనుసరించండి:** **Batch Genealogy** లో upstream/downstream search చేయండి లేదా material lot/Component కోసం **Find Affected Units** ఉపయోగించండి.",
      "**అవసరమైతే containment ప్రారంభించండి:** **Recall Notices** లో severity, status, reason, మరియు affected-unit population రికార్డు చేయండి.",
    ],
  ),
  dashboards: guide(
    "Manufacturing → Dashboard, Work Orders, Production Tasks, and Route Logs",
    [
      "**Plant dashboard సమీక్షించండి:** Current Plant కోసం readiness, active Work Orders, Stations, Products, మరియు targets చూడండి.",
      "**Work Orders తెరవండి:** Schedule risk కనుగొనడానికి status, priority, మరియు due date సమీక్షించండి.",
      "**Production Tasks తెరవండి:** Serial ద్వారా వెతికి Product, Routing, assigned Line, మరియు task status సమీక్షించండి.",
      "**Route Logs తెరవండి:** Operator, Station, Line, timestamp, మరియు quality result సహా execution evidence నిర్ధారించండి.",
      "**Source record పరిశీలించండి:** Corrective action తీసుకునే ముందు underlying Work Order, Task, లేదా Route Log తెరవండి.",
    ],
  ),
  "shift-operations": guide("Manufacturing → Shifts & Labor", [
    "**Shift Definitions సమీక్షించండి:** Timing, breaks, మరియు calculated net working duration నిర్ధారించండి.",
    "**Shift Schedules సమీక్షించండి:** Effective dates మరియు weekly pattern configure చేసి, సిద్ధమైనప్పుడు Schedule activate చేయండి; కొత్త Schedules మొదట Draft గా ఉంటాయి.",
    "**Handover సృష్టించండి:** **Shift Handovers** లో date, Shift, Line, outgoing operator, incoming operator, status, మరియు notes నమోదు చేయండి.",
    "**ప్రస్తుత పరిస్థితులను రికార్డు చేయండి:** WIP, holds, downtime, material risk, quality issues, మరియు unresolved actions జోడించండి.",
    "**Break Compliance తనిఖీ చేయండి:** Planned/actual duration, violations, మరియు compliance చూడండి; filtered results ఉన్నప్పుడు మాత్రమే export అందుబాటులో ఉంటుంది.",
  ]),
  "tools-and-maintenance": guide(
    "Manufacturing → Process & Engineering → Tools and Equipments",
    [
      "**Tools తెరవండి:** **Process & Engineering → Tools and Equipments** తెరిచి **Tools** ఎంచుకోండి.",
      "**Tool సృష్టించండి లేదా కనుగొనండి:** create action ఎంచుకోండి లేదా ఇప్పటికే ఉన్న Tool రికార్డు వెతకండి.",
      "**Control details సమీక్షించండి:** Identity, manufacturer/model, category, assigned Station, మరియు availability status నిర్ధారించండి.",
      "**Maintenance Alerts సమీక్షించండి:** Priority, owner, affected Tool/equipment, Line, మరియు status చూసి అవసరమైతే maintenance check trigger చేయండి.",
      "**Maintenance Work Orders ఉపయోగించండి:** Maintenance type, priority, assigned owner, scheduled start, మరియు completion status track చేయండి.",
      "**Production రక్షించండి:** Availability లేదా maintenance state అనుకూలంగా లేకపోతే Tool ను execution కు ఉపయోగించవద్దు.",
    ],
  ),
  "reports-and-audit": guide(
    "Traceability → Master Traceability; Production → Work Orders",
    [
      "**Traceability report నిర్మించండి:** **Master Traceability** లో required scope మరియు investigation కు అవసరమైన dossier sheets ఎంచుకోండి.",
      "**Dossier generate చేయండి:** Unit, route, quality, genealogy, identifier, tool, packaging, మరియు shipment evidence సమీక్షించండి.",
      "**Operational records export చేయండి:** **Work Orders** లో filters ఉంచి **Export Work Orders** ఎంచుకోండి.",
      "**Change history తెరవండి:** Entity Recent Changes history కోసం **View all changes** ఎంచుకోండి.",
      "**Evidence సమీక్షించండి:** Actor, action, entity, changed fields, మరియు timestamp నిర్ధారించి affected record కు తిరిగి వెళ్ళండి.",
    ],
  ),
  "first-production-run": guide("Manufacturing → Production → Work Orders", [
    "**ఒక trial Work Order సృష్టించండి:** **Create Work Order** ఎంచుకుని, చిన్న కానీ వాస్తవిక quantity ఉపయోగించండి.",
    "**సిద్ధం చేసి release చేయండి:** serials, capacity, Routing, material, మరియు identifiers నిర్ధారించి, తర్వాత **Release Work Order** ఎంచుకోండి.",
    "**సాధారణ మార్గం రన్ చేయండి:** కనీసం ఒక unit ను ప్రతి అవసరమైన operation ద్వారా పూర్తి చేయండి.",
    "**ఒక exception పరీక్షించండి:** ఒక నియంత్రిత operation ను విఫలం చేసి, దాని Repair లేదా Rework మార్గం పూర్తి చేయండి.",
    "**ముగించి trace చేయండి:** వర్తించే quality, packaging, మరియు shipment steps పూర్తి చేసి, తర్వాత **Master Traceability** లో unit వెతకండి.",
  ]),
  troubleshooting: guide("The affected Fynd ERP module", [
    "**విఫలమైన రికార్డు తెరవండి:** error చూపిస్తున్న Product, Routing, Work Order, Production Task, లేదా shipment కు తిరిగి వెళ్ళండి.",
    "**Validation సందేశం చదవండి:** విఫలమైన check విస్తరించి, ఖచ్చితమైన missing field, relationship, status, లేదా quantity గమనించండి.",
    "**Prerequisites తనిఖీ చేయండి:** వర్తించే విధంగా active BOM, Stations, Repair Stations, Shift, Line assignment, capacity, serials, inventory, మరియు identifiers verify చేయండి.",
    "**Source రికార్డును సరిచేయండి:** linked configuration తెరిచి, అవసరమైన మార్పు చేసి, **Save** ఎంచుకోండి.",
    "**Action మళ్ళీ ప్రయత్నించండి:** అసలు రికార్డుకు తిరిగి వెళ్ళి **Validate**, **Create**, **Release**, లేదా **Complete** మళ్ళీ ఎంచుకోండి.",
  ]),
};
