import type { ForgeTaskGuide } from "./forge-task-guides";

const guide = (navigationPath: string, steps: string[]): ForgeTaskGuide => ({
  navigationPath,
  steps,
});

export const TASK_GUIDES_TA: Record<string, ForgeTaskGuide> = {
  "complete-setup-journey": guide("Fynd ERP Dashboard", [
    "**அமைப்புப் பயணத்தைத் திறங்கள்:** Setup, Process & Engineering, Production, மற்றும் Traceability வழியாக வரிசையாக வேலை செய்ய இடது வழிசெலுத்தலைப் பயன்படுத்துங்கள்.",
    "**தொழிற்சாலைப் பதிவுகளை உருவாக்குங்கள்:** Sites, Lines, operation Stations, Repair Stations, மற்றும் Shift Definitions-ஐ உருவாக்குங்கள்.",
    "**தயாரிப்புப் பதிவுகளை உருவாக்குங்கள்:** Project, Product Family, Components, Product, Variants, மற்றும் BOM Version-ஐ உருவாக்குங்கள்.",
    "**செயலாக்கத்தைத் தயார் செய்யுங்கள்:** BOM-ஐச் செயலில் ஆக்கி, Routing-ஐ உருவாக்கி சரிபார்த்து, Product-ஐ தகுதியான Lines-க்கு ஒதுக்குங்கள்.",
    "**ஒரு சோதனை ஆர்டரைத் தொடங்குங்கள்:** ஒரு சிறிய Work Order-ஐ உருவாக்கி, அலகு சீரியல்களை உறுதிப்படுத்தி, திறனையும் Routing-ஐயும் தேர்ந்தெடுத்து, சரிபார்ப்பை இயக்கி, Release-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  sites: guide("Manufacturing → Setup → Sites", [
    "**Sites-ஐத் திறங்கள்:** Fynd ERP இடது வழிசெலுத்தலில் **Setup**-ஐத் திறந்து **Sites**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு புதிய பதிவைத் தொடங்குங்கள்:** மேல்-வலது மூலையில் **Create Site**-ஐத் தேர்ந்தெடுங்கள்.",
    "**தேவையான அடையாளத்தை உள்ளிடுங்கள்:** **Name** மற்றும் தனித்துவமான **Code**-ஐ உள்ளிடுங்கள். Code-இல் uppercase எழுத்துகள், எண்கள், மற்றும் hyphen மட்டுமே பயன்படுத்துங்கள்.",
    "**தேவைப்பட்டால் இருப்பிடத்தைச் சேர்க்குங்கள்:** **Country**-ஐத் தேர்ந்தெடுத்த பின்பு **State**, பின்னர் **City** இயங்கும்.",
    "**விருப்ப metadata-ஐ கவனமாகச் சேர்க்குங்கள்:** Metadata 32 KB வரம்புக்குள் இருக்க வேண்டும்; தேடலுக்கு உதவும்போது மட்டும் tags சேர்க்குங்கள்.",
    "**சேமித்து சரிபார்க்குங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து, பின்னர் Site, Sites பட்டியலில் தோன்றுவதை உறுதிப்படுத்துங்கள்.",
  ]),
  lines: guide("Manufacturing → Process & Engineering → Line", [
    "**Lines-ஐத் திறங்கள்:** Fynd ERP இடது வழிசெலுத்தலில், **Process & Engineering**-ஐத் திறந்து **Line**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு புதிய line-ஐத் தொடங்குங்கள்:** மேல்-வலது மூலையில் **Create Line**-ஐத் தேர்ந்தெடுங்கள்.",
    "**தேவையான விவரங்களை உள்ளிடுங்கள்:** **Name**, தனித்துவமான **Code**, மற்றும் **Line Type**-ஐ முடித்து, தேவையானபோது Site-ஐத் தேர்ந்தெடுங்கள்.",
    "**திறனை அமைக்குங்கள்:** **Capacity Per Shift**, **Capacity Per Hour**-ஐ விட அதிகமாக இருக்க வேண்டும்; **Task Queue Capacity** 1 முதல் 100,000 வரையிலான முழு எண்ணாக இருக்க வேண்டும்.",
    "**தொடக்க நடத்தையைத் தேர்வுசெய்யுங்கள்:** புதிதாக வெளியிடப்பட்ட Production Tasks இந்த Line-இல் தொடங்கக்கூடியபோது மட்டுமே **Is Starting Line**-ஐ இயக்குங்கள்.",
    "**line-ஐ உருவாக்குங்கள்:** Line-ஐ செயலில் வைத்திருந்து, மதிப்புகளை மதிப்பாய்வு செய்து, **Create Line**-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  "stations-and-repair-stations": guide(
    "Manufacturing → Process & Engineering → Stations",
    [
      "**Stations-ஐத் திறங்கள்:** **Process & Engineering**-ஐத் திறந்து **Stations**-ஐத் தேர்ந்தெடுங்கள்.",
      "**ஒரு operation Station-ஐ உருவாக்குங்கள்:** **Create Station**-ஐத் தேர்ந்தெடுத்து, தேவையான **Name**, தனித்துவமான **Code**, **Site**, மற்றும் **Station Category**-ஐ உள்ளிடுங்கள்.",
      "**அடையாளத்தைச் சரிபார்க்குங்கள்:** பெயர் குறைந்தது இரண்டு எழுத்துகள் இருக்க வேண்டும். Code-இல் எழுத்துகள், எண்கள், hyphen மட்டுமே இருக்கலாம்; பெயரும் code-மும் Plant-க்குள் தனித்துவமாக இருக்க வேண்டும்.",
      "**இடத்தையும் வகையையும் தேர்ந்தெடுங்கள்:** சரியான **Site** மற்றும் வேலை செய்யும் முறைக்கு பொருத்தமான Station type-ஐத் தேர்ந்தெடுங்கள்.",
      "**செயலாக்கத்தைக் கட்டமையுங்கள்:** Station-க்குத் தேவைப்படும்போது மட்டுமே devices, tools, அல்லது automation அமைப்புகளைச் சேர்க்குங்கள்.",
      "**Repair Station-ஐ உருவாக்குங்கள்:** செயல்முறையை மீண்டும் செய்து, பிரத்யேக தோல்வி-கையாளும் Station-க்கு Repair வகையைத் தேர்வுசெய்யுங்கள்.",
      "**சேமித்து சரிபார்க்குங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து இரண்டு Stations-ம் செயலில் உள்ளன மற்றும் Routing operations-இல் கிடைக்கின்றன என்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  shifts: guide("Manufacturing → Shifts & Labor → Shift Definitions", [
    "**Shift Definitions-ஐத் திறங்கள்:** **Shifts & Labor**-ஐத் திறந்து **Shift Definitions**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு shift-ஐத் தொடங்குங்கள்:** **Create Shift**-ஐத் தேர்ந்தெடுங்கள்.",
    "**தேவையான அட்டவணையை உள்ளிடுங்கள்:** **Name**, தனித்துவமான **Code**, **Shift Type**, **Start Time**, மற்றும் **End Time** தேவை. Code-இல் uppercase எழுத்துகள், எண்கள், hyphen பயன்படுத்துங்கள்.",
    "**செல்லுபடியாகும் நேரத்தைப் பயன்படுத்துங்கள்:** 24-hour **HH:mm** format-ஐ பயன்படுத்துங்கள்; overnight Shifts ஆதரிக்கப்படுகின்றன.",
    "**இடைவேளைகளை அமைக்குங்கள்:** ஒவ்வொரு break-க்கும் பெயர், வகை, மற்றும் குறைந்தது ஒரு நிமிடம் தேவை. Unpaid breaks net working time-இலிருந்து கழிக்கப்படும்.",
    "**நாட்காட்டி விதிகளைச் சேர்க்குங்கள்:** வேலை முறை நாளுக்கு நாள் மாறும்போது **Shift Schedules** அல்லது **Shift Calendar**-ஐப் பயன்படுத்துங்கள்.",
    "**shift-ஐ சேமியுங்கள்:** **Create Shift** அல்லது **Save**-ஐத் தேர்ந்தெடுத்து, பின்னர் அது Shift பட்டியலில் கிடைக்கிறது என்பதை உறுதிப்படுத்துங்கள்.",
  ]),
  "factory-readiness": guide(
    "Manufacturing → Factory setup and Process & Engineering",
    [
      "**Sites-ஐச் சரிபார்க்குங்கள்:** **Sites**-ஐத் திறந்து ஒவ்வொரு இயற்பியல் உற்பத்தி இருப்பிடமும் பிரதிநிதித்துவப்படுத்தப்படுகிறது என்பதை உறுதிப்படுத்துங்கள்.",
      "**Lines-ஐச் சரிபார்க்குங்கள்:** **Line**-ஐத் திறந்து நோக்கம் கொண்ட முதல் உற்பத்தி Line-க்கு **Is Starting Line** இயக்கப்பட்டுள்ளதை உறுதிப்படுத்துங்கள்.",
      "**திறனைச் சரிபார்க்குங்கள்:** ஒவ்வொரு Line-ஐயும் திறந்து **Task Queue Capacity**, மணிநேரத் திறன், மற்றும் shift திறனை மதிப்பாய்வு செய்யுங்கள்.",
      "**Stations-ஐச் சரிபார்க்குங்கள்:** **Stations**-ஐத் திறந்து ஒவ்வொரு Routing operation மற்றும் தோல்விப் பாதைக்கும் ஒரு செயலில் உள்ள Station உள்ளதை உறுதிப்படுத்துங்கள்.",
      "**ஒரு சிறிய சரிபார்ப்பை இயக்குங்கள்:** தொழிற்சாலை மாதிரி Production Tasks-ஐ ஏற்று வழிநடத்த முடியும் என்பதை உறுதிப்படுத்த ஒரு சிறிய Work Order அளவைப் பயன்படுத்துங்கள்.",
    ],
  ),
  "projects-and-product-families": guide("Manufacturing → Setup → Projects", [
    "**Projects-ஐத் திறங்கள்:** **Setup**-ஐத் திறந்து **Projects**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு Project-ஐ உருவாக்குங்கள்:** **Create Project**-ஐத் தேர்ந்தெடுத்து, Project அடையாளம் மற்றும் உரிமை விவரங்களை உள்ளிட்டு, பின்னர் அதைச் சேமியுங்கள்.",
    "**Project-ஐத் திறங்கள்:** புதிய Project-ஐத் தேர்ந்தெடுத்து அதன் **Product Families** பகுதியைக் கண்டறியுங்கள்.",
    "**ஒரு Product Family-ஐ உருவாக்குங்கள்:** **Create Product Family**-ஐத் தேர்ந்தெடுத்து, அதன் பெயரையும் குறியீட்டையும் உள்ளிட்டு, சேமியுங்கள்.",
    "**படிநிலையைச் சரிபார்க்குங்கள்:** Product Family நோக்கம் கொண்ட Project-க்குக் கீழ் தோன்றுவதையும் Product உருவாக்கத்தின் போது தேர்ந்தெடுக்க முடிவதையும் உறுதிப்படுத்துங்கள்.",
  ]),
  components: guide("Manufacturing → Setup → Item Master", [
    "**Item Master-ஐத் திறங்கள்:** **Setup**-ஐத் திறந்து **Item Master**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு component-ஐத் தொடங்குங்கள்:** Create action-ஐத் தேர்ந்தெடுத்து manual item creation-ஐத் தேர்வுசெய்யுங்கள்.",
    "**தேவையான அடையாளத்தை உள்ளிடுங்கள்:** **Name**, தனித்துவமான **Code**, மற்றும் **Unit** தேவை; பெயரும் code-மும் குறைந்தது இரண்டு எழுத்துகள் இருக்க வேண்டும்.",
    "**உருவாக்குவதற்கு முன் tracking-ஐத் தேர்ந்தெடுங்கள்:** **Serialized**, **Consumable**, அல்லது **Fixed Serial**-இல் ஒன்றை மட்டும் தேர்வுசெய்யலாம். Fixed Serial-க்கு நிரந்தர barcode அல்லது QR value தேவை.",
    "**Stock வரம்புகளை அமைக்குங்கள்:** Maximum stock, minimum stock-ஐ விட அதிகமாகவும் reorder level அவற்றுக்கிடையிலும் இருக்க வேண்டும்.",
    "**மாற்ற முடியாத அமைப்புகளை மதிப்பாய்வு செய்யுங்கள்:** Component உருவாக்கப்பட்ட பின் Unit மற்றும் tracking settings-ஐ மாற்ற முடியாது.",
    "**component-ஐ சேமியுங்கள்:** **Create Component**-ஐத் தேர்ந்தெடுத்து, பின்னர் ஒரு BOM-ஐ திருத்தும்போது அதைத் தேட முடியும் என்பதை உறுதிப்படுத்துங்கள்.",
  ]),
  "products-and-variants": guide("Manufacturing → Production → Products", [
    "**Products-ஐத் திறங்கள்:** **Production**-ஐத் திறந்து **Products**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு product-ஐத் தொடங்குங்கள்:** **Create Product**-ஐத் தேர்ந்தெடுங்கள்.",
    "**அடிப்படைத் தகவலை உள்ளிடுங்கள்:** குறைந்தது இரண்டு எழுத்துகள் கொண்ட தனித்துவமான **Name** மற்றும் குறைந்தது மூன்று எழுத்துகள் கொண்ட தனித்துவமான **SKU**-ஐ உள்ளிடுங்கள்; பயன்படுத்தினால் Product Family-ஐத் தேர்ந்தெடுங்கள்.",
    "**தேவைப்பட்டால் Variants-ஐச் சேர்க்குங்கள்:** Variants விருப்பமானவை; இயக்கினால் குறைந்தது இரண்டு தேவை.",
    "**உற்பத்தியை அமைக்குங்கள்:** Shared BOM அல்லது ஒவ்வொரு Variant-க்கும் BOM coverage கொடுங்கள். Shared rows எல்லா Variants-க்கும் பொருந்தும்; matching Variant rows அவற்றின் quantities-ஐ override செய்யும்.",
    "**product-ஐ உருவாக்குங்கள்:** சரிபார்ப்பு செய்திகளை மதிப்பாய்வு செய்து **Create Product**-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  "bill-of-materials": guide(
    "Manufacturing → Production → Products → Product detail → BOM",
    [
      "**Product-ஐத் திறங்கள்:** **Production → Products**-ஐத் திறந்து, Product-ஐத் தேடி, அதைத் தேர்ந்தெடுங்கள்.",
      "**BOM-ஐத் திறங்கள்:** Product-இன் **BOM** அல்லது **BOM Versions** பகுதியைத் தேர்ந்தெடுத்து வரைவுப் பதிப்பைத் திறங்கள்.",
      "**Components-ஐச் சேர்க்குங்கள்:** **Add Component**-ஐத் தேர்ந்தெடுத்து, ஒவ்வொரு Component-ஐயும் தேடி, தேவையான அளவை உள்ளிடுங்கள்.",
      "**கவரேஜை அமைக்குங்கள்:** பொதுவான பொருளுக்கு பகிரப்பட்ட உள்ளீடுகளையும், தேவைகள் வேறுபடும் இடங்களில் மட்டும் Variant உள்ளீடுகளையும் பயன்படுத்துங்கள்.",
      "**அளவுகளை மதிப்பாய்வு செய்யுங்கள்:** ஒவ்வொரு quantity-மும் positive ஆக இருக்க வேண்டும். ஒரே scope-இல் ஒரே Component-ஐ இருமுறை சேர்க்க முடியாது; optional unit override உற்பத்தித் தேவைக்கு பொருந்த வேண்டும்.",
      "**பதிப்பை சேமியுங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து, செயல்படுத்துவதற்கு முன் இல்லாத-கவரேஜ் சரிபார்ப்பைத் தீர்க்குங்கள்.",
    ],
  ),
  "activate-bom": guide(
    "Manufacturing → Production → Products → Product detail → BOM Versions",
    [
      "**BOM Versions-ஐத் திறங்கள்:** Product-ஐத் திறந்து **BOM Versions**-ஐத் தேர்ந்தெடுங்கள்.",
      "**வரைவைத் தேர்வுசெய்யுங்கள்:** உற்பத்தி பயன்படுத்த வேண்டிய பதிப்பைத் திறங்கள்.",
      "**உருப்படிகளை மதிப்பாய்வு செய்யுங்கள்:** குறைந்தது ஒரு Component உள்ளது மற்றும் ஒவ்வொரு Variant-க்கும் செல்லுபடியாகும் BOM கவரேஜ் உள்ளது என்பதை உறுதிப்படுத்துங்கள்.",
      "**பதிப்பை வெளியிடுங்கள்:** **Release BOM Version**-ஐத் தேர்ந்தெடுத்து warning-ஐ உறுதிப்படுத்துங்கள். Release செய்த பின் editing lock ஆகும்; ஒரு Product-க்கு ஒரே ஒரு BOM Version மட்டுமே Active ஆக இருக்கும்.",
      "**முடிவைச் சரிபார்க்குங்கள்:** Status **Active** ஆகவும் editing controls அகற்றப்பட்டும் **Create Routing** கிடைக்கிறதையும் உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "material-tracking": guide(
    "Inventory → Inventory and Manufacturing → Production",
    [
      "**Component-ஐத் திறங்கள்:** component பட்டியலைத் தேடி தேவையான Component-ஐத் திறங்கள்.",
      "**அதன் கண்காணிப்பு விதியைத் தேர்வுசெய்யுங்கள்:** தனிப்பட்ட அடையாளங்களுக்கு serial கண்காணிப்பையோ அல்லது மொத்தப் பொருளுக்கு lot/quantity கண்காணிப்பையோ தேர்ந்தெடுங்கள்.",
      "**இருப்பைப் பெறுங்கள்:** serials, சப்ளையர் lots, உள் lots, மற்றும் அளவுகளைப் பிடிக்க inventory receipt flow-ஐப் பயன்படுத்துங்கள்.",
      "**அதை BOM-க்குச் சேர்க்குங்கள்:** Product BOM-ஐத் திறந்து, Component-ஐத் தேர்ந்தெடுத்து, தேவையான அளவை உள்ளிடுங்கள்.",
      "**நுகர்வைச் சோதியுங்கள்:** ஒரு சிறிய operation-ஐ இயக்கி, genealogy பதிவாகிறது என்பதை உறுதிப்படுத்த ஒரு serial-ஐ ஸ்கேன் செய்யுங்கள் அல்லது ஒரு அளவை உள்ளிடுங்கள்.",
    ],
  ),
  "create-routing": guide("Manufacturing → Process & Engineering → Routing", [
    "**Routing-ஐத் திறங்கள்:** **Process & Engineering**-ஐத் திறந்து **Routing**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு Routing-ஐத் தொடங்குங்கள்:** **Create Routing**-ஐத் தேர்ந்தெடுத்து, பின்னர் Product, செயலில் உள்ள BOM Version, பெயர், மற்றும் பொருந்தக்கூடிய Variants-ஐத் தேர்வுசெய்யுங்கள்.",
    "**flow-ஐ கட்டமையுங்கள்:** ஒரு **Start** node, தேவையான operation nodes, மற்றும் ஒரு **End** node-ஐச் சேர்க்குங்கள்.",
    "**Stations-ஐ ஒதுக்குங்கள்:** தோல்வியடையக்கூடிய ஒவ்வொரு operation-க்கும் ஒரு முக்கிய Station மற்றும் வேறுபட்ட Repair Station-ஐத் தேர்ந்தெடுங்கள்.",
    "**இணைத்து கட்டமையுங்கள்:** ஒவ்வொரு operation-ஐயும் **Start** முதல் **End** வரை இணைத்து, தனித்துவமான operation name-ஐப் பயன்படுத்தி, தேவையான ஒவ்வொரு Component-க்கும் முழு BOM quantity-ஐ ஒதுக்குங்கள்.",
    "**சரிபார்த்து செயலில் ஆக்குங்கள்:** **Validate**-ஐத் தேர்ந்தெடுத்து எல்லா blocking errors-ஐயும் தீர்க்குங்கள். Validation pass ஆகும் வரை **Save** கிடைக்காது; பின்னர் save செய்து **Active** ஆக அமைக்குங்கள்.",
  ]),
  "product-line-assignment": guide(
    "Manufacturing → Production → Products → Product detail → Lines",
    [
      "**Product-ஐத் திறங்கள்:** **Production → Products**-ஐத் திறந்து, Product-ஐத் தேடி, அதைத் தேர்ந்தெடுங்கள்.",
      "**Line ஒதுக்கீடுகளைக் கண்டறியுங்கள்:** **Lines**, **Assigned Lines**, அல்லது உற்பத்தி ஒதுக்கீட்டுப் பகுதியைத் திறங்கள்.",
      "**ஒரு Line-ஐச் சேர்க்குங்கள்:** **Assign Line** அல்லது **Add Line**-ஐத் தேர்ந்தெடுத்து, பின்னர் Product-ஐ கட்டமைக்கக்கூடிய ஒரு செயலில் உள்ள Line-ஐத் தேர்வுசெய்யுங்கள்.",
      "**மாற்றுகளை கவனமாகச் சேர்க்குங்கள்:** அதே Product அவற்றில் தொடங்கவோ இயங்கவோ கூடியபோது மட்டுமே கூடுதல் Lines-ஐத் தேர்ந்தெடுங்கள்.",
      "**சேமித்து சரிபார்க்குங்கள்:** ஒதுக்கீட்டைச் சேமித்து, குறைந்தது ஒரு தகுதியான Line-க்கு **Is Starting Line** இயக்கப்பட்டுள்ளதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "starting-lines-and-capacity": guide(
    "Manufacturing → Process & Engineering → Line",
    [
      "**Line-ஐத் திறங்கள்:** **Process & Engineering → Line**-ஐத் திறந்து, Line-ஐத் தேடி, **Edit**-ஐத் தேர்ந்தெடுங்கள்.",
      "**தொடக்கத் தகுதியை அமைக்குங்கள்:** Production Tasks அங்கே தொடங்கக்கூடியபோது மட்டுமே **Is Starting Line**-ஐ இயக்குங்கள்.",
      "**queue திறனை அமைக்குங்கள்:** **Task Queue Capacity** 1 முதல் 100,000 வரையிலான முழு எண்ணாக இருக்க வேண்டும்.",
      "**உற்பத்தித் திறனை அமைக்குங்கள்:** **Capacity Per Shift**, **Capacity Per Hour**-ஐ விட அதிகமாக இருக்க வேண்டும்; யதார்த்தமான மதிப்புகளை உள்ளிடுங்கள்.",
      "**சேமித்து சோதியுங்கள்:** **Save**-ஐத் தேர்ந்தெடுத்து, பின்னர் Work Order திறன் திட்டமிடலைத் திறந்து Line எதிர்பார்க்கப்பட்ட இடத்தைக் காட்டுவதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "product-identifiers": guide(
    "Manufacturing → Process & Engineering → Identifier Management",
    [
      "**Identifier Management-ஐத் திறங்கள்:** **Process & Engineering**-ஐத் திறந்து **Identifier Management**-ஐத் தேர்ந்தெடுங்கள்.",
      "**ஒரு mapping-ஐ உருவாக்குங்கள்:** தேவையான key, display name, மற்றும் definition அல்லது range-ஐ உள்ளிடுங்கள்.",
      "**Key-ஐச் சரிபார்க்குங்கள்:** Uppercase எழுத்துகள், எண்கள், மற்றும் underscores மட்டுமே பயன்படுத்துங்கள்.",
      "**மூலத்தைத் தேர்வுசெய்யுங்கள்:** உருவாக்கப்படும் values-க்கு **Range** பயன்படுத்துங்கள்; external identifiers auto-generation-ஐ முடக்கும்.",
      "**உருவாக்க நேரத்தை அமைக்குங்கள்:** Task creation, task start, அல்லது கட்டமைக்கப்பட்ட Routing step-இல் generate செய்யுங்கள்; value மீண்டும் பயன்படுத்தக்கூடாதபோது uniqueness-ஐ இயக்குங்கள்.",
      "**சேமித்து கிடைக்கும் தன்மையைச் சரிபார்க்குங்கள்:** வரைபடத்தைச் சேமித்து, திட்டமிடப்பட்ட Work Order அளவுக்குப் போதுமான பயன்படுத்தப்படாத மதிப்புகள் உள்ளன என்பதை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "create-work-order": guide("Manufacturing → Production → Work Orders", [
    "**Work Orders-ஐத் திறங்கள்:** **Production**-ஐத் திறந்து **Work Orders**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு ஆர்டரைத் தொடங்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுங்கள்.",
    "**தேவையைத் தேர்ந்தெடுங்கள்:** பயன்படுத்தப்படும்போது Production Order-ஐத் தேர்ந்தெடுத்து, பின்னர் Client, Product, மற்றும் Variant-ஐத் தேர்ந்தெடுங்கள்.",
    "**செயலாக்க விவரங்களை உள்ளிடுங்கள்:** தனித்துவமான பெயர், அளவு, முன்னுரிமை, எதிர்கால நிறைவு தேதி, மற்றும் குறைந்தது ஒரு Shift-ஐ முடிக்குங்கள்.",
    "**அட்டவணையைச் சரிபார்க்குங்கள்:** Quantity positive whole number ஆகவும் due date கடந்த காலத்தில் இல்லாமலும் இருக்க வேண்டும்; start செய்வதற்கு குறைந்தது ஒரு active Shift தேவை.",
    "**தயார்நிலையை மதிப்பாய்வு செய்யுங்கள்:** Product-க்கு active BOM, active Routing, மற்றும் eligible Line assignment உள்ளதை உறுதிப்படுத்துங்கள். Inventory shortfall இருந்தாலும் creation அனுமதிக்கப்படும்; release-க்கு முன் தீர்க்க வேண்டும்.",
    "**ஆர்டரை உருவாக்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுத்து, தொடக்கப் பயணத்தைத் தொடர புதிய பதிவைத் திறங்கள்.",
  ]),
  "generate-unit-serials": guide(
    "Manufacturing → Production → Work Orders → Work Order detail",
    [
      "**Work Order-ஐத் திறங்கள்:** Work Orders பட்டியலைத் தேடி வரைவு Work Order-ஐத் தேர்ந்தெடுங்கள்.",
      "**தொடக்கப் பயணத்தைத் திறங்கள்:** **Start**, **Prepare**, அல்லது கிடைக்கும் உற்பத்தி-தொடக்கச் செயலைத் தேர்ந்தெடுங்கள்.",
      "**சீரியல்களை உருவாக்குங்கள்:** **Serial Numbers**-ஐத் திறந்து, கட்டமைக்கப்பட்ட Product template அல்லது ஆதரிக்கப்படும் முறையைப் பயன்படுத்தி **Generate**-ஐத் தேர்ந்தெடுங்கள்.",
      "**batch-ஐ மதிப்பாய்வு செய்யுங்கள்:** ஒவ்வொரு proposed value-க்கும் uniqueness validation செய்து invalid duplicates-ஐ அகற்றி batch-ஐ உருவாக்குங்கள்.",
      "**batch-ஐ உறுதிப்படுத்துங்கள்:** Generated serials batch confirm செய்யப்படும் வரை பயன்படுத்த முடியாது.",
      "**அளவைப் பொருத்துங்கள்:** உறுதிப்படுத்தப்பட்ட சீரியல் எண்ணிக்கை இறுதி Work Order அளவுக்கு சரியாகச் சமமாக இருப்பதைச் சரிபார்க்குங்கள்.",
    ],
  ),
  "capacity-and-routing": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**முதலில் serials-ஐ உறுதிப்படுத்துங்கள்:** Line capacity allocation அல்லது Routing selection-க்கு முன் unit-serial batch-ஐ confirm செய்யுங்கள்.",
      "**Capacity and Lines-ஐத் திறங்கள்:** வரைவு Work Order-இன் தொடக்கப் பயணத்தைத் திறந்து **Capacity and Lines**-ஐத் தேர்ந்தெடுங்கள்.",
      "**தகுதியான Lines-ஐ மதிப்பாய்வு செய்யுங்கள்:** Starting Lines-இல் தற்போதைய task சுமையையும் கிடைக்கும் இடத்தையும் ஒப்பிடுங்கள்.",
      "**ஒதுக்கீட்டு முறையைத் தேர்வுசெய்யுங்கள்:** தானியங்கு சமநிலைப்படுத்தலைத் தேர்ந்தெடுங்கள் அல்லது கைமுறை ஒதுக்கீட்டைத் தேர்வுசெய்யுங்கள்.",
      "**கைமுறை ஒதுக்கீடுகளை முடியுங்கள்:** கைமுறை முறை பயன்படுத்தப்படும்போது, முழு அளவும் ஒதுக்கப்படும் வரை **Add Line Assignment**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Routing-ஐத் தேர்ந்தெடுங்கள்:** தேர்ந்தெடுக்கப்பட்ட Product மற்றும் Variant-ஐ cover செய்யும் active Routing-ஐத் தேர்ந்தெடுத்து, plan-ஐ save செய்து inventory, identifier, மற்றும் Station blockers-ஐ மதிப்பாய்வு செய்யுங்கள்.",
    ],
  ),
  "pre-start-validation": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**Pre-start validation-ஐத் திறங்கள்:** தயார் செய்யப்பட்ட Work Order-ஐத் திறந்து சரிபார்ப்புப் படியைத் தேர்ந்தெடுங்கள்.",
      "**சரிபார்ப்பை இயக்குங்கள்:** சீரியல்கள், Line திறன், மற்றும் Routing முடிந்த பிறகு **Validate**-ஐத் தேர்ந்தெடுங்கள்.",
      "**தடைகளைத் தீர்க்குங்கள்:** தோல்வியுற்ற ஒவ்வொரு சரிபார்ப்பையும் திறந்து Product, BOM, serial, அடையாளங்காட்டி, இருப்பு, அல்லது திறன் தரவைச் சரிசெய்யுங்கள்.",
      "**சரிபார்ப்புகளை மீண்டும் இயக்குங்கள்:** தடுக்கும் முடிவு எதுவும் இல்லாத வரை **Validate**-ஐ மீண்டும் தேர்ந்தெடுங்கள்.",
      "**உற்பத்தியை வெளியிடுங்கள்:** எச்சரிக்கைகளை மதிப்பாய்வு செய்து, பின்னர் **Release Work Order**-ஐத் தேர்ந்தெடுத்து செயலை உறுதிப்படுத்துங்கள்.",
    ],
  ),
  "production-tasks": guide("Manufacturing → Production → Production Tasks", [
    "**Production Tasks-ஐத் திறங்கள்:** **Production**-ஐத் திறந்து **Production Tasks**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு அலகைக் கண்டறியுங்கள்:** முடிக்கப்பட்ட-அலகு சீரியல், Work Order, Product, Line, அல்லது நிலை மூலம் தேடுங்கள்.",
    "**Task-ஐத் திறங்கள்:** அதன் தற்போதைய operation, ஒதுக்கப்பட்ட Line, Station, மற்றும் Routing நிலையைப் பார்க்க task-ஐத் தேர்ந்தெடுங்கள்.",
    "**நிலையையும் வரலாற்றையும் மதிப்பாய்வு செய்யுங்கள்:** முடிக்கப்பட்ட மற்றும் நிலுவை operations-ஐப் பார்க்க நிலை விவரங்களையும் Route Logs-ஐயும் திறங்கள்.",
    "**செல்லுபடியாகும் செயலை எடுங்கள்:** தற்போதைய நிலையின் அடிப்படையில் கிடைக்கும் start, hold, repair, reassign, அல்லது நிறைவுச் செயலைப் பயன்படுத்துங்கள்.",
  ]),
  "operator-flow": guide("Manufacturing → Station work area", [
    "**Station வேலைப் பகுதியைத் திறங்கள்:** operator-இன் Station-ஐத் தேர்ந்தெடுத்து முடிக்கப்பட்ட-அலகு சீரியலை ஸ்கேன் செய்யுங்கள் அல்லது உள்ளிடுங்கள்.",
    "**operation-ஐ மதிப்பாய்வு செய்யுங்கள்:** வழிமுறைகள், தேவையான Components, tools, மற்றும் தர gates-ஐ படியுங்கள்.",
    "**உள்ளீடுகளைப் பிடியுங்கள்:** ஒவ்வொரு serialised Component-ஐயும் ஸ்கேன் செய்து மொத்த Components-க்கு சரியான அளவை உள்ளிடுங்கள்.",
    "**முடிவைப் பதிவு செய்யுங்கள்:** தேவையான சரிபார்ப்புகளை முடித்து pass, fail, hold, அல்லது repair விளைவைத் தேர்ந்தெடுங்கள்.",
    "**operation-ஐ முடியுங்கள்:** Fynd ERP Route Log-ஐப் பதிவு செய்து அலகை அதன் அடுத்த செல்லுபடியாகும் படிக்கு நகர்த்தும் வகையில் **Complete**-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  "material-consumption": guide(
    "Manufacturing → Station work area → Current operation",
    [
      "**அலகைத் திறங்கள்:** Station வேலைப் பகுதியில், முடிக்கப்பட்ட-அலகு சீரியலை ஸ்கேன் செய்து தற்போதைய operation-ஐத் திறங்கள்.",
      "**Materials-ஐத் திறங்கள்:** Components அல்லது பொருள்-நுகர்வுப் பகுதியைத் தேர்ந்தெடுங்கள்.",
      "**serialised பொருளை ஸ்கேன் செய்யுங்கள்:** தேவையான ஒவ்வொரு Component சீரியலையும் ஸ்கேன் செய்து பொருந்திய Component-ஐச் சரிபார்க்குங்கள்.",
      "**மொத்த அளவுகளை உள்ளிடுங்கள்:** lot அல்லது இருப்பிடத்தைத் தேர்ந்தெடுத்து serialised அல்லாத பொருளுக்கு நுகரப்பட்ட அளவை உள்ளிடுங்கள்.",
      "**operation-ஐ முடியுங்கள்:** பிடிக்கப்பட்ட பொருளை மதிப்பாய்வு செய்து நுகர்வையும் genealogy-ஐயும் எழுத **Complete**-ஐத் தேர்ந்தெடுங்கள்.",
    ],
  ),
  "statuses-and-route-logs": guide(
    "Manufacturing → Production → Work Orders or Production Tasks",
    [
      "**பதிவைக் கண்டறியுங்கள்:** Work Order அல்லது Production Task-ஐத் தேடி அதைத் திறங்கள்.",
      "**தற்போதைய நிலையை மதிப்பாய்வு செய்யுங்கள்:** நிலை chip-ஐயும் தற்போதைய Routing operation-ஐயும் சரிபார்க்குங்கள்.",
      "**Route Logs-ஐத் திறங்கள்:** வரலாறு, timeline, அல்லது **Route Logs** தாவலைத் தேர்ந்தெடுங்கள்.",
      "**ஒரு நிகழ்வை ஆய்வு செய்யுங்கள்:** Station, operator, முடிவு, timestamps, Components, மற்றும் விதிவிலக்குகளை மதிப்பாய்வு செய்ய ஒரு உள்ளீட்டைத் திறங்கள்.",
      "**வடிகட்டுங்கள் அல்லது export செய்யுங்கள்:** கிடைக்கும் வடிகட்டிகளைப் பயன்படுத்துங்கள் அல்லது விசாரணைக்குத் தேவைப்படும்போது வரலாற்றை export செய்யுங்கள்.",
    ],
  ),
  "quality-controls": guide("Manufacturing → Quality → Control Points", [
    "**Control Points-ஐத் திறங்கள்:** **Quality**-ஐத் திறந்து **Control Points**-ஐத் தேர்ந்தெடுங்கள்.",
    "**கட்டுப்பாட்டை உருவாக்குங்கள்:** Inspection name மற்றும் தேவையான **Control Type**, **Frequency**, **Failure Action**-ஐ உள்ளிடுங்கள்.",
    "**Scope-ஐத் தேர்ந்தெடுங்கள்:** Control-ஐ Product, production Line, Station, அல்லது Routing operation-உடன் இணைக்குங்கள்.",
    "**விளைவுகளை வரையறுங்கள்:** அளவிடக்கூடிய pass criteria மற்றும் quarantine அல்லது automatic Hold போன்ற failure behavior-ஐ அமைக்குங்கள்.",
    "**சேமித்து சோதியுங்கள்:** கட்டுப்பாட்டைச் சேமித்து, அது தோன்றுவதை உறுதிப்படுத்த operation வழியாக ஒரு சிறிய அலகை இயக்குங்கள்.",
  ]),
  "inspection-to-capa": guide("Manufacturing → Quality", [
    "**Inspection-ஐ உருவாக்குங்கள்:** **Quality Inspections**-ஐத் திறந்து production source-இலிருந்து Inspection-ஐத் தொடங்குங்கள்.",
    "**செல்லுபடியாகும் production-ஐத் தேர்ந்தெடுங்கள்:** Started Work Order அல்லது valid lot-ஐத் தேர்ந்தெடுத்து affected quantity-ஐ உள்ளிடுங்கள்.",
    "**பிரச்சினையைப் பதிவு செய்யுங்கள்:** Failure-இல் symptom, severity, source, evidence, மற்றும் affected unit உடன் **Defect**-ஐ உருவாக்குங்கள் அல்லது இணைக்குங்கள்.",
    "**வெளியீட்டைக் கட்டுப்படுத்துங்கள்:** **NCR Reports**-இல் non-conformance-ஐ பதிவு செய்து Disposition-ஐ நிர்ணயிக்குங்கள்.",
    "**தேவைப்பட்டால் escalate செய்யுங்கள்:** **CAPA**-இல் corrective அல்லது preventive action-ஐ assign செய்து verification வரை track செய்யுங்கள்.",
  ]),
  "repair-and-rework": guide("Manufacturing → Repair & Rework", [
    "**முடிவைப் பதிவு செய்யுங்கள்:** **Quality → Dispositions**-ஐத் திறந்து affected record-க்கு தேவையான rationale மற்றும் action-ஐ உள்ளிடுங்கள்.",
    "**மூல இணைப்பைப் பாதுகாக்குங்கள்:** Original serial, Defect, மற்றும் Disposition ஒன்றோடொன்று இணைந்திருப்பதை உறுதிப்படுத்துங்கள்.",
    "**Rework Board-ஐத் திறங்கள்:** **Repair & Rework → Rework Board**-இல் tracked Rework job அல்லது Work Order-ஐ உருவாக்குங்கள்.",
    "**வேலையைப் பதிவு செய்யுங்கள்:** Symptoms, diagnosis, repair/rework actions, மற்றும் தேவையான replacement Components-ஐ உள்ளிடுங்கள்.",
    "**மீண்டும் ஆய்வு செய்து மூடுங்கள்:** Allowed Routing point-க்கு அனுப்புவதற்கு அல்லது job-ஐ close செய்வதற்கு முன் required reinspection-ஐ முடிக்குங்கள்.",
  ]),
  "hold-scrap-teardown": guide("Manufacturing → Quality or Scrap & Teardown", [
    "**பாதிக்கப்பட்ட அலகைத் திறங்கள்:** Production Task, தரப் பதிவு, அல்லது பொருள் பதிவைக் கண்டறியுங்கள்.",
    "**விதிவிலக்கைத் தேர்வுசெய்யுங்கள்:** அங்கீகரிக்கப்பட்ட முடிவின்படி **Hold**, **Scrap**, அல்லது **Teardown**-ஐத் தேர்ந்தெடுங்கள்.",
    "**காரணத்தை உள்ளிடுங்கள்:** கட்டமைக்கப்பட்ட காரணத்தைத் தேர்ந்தெடுத்து குறிப்புகள், சான்று, பாதிக்கப்பட்ட அளவு, மற்றும் உரிமையைச் சேர்க்குங்கள்.",
    "**செயலை உறுதிப்படுத்துங்கள்:** மீளமுடியாத தாக்கத்தை மதிப்பாய்வு செய்யுங்கள்; Scrap approval மற்றும் execution states வழியாக நகரும்.",
    "**தொடர்நடவடிக்கையை முடிக்குங்கள்:** தீர்வுக்குப் பிறகே Hold-ஐ Release செய்யுங்கள். Executed Scrap dispatch ஆன பின் Teardown கிடைக்கும்; recovered Components-ஐ donor-unit context உடன் பதிவு செய்யுங்கள்.",
  ]),
  packaging: guide("Manufacturing → Packaging & Shipping → Packaging", [
    "**Packaging-ஐத் திறங்கள்:** **Packaging & Shipping**-ஐத் திறந்து **Packaging**-ஐத் தேர்ந்தெடுங்கள்.",
    "**ஒரு கொள்கலனைத் தொடங்குங்கள் அல்லது கண்டறியுங்கள்:** ஏற்கனவே உள்ள ஒரு கொள்கலனை ஸ்கேன் செய்யுங்கள் அல்லது சரியான Container Type-ஐப் பயன்படுத்தி ஒன்றை உருவாக்கும் செயலைத் தேர்ந்தெடுங்கள்.",
    "**முடிக்கப்பட்ட அலகுகளைச் சேர்க்குங்கள்:** தகுதியான ஒவ்வொரு முடிக்கப்பட்ட-அலகு சீரியலையும் கொள்கலனுக்குள் ஸ்கேன் செய்யுங்கள்.",
    "**சரிபார்ப்புகளை இயக்குங்கள்:** Configured Container Type, quantity, weight, declarations, மற்றும் label verification-ஐ முடிக்குங்கள்.",
    "**கொள்கலனை மூடுங்கள்:** எல்லா configured checks pass ஆகும் வரை container-ஐ open ஆக வைத்திருந்து, பின்னர் label print செய்து close அல்லது complete action-ஐத் தேர்ந்தெடுங்கள்.",
  ]),
  "containers-and-labels": guide("Manufacturing → Packaging & Shipping", [
    "**Packaging configuration-ஐத் திறங்கள்:** Product-க்கான Container Types, packaging rules, மற்றும் label templates-ஐத் திறங்கள்.",
    "**Hierarchy-ஐ அமைக்குங்கள்:** Unit, box, carton, pallet போன்ற அனுமதிக்கப்பட்ட leaf-to-parent வரிசையை அமைக்குங்கள்.",
    "**அடையாளங்களை இணைக்குங்கள்:** Leaf container finished-unit serial-ஐ bind செய்யும்; ஒவ்வொரு parent-மும் configured child UID-ஐ மட்டுமே ஏற்கும்.",
    "**Label-ஐ உருவாக்குங்கள்:** Product, unit, container, quantity, மற்றும் shipment scanning-க்கு தேவையான template variables-ஐச் சேர்க்குங்கள்.",
    "**சோதித்து audit செய்யுங்கள்:** Test label print செய்து label history மற்றும் reprints traceable ஆக இருப்பதை உறுதிப்படுத்துங்கள்.",
  ]),
  "shipment-verification": guide(
    "Manufacturing → Packaging & Shipping → Shipment Verification",
    [
      "**Shipment Verification-ஐத் திறங்கள்:** **Packaging & Shipping**-ஐத் திறந்து **Shipment Verification**-ஐத் தேர்ந்தெடுங்கள்.",
      "**முதலில் Shipment-ஐத் தேர்ந்தெடுங்கள்:** Shipment தேர்ந்தெடுக்கப்படும் வரை verification தொடங்காது; அதுவரை **Container Type** கிடைக்காது.",
      "**Container Type-ஐத் தேர்ந்தெடுத்து verify செய்யுங்கள்:** Expected container UID-களை scan செய்து Verified, Mismatched, Pending counts-ஐ மதிப்பாய்வு செய்யுங்கள்.",
      "**விதிகளை மதிப்பாய்வு செய்யுங்கள்:** Active Shipment Rule container count மற்றும் weight-ஐ அனுமதிக்கிறதா, Shipping Gate-இல் போதுமான approved PO quantity உள்ளதா என உறுதிப்படுத்துங்கள்.",
      "**வேறுபாடுகளைத் தீர்க்குங்கள்:** Completion-க்கு முன் mismatches-ஐ சரிசெய்து, export தேவைப்பட்டால் client-specific ASN template-ஐப் பயன்படுத்துங்கள்.",
    ],
  ),
  "traceability-genealogy-recall": guide(
    "Manufacturing → Traceability → Master Traceability",
    [
      "**Master Traceability-ஐத் திறங்கள்:** **Traceability**-ஐத் திறந்து **Master Traceability**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Dossier scope-ஐ அமைக்குங்கள்:** Filters-ஐ combine செய்யுங்கள் அல்லது identifier list paste செய்யுங்கள்; identifier list மற்ற scope filters-ஐ override செய்யும்.",
      "**Report sheets-ஐத் தேர்ந்தெடுங்கள்:** தேவையான unit, route, quality, genealogy, packaging, shipment, அல்லது audit sheets-ஐத் தேர்ந்தெடுத்து dossier-ஐ generate செய்யுங்கள்.",
      "**Stage Timeline-ஐ சரியாகப் பயன்படுத்துங்கள்:** Start/end dates, குறைந்தது ஒரு Work Order, மற்றும் 1–50 Operations-ஐத் தேர்ந்தெடுங்கள்.",
      "**Genealogy-ஐப் பின்தொடருங்கள்:** **Batch Genealogy**-இல் upstream/downstream search செய்யுங்கள் அல்லது material lot/Component-க்கு **Find Affected Units** பயன்படுத்துங்கள்.",
      "**தேவைப்பட்டால் containment தொடங்குங்கள்:** **Recall Notices**-இல் severity, status, reason, மற்றும் affected-unit population-ஐப் பதிவு செய்யுங்கள்.",
    ],
  ),
  dashboards: guide(
    "Manufacturing → Dashboard, Work Orders, Production Tasks, and Route Logs",
    [
      "**Plant dashboard-ஐ மதிப்பாய்வு செய்யுங்கள்:** Current Plant-க்கான readiness, active Work Orders, Stations, Products, மற்றும் targets-ஐப் பாருங்கள்.",
      "**Work Orders-ஐத் திறங்கள்:** Schedule risk-ஐ கண்டறிய status, priority, மற்றும் due date-ஐ மதிப்பாய்வு செய்யுங்கள்.",
      "**Production Tasks-ஐத் திறங்கள்:** Serial மூலம் தேடி Product, Routing, assigned Line, மற்றும் task status-ஐப் பாருங்கள்.",
      "**Route Logs-ஐத் திறங்கள்:** Operator, Station, Line, timestamp, மற்றும் quality result உட்பட execution evidence-ஐ உறுதிப்படுத்துங்கள்.",
      "**Source record-ஐ விசாரியுங்கள்:** Corrective action-க்கு முன் underlying Work Order, Task, அல்லது Route Log-ஐத் திறங்கள்.",
    ],
  ),
  "shift-operations": guide("Manufacturing → Shifts & Labor", [
    "**Shift Definitions-ஐ மதிப்பாய்வு செய்யுங்கள்:** Timing, breaks, மற்றும் calculated net working duration-ஐ உறுதிப்படுத்துங்கள்.",
    "**Shift Schedules-ஐ மதிப்பாய்வு செய்யுங்கள்:** Effective dates மற்றும் weekly pattern-ஐ அமைத்து, தயாரானபோது Schedule-ஐ activate செய்யுங்கள்; புதிய Schedules முதலில் Draft ஆக இருக்கும்.",
    "**Handover-ஐ உருவாக்குங்கள்:** **Shift Handovers**-இல் date, Shift, Line, outgoing operator, incoming operator, status, மற்றும் notes-ஐ உள்ளிடுங்கள்.",
    "**தற்போதைய நிலையைப் பதிவு செய்யுங்கள்:** WIP, holds, downtime, material risk, quality issues, மற்றும் unresolved actions-ஐச் சேர்க்குங்கள்.",
    "**Break Compliance-ஐச் சரிபார்க்குங்கள்:** Planned/actual duration, violations, மற்றும் compliance-ஐ பாருங்கள்; filtered results இருந்தால் மட்டுமே export கிடைக்கும்.",
  ]),
  "tools-and-maintenance": guide(
    "Manufacturing → Process & Engineering → Tools and Equipments",
    [
      "**Tools-ஐத் திறங்கள்:** **Process & Engineering → Tools and Equipments**-ஐத் திறந்து **Tools**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Tool-ஐ உருவாக்குங்கள் அல்லது கண்டறியுங்கள்:** உருவாக்கச் செயலைத் தேர்ந்தெடுங்கள் அல்லது ஏற்கனவே உள்ள Tool பதிவைத் தேடுங்கள்.",
      "**Control details-ஐ மதிப்பாய்வு செய்யுங்கள்:** Identity, manufacturer/model, category, assigned Station, மற்றும் availability status-ஐ உறுதிப்படுத்துங்கள்.",
      "**Maintenance Alerts-ஐ மதிப்பாய்வு செய்யுங்கள்:** Priority, owner, affected Tool/equipment, Line, மற்றும் status-ஐப் பார்த்து தேவைப்பட்டால் maintenance check trigger செய்யுங்கள்.",
      "**Maintenance Work Orders-ஐப் பயன்படுத்துங்கள்:** Maintenance type, priority, assigned owner, scheduled start, மற்றும் completion status-ஐ track செய்யுங்கள்.",
      "**Production-ஐ பாதுகாக்குங்கள்:** Availability அல்லது maintenance state பொருத்தமில்லாதபோது Tool-ஐ execution-க்கு பயன்படுத்தாதீர்கள்.",
    ],
  ),
  "reports-and-audit": guide(
    "Traceability → Master Traceability; Production → Work Orders",
    [
      "**Traceability report-ஐ உருவாக்குங்கள்:** **Master Traceability**-இல் required scope மற்றும் investigation-க்கு தேவையான dossier sheets-ஐத் தேர்ந்தெடுங்கள்.",
      "**Dossier-ஐ generate செய்யுங்கள்:** Unit, route, quality, genealogy, identifier, tool, packaging, மற்றும் shipment evidence-ஐ மதிப்பாய்வு செய்யுங்கள்.",
      "**Operational records-ஐ export செய்யுங்கள்:** **Work Orders**-இல் filters-ஐ வைத்திருந்து **Export Work Orders**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Change history-ஐத் திறங்கள்:** Entity-இன் Recent Changes history-ஐ பார்க்க **View all changes**-ஐத் தேர்ந்தெடுங்கள்.",
      "**Evidence-ஐ மதிப்பாய்வு செய்யுங்கள்:** Actor, action, entity, changed fields, மற்றும் timestamp-ஐ உறுதிப்படுத்தி affected record-க்கு திரும்புங்கள்.",
    ],
  ),
  "first-production-run": guide("Manufacturing → Production → Work Orders", [
    "**ஒரு சோதனை Work Order-ஐ உருவாக்குங்கள்:** **Create Work Order**-ஐத் தேர்ந்தெடுத்து ஒரு சிறிய ஆனால் யதார்த்தமான அளவைப் பயன்படுத்துங்கள்.",
    "**தயார் செய்து வெளியிடுங்கள்:** சீரியல்கள், திறன், Routing, பொருள், மற்றும் அடையாளங்காட்டிகளை உறுதிப்படுத்தி, பின்னர் **Release Work Order**-ஐத் தேர்ந்தெடுங்கள்.",
    "**சாதாரண பாதையை இயக்குங்கள்:** குறைந்தது ஒரு அலகை ஒவ்வொரு தேவையான operation வழியாகவும் முடிக்குங்கள்.",
    "**ஒரு விதிவிலக்கைச் சோதியுங்கள்:** ஒரு கட்டுப்படுத்தப்பட்ட operation-ஐ தோல்வியடையச் செய்து அதன் Repair அல்லது Rework பாதையை முடிக்குங்கள்.",
    "**முடித்து கண்காணியுங்கள்:** பொருந்தும் தரம், packaging, மற்றும் shipment படிகளை முடித்து, பின்னர் **Master Traceability**-இல் அலகைத் தேடுங்கள்.",
  ]),
  troubleshooting: guide("The affected Fynd ERP module", [
    "**தோல்வியுற்ற பதிவைத் திறங்கள்:** பிழையைக் காட்டும் Product, Routing, Work Order, Production Task, அல்லது shipment-க்குத் திரும்புங்கள்.",
    "**சரிபார்ப்புச் செய்தியைப் படியுங்கள்:** தோல்வியுற்ற சரிபார்ப்பை விரிவுபடுத்தி, சரியான இல்லாத புலம், உறவு, நிலை, அல்லது அளவைக் குறித்துக்கொள்ளுங்கள்.",
    "**முன்நிபந்தனைகளைச் சரிபார்க்குங்கள்:** பொருந்தும்படி செயலில் உள்ள BOM, Stations, Repair Stations, Shift, Line ஒதுக்கீடு, திறன், சீரியல்கள், இருப்பு, மற்றும் அடையாளங்காட்டிகளைச் சரிபார்க்குங்கள்.",
    "**மூலப் பதிவைச் சரிசெய்யுங்கள்:** இணைக்கப்பட்ட கட்டமைப்பைத் திறந்து, தேவையான மாற்றத்தைச் செய்து, **Save**-ஐத் தேர்ந்தெடுங்கள்.",
    "**செயலை மீண்டும் முயற்சியுங்கள்:** அசல் பதிவுக்குத் திரும்பி **Validate**, **Create**, **Release**, அல்லது **Complete**-ஐ மீண்டும் தேர்ந்தெடுங்கள்.",
  ]),
};

export function getForgeTaskGuide(slug: string): ForgeTaskGuide | undefined {
  return TASK_GUIDES_TA[slug];
}
