import type { ForgeTaskGuide } from "./forge-task-guides";

const guide = (navigationPath: string, steps: string[]): ForgeTaskGuide => ({
  navigationPath,
  steps,
});

export const TASK_GUIDES_TE: Record<string, ForgeTaskGuide> = {
  "complete-setup-journey": guide("Fynd ERP Dashboard", [
    "**Manufacturing journey తెరవండి:** మీ process‌కు అవసరమైన క్రమంలో Production, Process & Engineering, Quality, మరియు తరువాతి manufacturing modules ద్వారా పని చేయడానికి ఎడమ navigation ఉపయోగించండి.",
    "**Factory రికార్డులను సృష్టించండి:** Sites, Lines, operation Stations, Repair Stations, మరియు Shift Definitions సృష్టించండి.",
    "**Product రికార్డులను సృష్టించండి:** Project, Product Family, Components, Product, Variants, మరియు BOM Version సృష్టించండి.",
    "**Execution కోసం సిద్ధం చేయండి:** BOM ను activate చేసి, Routing ను సృష్టించి validate చేసి, Product ను eligible Lines కు assign చేయండి.",
    "**ఒక trial order ప్రారంభించండి:** ఒక చిన్న Work Order సృష్టించి, unit serials నిర్ధారించి, capacity మరియు Routing ఎంచుకుని, validation రన్ చేసి, Release ఎంచుకోండి.",
  ]),
  sites: guide("Masters → Sites", [
    "**Sites తెరవండి:** Fynd ERP ఎడమ నావిగేషన్‌లో **Masters** తెరిచి **Sites** ఎంచుకోండి.",
    "**కొత్త రికార్డు ప్రారంభించండి:** కుడి పైభాగంలో ఉన్న **Create Site** ఎంచుకోండి.",
    "**Creation method ఎంచుకోండి:** Form ను మీరే పూర్తి చేయడానికి **Create Manually** ఎంచుకోండి; prompt నుంచి వివరాల draft కావాలంటే AI-assisted option ఉపయోగించవచ్చు.",
    "**అవసరమైన identity నమోదు చేయండి:** **Name** మరియు **Code** తప్పనిసరి. Code లో అక్షరాలు, సంఖ్యలు, మరియు hyphen మాత్రమే అనుమతించబడతాయి.",
    "**అవసరమైతే location వివరాలు జోడించండి:** Address fields optional. **State / Province / Region** కంటే ముందు **Country** ఎంచుకోండి; ఎంచుకున్న location ఆధారంగా City values filter అవుతాయి.",
    "**Optional metadata జాగ్రత్తగా జోడించండి:** Metadata 32 KB పరిమితిలో ఉండాలి; search లేదా grouping కు ఉపయోగపడితే మాత్రమే tags జోడించండి.",
    "**సృష్టించి తనిఖీ చేయండి:** **Create** ఎంచుకుని, కొత్త Site జాబితాలో కనిపిస్తోందని మరియు Station సృష్టించేటప్పుడు దాన్ని ఎంచుకోగలమని నిర్ధారించండి.",
  ]),
  lines: guide("Mfg → Process & Engineering → Line", [
    "**Lines తెరవండి:** **Mfg** తెరిచి, **Process & Engineering** విస్తరించి, **Line** ఎంచుకోండి.",
    "**కొత్త line ప్రారంభించండి:** కుడి పైభాగంలో ఉన్న **Create Line** ఎంచుకోండి.",
    "**Creation method ఎంచుకోండి:** Form ను పూర్తి చేయడానికి **Create Manually** ఎంచుకోండి; prompt నుంచి Line draft చేయడానికి AI-assisted option ఉపయోగించవచ్చు.",
    "**అవసరమైన వివరాలు నమోదు చేయండి:** **Name**, **Code**, మరియు **Line Type** తప్పనిసరి. **Site** optional; Line ఒక నిర్దిష్ట location కు చెందినప్పుడు దాన్ని ఎంచుకోండి.",
    "**Capacity సెట్ చేయండి:** **Capacity Per Shift**, **Capacity Per Hour** కంటే ఎక్కువగా ఉండాలి; **Task Queue Capacity** 1 నుండి 100,000 మధ్య పూర్తి సంఖ్యగా ఉండాలి.",
    "**ప్రారంభ ప్రవర్తనను ఎంచుకోండి:** Capacity planning లో ఈ Line initial task assignment పొందగలిగినప్పుడు మాత్రమే **Is Starting Line** ఆన్ చేయండి. Eligible SMT మరియు BLT starting Lines కోసం form ఈ behavior ను నిర్ధారిస్తుంది.",
    "**Line సృష్టించండి:** Line ను active గా ఉంచి విలువలను సమీక్షించి **Create** ఎంచుకోండి. కొత్త Line దాని Site, type, status, మరియు hourly capacity తో జాబితాలో కనిపిస్తుందని నిర్ధారించండి.",
  ]),
  "stations-and-repair-stations": guide(
    "Mfg → Process & Engineering → Stations",
    [
      "**Stations తెరవండి:** **Mfg** తెరిచి, **Process & Engineering** విస్తరించి, **Stations** ఎంచుకోండి.",
      "**Station ప్రారంభించండి:** **Create Station** ఎంచుకుని **Create Manually** ఎంచుకోండి; AI-assisted option తో record draft చేయవచ్చు.",
      "**అవసరమైన వివరాలు నమోదు చేయండి:** **Station Name**, **Station Code**, **Site Location**, మరియు **Station Category** తప్పనిసరి.",
      "**Station ను classify చేయండి:** **Station Type** దాని production behavior ను నియంత్రిస్తుంది; **Station Category** production ఉపయోగం కోసం దాన్ని నిర్వహిస్తుంది. New Stations default గా **Idle** మరియు **Regular** ఉంటాయి.",
      "**Operation Station సృష్టించండి:** SMT placement Station కోసం Assembly Site మరియు category ఎంచుకుని **Create Station** ఎంచుకోండి.",
      "**Repair Station సృష్టించండి:** Flow ను మళ్లీ చేసి **Station Type** మరియు **Station Category** రెండింటినీ **Repair** గా సెట్ చేయండి.",
      "**రెండు records ను verify చేయండి:** Regular Assembly Station మరియు Repair Station సరైన Site, type, category, మరియు Idle status తో జాబితాలో ఉన్నాయని నిర్ధారించండి.",
    ],
  ),
  shifts: guide("Mfg → Shifts & Labor → Shift Definitions", [
    "**Shift Definitions తెరవండి:** **Mfg** తెరిచి, **Shifts & Labor** విస్తరించి, **Shift Definitions** ఎంచుకోండి.",
    "**Shift ప్రారంభించండి:** **Create Shift** ఎంచుకుని **Create Manually** ఎంచుకోండి; AI-assisted option తో schedule draft చేయవచ్చు.",
    "**అవసరమైన schedule నమోదు చేయండి:** **Shift Name**, **Code**, **Shift Type**, **Start Time**, మరియు **End Time** తప్పనిసరి. Code లో uppercase అక్షరాలు, సంఖ్యలు, మరియు hyphen మాత్రమే అనుమతించబడతాయి.",
    "**సరైన Shift Type ఉపయోగించండి:** Morning, Afternoon, Night, General, Rotational, లేదా Split ఎంచుకోండి. Selected type కు form సరిపోయే default color ఇస్తుంది.",
    "**Valid times సెట్ చేయండి:** Duration మరియు net working time ఆటోమేటిక్‌గా లెక్కించబడతాయి. Overnight Shifts లో end time తదుపరి రోజుకు వెళ్లవచ్చు.",
    "**Breaks configure చేయండి:** **Add Break** ఎంచుకుని name, type, మరియు కనీసం ఒక నిమిషం duration నమోదు చేయండి. Break start time optional; unpaid breaks net working time ను తగ్గిస్తాయి.",
    "**Create చేసి verify చేయండి:** Shift ను active గా ఉంచి **Create** ఎంచుకుని, overview లో identity, type, timing, net working time, మరియు breaks సరైనవని నిర్ధారించండి.",
  ]),
  "factory-readiness": guide(
    "Manufacturing → Factory setup and Process & Engineering",
    [
      "**Sites తనిఖీ చేయండి:** **Sites** తెరిచి, ప్రతి భౌతిక manufacturing స్థానం ప్రాతినిధ్యం వహించబడిందని నిర్ధారించండి.",
      "**Lines తనిఖీ చేయండి:** **Line** తెరిచి, ఉద్దేశించిన మొదటి production Line కు **Is Starting Line** ప్రారంభించబడిందని నిర్ధారించండి.",
      "**Capacity తనిఖీ చేయండి:** ప్రతి Line తెరిచి, **Task Queue Capacity**, గంటవారీ capacity, మరియు shift capacity సమీక్షించండి.",
      "**Stations తనిఖీ చేయండి:** **Stations** తెరిచి, ప్రతి Routing operation మరియు failure path కు ఒక active Station ఉందని నిర్ధారించండి.",
      "**ఒక చిన్న validation రన్ చేయండి:** factory model, Production Tasks ను స్వీకరించి route చేయగలదని నిర్ధారించడానికి ఒక చిన్న Work Order quantity ఉపయోగించండి.",
    ],
  ),
  "projects-and-product-families": guide("Mfg → Production → Product Families", [
    "**Product Families తెరవండి:** **Mfg** తెరిచి, **Production** విస్తరించి, **Product Families** ఎంచుకోండి.",
    "**List‌ను review చేయండి:** కొత్త Family సృష్టించే ముందు search మరియు filters‌తో ఇప్పటికే ఉందో చూడండి.",
    "**Product Family ప్రారంభించండి:** Available create action ఎంచుకుని required **Name** మరియు **Code** నమోదు చేయండి.",
    "**Classification జోడించండి:** Product group‌కు వర్తిస్తే మాత్రమే Type, Status, Project, లేదా ఇతర context ఎంచుకోండి.",
    "**Create చేసి verify చేయండి:** Product Family‌ను save చేసి code, status, type, Project context, మరియు product count list‌లో సరైందో చూడండి.",
    "**Project context ఉపయోగించండి:** **Mfg → Production** కింద Projects ప్రత్యేక option కనిపించకపోతే, Product Family screen‌లో Project field లేదా linked Project context అందుబాటులో ఉన్నప్పుడు మాత్రమే ఉపయోగించండి.",
  ]),
  components: guide("Masters → Item Master", [
    "**Item Master తెరవండి:** **Masters** తెరిచి **Item Master** ఎంచుకుని, తర్వాత **Add Item** ఎంచుకోండి.",
    "**అవసరమైన identity నమోదు చేయండి:** **Name**, ప్రత్యేకమైన **Code**, మరియు **Unit** పూర్తి చేయండి. Code లో అక్షరాలు, సంఖ్యలు, మరియు hyphens అనుమతించబడతాయి.",
    "**శాశ్వత settings సమీక్షించండి:** Unit, Track by Serial Number, Consumable Component, Fixed Serial, మరియు Track by Non-Serialized create చేసిన తర్వాత మార్చలేరు.",
    "**Tracking configure చేయండి:** **Track by Serial Number** enable చేస్తే Consumable మరియు Fixed Serial disable అవుతాయి. Mixed serial మరియు lot tracking కోసం **Track by Non-Serialized** అదే సమయంలో enabled గా ఉండవచ్చు.",
    "**Stock limits సెట్ చేయండి:** Reorder point maximum stock ను మించకూడదు; minimum stock ను reorder point కు సమంగా లేదా తక్కువగా ఉంచండి.",
    "**Create చేసి verify చేయండి:** **Create Component/Part** ఎంచుకుని code, unit, serialized status, మరియు non-serialized tracking ఉన్న success summary ను సమీక్షించండి.",
    "**మార్చగల details update చేయండి:** **Item Master**-లో material‌ను మళ్లీ తెరిచి, అనుమతించిన identity, stock, supplier, లేదా description fields‌ను అవసరానికి అనుగుణంగా edit చేయండి. Unit మరియు permanent tracking controls creation తర్వాత locked‌గా ఉంటాయి.",
    "**Inventory activity track చేయండి:** Inventory Lots, Serials, Usage History, మరియు సంబంధిత inventory views ద్వారా stock receive చేసి, lot, serial, quantity, మరియు consumption history‌ను అనుసరించండి.",
  ]),
  "products-and-variants": guide("Mfg → Production → Products", [
    "**Products తెరవండి:** **Mfg** తెరిచి **Production** విస్తరించి **Products** ఎంచుకోండి.",
    "**Product ప్రారంభించండి:** **Create Product** ఎంచుకుని **Create Manually** ఎంచుకోండి; AI-assisted option కూడా ఉపయోగించవచ్చు.",
    "**అవసరమైన సమాచారం నమోదు చేయండి:** **Product Name** మరియు ప్రత్యేకమైన **SKU** తప్పనిసరి. Product Description మరియు Product Family optional.",
    "**Batch multiplier సెట్ చేయండి:** Multiplier ఒక batch లో తయారయ్యే units ను నిర్వచిస్తుంది; అది 1 లేదా అంతకంటే ఎక్కువ whole number అయి ఉండాలి.",
    "**అవసరమైతే Variants జోడించండి:** Variants optional. ప్రతి భిన్న configuration కు ప్రత్యేకమైన Variant SKU, Status, మరియు Storage/Color వంటి optional key-value attributes నమోదు చేయండి.",
    "**BOM prerequisite పూర్తి చేయండి:** కనీసం ఒక Shared BOM component జోడించండి లేదా ప్రతి Variant కు BOM జోడించండి. ఈ coverage paths లో ఒకటి లేకుండా Product create చేయలేరు.",
    "**Create చేసి verify చేయండి:** **Create Product** ఎంచుకుని Products list లో Product, SKU, active status, మరియు Variant count నిర్ధారించండి.",
  ]),
  "bill-of-materials": guide(
    "Mfg → Production → Products → Product detail → BOM Versions",
    [
      "**Product తెరవండి:** **Mfg → Production → Products** తెరిచి Product ను కనుగొని **View** ద్వారా details తెరవండి.",
      "**Draft version తెరవండి:** **BOM Versions** కింద **View Version Details** ద్వారా **Initial Version (V1)** తెరవండి. Product creation సమయంలో ఇచ్చిన BOM నుంచి Draft సృష్టించబడిందో నిర్ధారించండి.",
      "**BOM item జోడించండి:** **Add Item** ఎంచుకోండి. Version Draft లో ఉన్నప్పుడు items జోడించవచ్చు.",
      "**Scope ఎంచుకోండి:** అన్ని Variants ఉపయోగించే material కు **Shared** వాడండి. Configuration-specific material కు మాత్రమే Variant BOM ఎంచుకోండి.",
      "**Quantity మరియు unit సెట్ చేయండి:** Quantity కనీసం 1. Production వేరే compatible unit ఉపయోగించినప్పుడు మాత్రమే optional **Unit Override** వాడండి.",
      "**Components ఎంచుకుని జోడించండి:** **Select Components** లేదా **Bulk Upload** ద్వారా Component records ఎంచుకుని **Add Items** ఎంచుకోండి.",
      "**Draft verify చేయండి:** Total Items మరియు Shared/Variant BOM table లో ప్రతి Component, code, tracking type, quantity, మరియు unit కనిపిస్తున్నాయని నిర్ధారించండి.",
    ],
  ),
  "activate-bom": guide(
    "Mfg → Production → Products → Product detail → BOM Versions",
    [
      "**BOM Version తెరవండి:** Product లో production ఉపయోగించాల్సిన Draft version కు **View Version Details** ఎంచుకోండి.",
      "**Draft సమీక్షించండి:** Usage Type, effective dates, Total Items, మరియు Shared/Variant coverage సరైనవని నిర్ధారించండి.",
      "**Version release చేయండి:** **Release** ఎంచుకుని **Release BOM Version** నిర్ధారించండి. Release చేసిన తర్వాత version ను edit చేయలేరు.",
      "**Active-version behavior అర్థం చేసుకోండి:** వేరే active version ప్రభావితం అవుతుందా అని confirmation చూపిస్తుంది. ఈ workflow లో V1 Product యొక్క ఏకైక active BOM version అవుతుంది.",
      "**ఫలితాన్ని verify చేయండి:** Status **Active**, item editing controls తొలగించబడ్డాయి, release audit fields రికార్డయ్యాయి, మరియు **Create Routing** అందుబాటులో ఉందని నిర్ధారించండి.",
    ],
  ),
  "material-tracking": guide(
    "Masters → Item Master → Component detail",
    [
      "**Create చేయడానికి ముందు tracking సెట్ చేయండి:** Track by Serial Number మరియు Track by Non-Serialized Component create చేసిన తర్వాత మార్చలేరు. రెండింటినీ enable చేస్తే inventory lots లో వ్యక్తిగత serial identity లభిస్తుంది.",
      "**Component తెరవండి:** **Masters → Item Master** తెరిచి Component ను కనుగొని details తెరవండి. Tracking Type మరియు **Inventory Lots**, **Serials** tabs నిర్ధారించండి.",
      "**Lot receipt ప్రారంభించండి:** **Inventory Lots** తెరిచి **Add Lot** ఎంచుకుని **Create Manually** లేదా AI-assisted option వాడండి.",
      "**అవసరమైన receipt fields నమోదు చేయండి:** Lot Number, Quantity Received, Vendor, Location Type, మరియు Storage Location తప్పనిసరి. Vendor మరియు destination location ముందే ఉండాలి.",
      "**Lot create చేయండి:** Batch Number, dates, invoice, manufacturer data, notes, dimensions, మరియు metadata optional. Review తర్వాత **Create** ఎంచుకోండి.",
      "**Serialized stock నమోదు చేయండి:** Serialized Component కు serials register చేసే వరకు received quantity available కాదు. **Add Component Serials** లో **Manual Entry** లేదా **Bulk Entry** వాడండి.",
      "**Availability verify చేయండి:** Lot లో received serial count, available quantity, Vendor, మరియు Storage Location నిర్ధారించండి; consumption మరియు genealogy కోసం Usage History ఉపయోగించండి.",
    ],
  ),
  "create-routing": guide("Masters → Products → Product detail → Create Routing", [
    "**Product నుండి ప్రారంభించండి:** Product detail తెరిచి **Create Routing** ఎంచుకోండి. Routing configurator ఆ Product‌ను స్వయంచాలకంగా ఉపయోగిస్తుంది.",
    "**అవసరమైన configuration ఎంచుకోండి:** కనీసం ఒక Variant ఎంచుకుని కొనసాగండి; తరువాత **Active** BOM Version ఎంచుకోండి. Inactive BOM versions ఇక్కడ అందుబాటులో ఉండవు.",
    "**Workflow‌కు పేరు పెట్టండి:** తప్పనిసరి Workflow Name నమోదు చేసి, optional description జోడించి, production‌కు route అందుబాటులో ఉండాలంటే **Active** ఆన్‌లో ఉంచండి.",
    "**Operation జోడించండి:** **Add Stage → Create Manually** ఎంచుకుని main Station ఎంచుకొని unique Operation Name నమోదు చేయండి. Repair Station తప్పనిసరి; అది main Station‌కు భిన్నంగా ఉండాలి.",
    "**BOM‌ను పూర్తిగా cover చేయండి:** **Components** లో అవసరమైన Components మరియు quantities assign చేయండి. రెండు BOM coverage indicators **100%** చేరాలి.",
    "**Connect చేసి validate చేయండి:** Stage save చేసి, అవసరమైతే nodes arrange చేసి, **Start → ప్రతి stage → End** గా connect చేయండి. Editor స్వయంచాలకంగా validate చేసి workflow valid అయిన తర్వాత మాత్రమే **Save** enable చేస్తుంది.",
    "**Creation నిర్ధారించండి:** **Save** ఎంచుకుని workflow summary review చేసి **Confirm & Save** ఎంచుకోండి. Routing detail page లో Active status, Product, Variants, BOM Version, మరియు Workflow Preview నిర్ధారించండి.",
  ]),
  "product-line-assignment": guide(
    "Manufacturing → Production → Products → Product detail → Assigned Lines",
    [
      "**Product తెరవండి:** **Production → Products** తెరిచి, Product ను వెతికి, దానిని ఎంచుకోండి.",
      "**Assigned Lines కనుగొనండి:** **Assigned Lines** విభాగానికి scroll చేయండి. ఈ Product-level section multi-line Work Order execution‌ను enable చేస్తుంది.",
      "**Line assign చేయండి:** **Assign Line** ఎంచుకుని **Select Line** తెరిచి eligible manufacturing Line ఎంచుకొని **Assign** ఎంచుకోండి.",
      "**Availability సరిగ్గా చదవండి:** Selector **Available Lines** మరియు ఇప్పటికే **Assigned to Other Products** అయిన Lines‌ను వేరు చేసి, Line code మరియు Site చూపిస్తుంది.",
      "**చెల్లుబాటు అయ్యే alternatives జోడించండి:** అదే Product‌ను నిజంగా manufacture చేయగల అదనపు Lines కోసం మాత్రమే assignment పునరావృతం చేయండి.",
      "**Table verify చేయండి:** Assigned Line name, code, status, capacity per hour, Site, మరియు actions నిర్ధారించండి. Starting-Line eligibility వేరుగా Line‌లో configure చేయబడుతుంది.",
    ],
  ),
  "starting-lines-and-capacity": guide(
    "Manufacturing → Process & Engineering → Line → Line detail → Edit",
    [
      "**Line తెరవండి:** **Process & Engineering → Line** తెరిచి Line name లేదా code ద్వారా search చేసి, Line detail తెరిచి **Edit** ఎంచుకోండి.",
      "**Throughput సెట్ చేయండి:** **Capacity Per Hour** మరియు **Capacity Per Shift** optional. రెండూ ఇచ్చినప్పుడు Capacity Per Shift, Capacity Per Hour కంటే ఎక్కువగా ఉండాలి.",
      "**Task queue పరిమితం చేయండి:** **Task Queue Capacity** optional; అది Line‌లో అనుమతించే pending మరియు active tasks గరిష్ఠ సంఖ్యను సెట్ చేస్తుంది. విలువ ఇస్తే 1 నుండి 100,000 మధ్య whole number ఉపయోగించండి.",
      "**Starting eligibility సెట్ చేయండి:** Capacity planning‌లో Line initial task పొందవలసినప్పుడు మాత్రమే **Is Starting Line** ఆన్ చేయండి. UI phase order: SMT → BLT → ASSEMBLY → TESTING → PACKING.",
      "**Save చేసి verify చేయండి:** **Save** ఎంచుకుని Line detail‌లో status, Site, Capacity Per Hour, Capacity Per Shift, మరియు assigned Products సరైనవని నిర్ధారించండి.",
    ],
  ),
  templates: guide("Mfg → Process & Engineering → Templates", [
    "**Templates తెరవండి:** **Mfg** తెరిచి, **Process & Engineering** విస్తరించి, **Templates** ఎంచుకోండి.",
    "**Template ప్రారంభించండి:** **Create Template** ఎంచుకుని, **Create Manually** ఎంచుకోండి లేదా AI-assisted option ద్వారా draft సిద్ధం చేయండి.",
    "**అవసరమైన identity నమోదు చేయండి:** **Template Name** మరియు **Template Type** తప్పనిసరి. Description optional.",
    "**Data scope ఎంచుకోండి:** **Context Type** optional; ఏ data sources variables‌గా అందుబాటులో ఉంటాయో ఇది నియంత్రిస్తుంది. ఎక్కువ flexibility అవసరమైనప్పుడు మాత్రమే ఖాళీగా ఉంచండి.",
    "**Template నిర్మించండి:** ఎంచుకున్న type‌కు అవసరమైన content, pattern, parser లేదా validation rule జోడించండి. PDF/HTML, HTML, CSS మరియు Nunjucks variables‌ను support చేస్తుంది; starter ఉపయోగకరమైతే **Load Sample** వాడండి.",
    "**Activate చేసే ముందు preview చేయండి:** Editor, Variables మరియు Data Preview ద్వారా realistic dataతో output‌ను verify చేయండి. Template ఉపయోగానికి సిద్ధంగా ఉన్నప్పుడే **Active** on‌లో ఉంచండి.",
    "**Save చేసి verify చేయండి:** **Save** ఎంచుకుని Templates list‌లో సరైన name, type, status, creator మరియు creation date ఉన్నాయని నిర్ధారించండి. Governance ఉంటే **My Approvals** మరియు change history వాడండి.",
  ]),
  "product-identifiers": guide(
    "Manufacturing → Process & Engineering → Identifier Management; Production → Products → Product detail → Product Identifiers",
    [
      "**Identifier definition సృష్టించండి:** **Process & Engineering → Identifier Management** తెరిచి **Create Identifier Range → Create Manually** ఎంచుకొని తప్పనిసరి Name నమోదు చేయండి. Description మరియు Active status optional controls.",
      "**Source మరియు type ఎంచుకోండి:** **Range**, **Template**, **External**, లేదా **Manual** ఎంచుకోండి. Range source కోసం identifier Type మరియు **Range** లేదా **File Upload** ఎంచుకోండి; ఒక operation‌లో గరిష్ఠంగా 10,000 identifiers process చేయవచ్చు.",
      "**Pool నిర్వచించండి:** IMEI Range కోసం తప్పనిసరి Start మరియు End values నమోదు చేసి calculated identifier count మరియు optional Range Preview నిర్ధారించి **Create** ఎంచుకోండి.",
      "**Product Identifiers తెరవండి:** **Production → Products** లో Product detail తెరిచి **Product Identifiers** విభాగానికి scroll చేసి **Add Identifier** ఎంచుకోండి.",
      "**Mapping configure చేయండి:** Identifier definition ఎంచుకుని తప్పనిసరి Identifier Key మరియు Display Name నమోదు చేసి **Generated** లేదా **External** ఎంచుకోండి. Keys uppercase‌గా store చేయబడతాయి.",
      "**Assignment behavior సెట్ చేయండి:** **On Task Creation**, **On Task Start**, లేదా **At Route Step** ఎంచుకోండి. Generated IMEI కోసం అవసరానికి అనుగుణంగా **Auto-generate** మరియు **Must be Unique** enable చేయండి.",
      "**Save చేసి verify చేయండి:** **Add Identifier** ఎంచుకుని Product table‌లో key, display name, type, source, assignment timing, మరియు linked range నిర్ధారించండి.",
    ],
  ),
  "create-production-order": guide(
    "Mfg → Production → Production Orders",
    [
      "**Production Orders తెరవండి:** **Mfg** తెరిచి, **Production** విస్తరించి, **Production Orders** ఎంచుకోండి.",
      "**Order ప్రారంభించండి:** **Create Production Order** ఎంచుకుని, **Create Manually** ఎంచుకోండి లేదా AI-assisted option ద్వారా draft సిద్ధం చేయండి.",
      "**అవసరమైన identity నమోదు చేయండి:** **Name** మరియు **Order Number** తప్పనిసరి. ఈ grouping record‌ను ప్రత్యేకంగా గుర్తించే Order Number వాడండి.",
      "**Optional Client scope సెట్ చేయండి:** ఈ Production Order ఒక Client Work Orders‌కే పరిమితం కావాలంటే **Client** ఎంచుకోండి. Client ఎంపిక eligible Work Orders‌ను పరిమితం చేస్తుంది.",
      "**Planning context జోడించండి:** Description, Start Date, End Date మరియు metadata optional. Scheduling, search లేదా reporting‌కు ఉపయోగపడితే జోడించండి.",
      "**Grouping record సృష్టించండి:** Fields review చేసి **Create Production Order** ఎంచుకోండి. Production Order work‌ను group చేస్తుంది; అది ఒంటరిగా executable quantity లేదా Production Tasks సృష్టించదు.",
      "**Work Orders link చేసి monitor చేయండి:** Production Order తెరిచి, అర్హమైన సంబంధిత Work Orders‌ను link చేసి, combined progress, status మరియు planned date range‌ను monitor చేయండి.",
    ],
  ),
  "create-work-order": guide("Manufacturing → Production → Work Orders", [
    "**Work Orders తెరవండి:** **Production** తెరిచి **Work Orders** ఎంచుకోండి.",
    "**ఒక order ప్రారంభించండి:** **Create Work Order** ఎంచుకుని, అవసరమైన ప్రత్యేక Work Order Name నమోదు చేయండి.",
    "**Product ఎంచుకోండి:** Routing configure చేసిన Product ఎంచుకుని, అవసరమైన Product Variant ఎంచుకోండి. Project మరియు Product Family ఆటోమేటిక్‌గా derive అవుతాయి.",
    "**Execution వివరాలు నమోదు చేయండి:** Positive Input Quantity, అవసరమైన Priority, మరియు గతంలో లేని Due Date నమోదు చేయండి. UI Total Computed Quantity ను Input Quantity × Product Multiplier గా లెక్కిస్తుంది.",
    "**Production సమయం కేటాయించండి:** తెలిసినప్పుడు ఒకటి లేదా ఎక్కువ Shifts ఎంచుకోండి. Record సృష్టించే సమయంలో Shift optional; కానీ Work Order start కావడానికి కనీసం ఒక Shift అవసరం.",
    "**Availability మరియు test behavior సమీక్షించండి:** Component Availability చూడండి. Line setup లేదా workflow testing కోసం మాత్రమే **Test Order** enable చేయండి; Test Orders analytics లో చేరవు.",
    "**సృష్టించి ధృవీకరించండి:** **Create Work Order** ఎంచుకుని, success dialog లో Work Order ID, Product hierarchy, quantity, due date, priority, మరియు **PENDING** status ఉన్నాయని నిర్ధారించండి.",
  ]),
  "generate-unit-serials": guide(
    "Manufacturing → Production → Work Orders → Work Order detail",
    [
      "**Work Order తెరవండి:** Work Orders జాబితా వెతికి draft Work Order ఎంచుకోండి.",
      "**Start journey తెరవండి:** **Start Work Order** ఎంచుకోండి. Confirmed serials Work Order quantity కు సమానం అయ్యే వరకు **Serial Numbers** step progress ను block చేస్తుంది.",
      "**Generation method ఎంచుకోండి:** **Generate Serial Numbers** ఎంచుకోండి. Configure అయితే Product Template, మరో available Template, లేదా CSV/Excel values కోసం **Manual Upload** ఉపయోగించండి.",
      "**Preview సమీక్షించండి:** Preview count Work Order quantity కు సమానమని నిర్ధారించి **Validate Uniqueness** ఎంచుకోండి. ప్రతి proposed serial unique గా ఉండాలి.",
      "**Batch generate చేయండి:** **Generate _n_ Serial Numbers** ఎంచుకుని batch number, quantity, మరియు **GENERATED** status సమీక్షించండి.",
      "**Batch confirm చేయండి:** **Confirm & Complete** ఎంచుకోండి. GENERATED batch confirm అయ్యే వరకు production కు ready కాదు.",
      "**Gate verify చేయండి:** Start journey లో **CONFIRMED**, ఖచ్చితమైన _n_/_n_ serial count, మరియు enabled **Next** ఉన్నాయని నిర్ధారించండి.",
    ],
  ),
  "capacity-and-routing": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**ముందుగా serials confirm చేయండి:** Confirmed serials Work Order quantity కు సరిపోయిన తర్వాత మాత్రమే start wizard **Capacity & Lines** enable చేస్తుంది.",
      "**Capacity configure చేయండి:** **Configure Capacity Planning** ఎంచుకుని Total Quantity, Available Capacity, Available Lines, మరియు eligible Starting Lines projected capacity సమీక్షించండి.",
      "**Assignment mode ఎంచుకోండి:** Default system-optimized distribution ఉపయోగించండి లేదా manual assignment కు మారండి. System mode లో **Proceed with System Assignment** ఎంచుకోండి.",
      "**Capacity gate verify చేయండి:** **Capacity planning completed** మరియు enabled **Next** ఉన్నాయని నిర్ధారించండి.",
      "**Routing ఎంచుకోండి:** **Production Route** లో eligible active Routing ఎంచుకోండి. Option associated BOM status, route type, మరియు item count చూపుతుంది.",
      "**Route gate verify చేయండి:** Routing step checked గా, overall progress 60% గా, మరియు **Next** enabled గా ఉన్నాయని నిర్ధారించండి.",
    ],
  ),
  "pre-start-validation": guide(
    "Manufacturing → Production → Work Orders → Work Order start journey",
    [
      "**Validation తెరవండి:** Serial Numbers, Capacity & Lines, మరియు Routing పూర్తయ్యాక **Next → Run Pre-Start Validation** ఎంచుకోండి.",
      "**అన్ని gates సమీక్షించండి:** Product assignment, BOM, generated/confirmed serials, Component Inventory, Station-Level Inventory, మరియు Identifier Availability validate అవుతాయి.",
      "**Blocking shortage పరిష్కరించండి:** Plant-level Component Inventory సరిపోతున్నా first-stage Station shortage start ను block చేస్తుంది. **Transfer All** లేదా component transfer action ఉపయోగించండి.",
      "**జాగ్రత్తగా transfer చేయండి:** Transfer All storage locations, తర్వాత non-routing Stations కు priority ఇస్తుంది; full coverage లేనప్పుడు partial transfer జరగవచ్చు. Remaining quantity కు **Auto-Fill Shortage** ఉపయోగించండి.",
      "**PASS verify చేయండి:** అన్ని gates pass అయి **Proceed to Start** enabled అయ్యే వరకు validation refresh చేయండి.",
      "**Production release చేయండి:** **Proceed to Start** వెంటనే release చేసి Production Tasks సృష్టించి Work Order ను **PENDING** నుండి **IN PROGRESS** కు మార్చుతుంది.",
    ],
  ),
  "production-tasks": guide("Manufacturing → Production → Production Tasks", [
    "**Work Order లో tasks సమీక్షించండి:** Released Work Order తెరిచి **Production Tasks** ఎంచుకోండి. ప్రతి confirmed finished-unit serial కు ఒక task సృష్టించబడుతుంది.",
    "**Distribution verify చేయండి:** Task count, serial coverage, Line Type, assigned Line, మరియు pending/completed distribution capacity planning కు సరిపోతున్నాయని నిర్ధారించండి.",
    "**Unit Task తెరవండి:** Task detail action ఎంచుకోండి. Header Task status, assigned serial, Work Order, Product, Line, మరియు Line Type చూపుతుంది.",
    "**Execution readiness చూడండి:** **Stage Progress** ప్రస్తుత Routing stage మరియు Station చూపుతుంది; **Bound Identifiers** assigned unit identifier చూపుతుంది.",
    "**Material readiness చూడండి:** **BOM Progress** required మరియు used quantities చూపుతుంది. Execution లో consume అయ్యే వరకు Components Pending గా ఉంటాయి.",
    "**Process context చూడండి:** Active Routing, process step, మరియు assigned Station verify చేయడానికి **Routing and Process Details** తెరవండి.",
  ]),
  "operator-flow": guide("Manufacturing → Station work area", [
    "**Mapped Stations ఫిల్టర్ చేయండి:** **Operator** లో ముందుగా Product ఎంచుకుని **Mapped** ఎంచుకోండి; default **Running** view లో Station కనిపించకపోతే Status filter ఉపయోగించండి.",
    "**Production context ఎంచుకోండి:** Station తెరిచి active Work Order మరియు eligible Production Line ఎంచుకోండి.",
    "**Task తెరవండి:** Production Task ID లేదా confirmed finished-unit serial ను scan లేదా enter చేసి **Start Task** ఎంచుకోండి.",
    "**Required inputs validate చేయండి:** ప్రతి serialised BOM Component కు available serial నమోదు చేయండి. Identifier validators వర్తిస్తాయి; Battery Pack కు GS1 AI 01 మరియు AI 10 అవసరం.",
    "**Operation పూర్తి చేయండి:** Result నిర్ధారించి **Complete & Next** ఎంచుకోండి. Operator, Station, material identities, result, timestamps, మరియు Route progress రికార్డ్ అవుతాయి.",
  ]),
  "material-consumption": guide(
    "Manufacturing → Station work area → Current operation",
    [
      "**Material available చేయండి:** Operation తెరవడానికి ముందు required stock ను execution Station కు transfer చేయండి; Station inventory panel available quantities మరియు lots చూపుతుంది.",
      "**Production Task తెరవండి:** Station work area లో Task ID లేదా confirmed finished-unit serial ను scan లేదా enter చేయండి.",
      "**Serialised material నమోదు చేయండి:** ప్రతి serialised BOM requirement కు ఒక available, unconsumed serial నమోదు చేయండి.",
      "**Identifier validators పూర్తి చేయండి:** Configured identifier format ఉపయోగించండి. GS1 validation configured అయితే AI 01 మరియు AI 10 వంటి అవసరమైన Application Identifiers అన్నీ నమోదు చేయండి.",
      "**Consumption రికార్డ్ చేయండి:** Required inputs అన్నీ validate అయిన తర్వాత **Complete & Next** ఎంచుకోండి. Completed Task material identities, inventory use, మరియు genealogy రికార్డ్ చేస్తుంది.",
    ],
  ),
  "statuses-and-route-logs": guide(
    "Manufacturing → Work Orders మరియు Route Execution Logs",
    [
      "**Work Order తనిఖీ చేయండి:** Overall status, progress, Production Metrics, మరియు task distribution చూడటానికి Work Order తెరవండి. అన్ని Production Tasks పూర్తయ్యాక మాత్రమే అది **COMPLETED** అవుతుంది.",
      "**Route Execution Logs తెరవండి:** Operation-level execution evidence చూడటానికి **Route Execution Logs** ఉపయోగించండి.",
      "**Counters చదవండి:** Individual rows పరిశీలించే ముందు **Total Logs**, **Passed**, **Failed**, మరియు **In Progress** పోల్చండి.",
      "**History filter చేయండి:** Status, date range, Work Order, Product, Routing, లేదా Station ద్వారా filter చేయండి. అవసరమైతే log ID, notes, లేదా Product ద్వారా search చేయండి.",
      "**ప్రతి result చూడండి:** Log timestamp, Work Order, Product, Routing, Line, Station, operator, quality result, మరియు execution status రికార్డ్ చేస్తుంది. సంబంధిత production context కోసం **View Details** ఉపయోగించండి.",
    ],
  ),
  "quality-controls": guide("Manufacturing → Quality → Control Points", [
    "**Control Points తెరవండి:** **Quality → Control Points** తెరిచి **Create Control Point** ఎంచుకోండి.",
    "**Required identity నమోదు చేయండి:** Unique **Code** మరియు **Name** నమోదు చేయండి. అవసరమైన **Control Type**, **Frequency**, మరియు **On Failure** action ఎంచుకోండి.",
    "**Conditional scope సెట్ చేయండి:** ముందుగా **Production Line** ఎంచుకోండి; Line ఎంచుకునే వరకు **Station** అందుబాటులో ఉండదు.",
    "**Failure behavior నిర్వచించండి:** **Stop Line**, **Quarantine**, **Hold Lot**, **Escalate**, లేదా **Alert Only** ఎంచుకోండి. Failed output స్వయంచాలకంగా secure కావాలంటే **Auto-hold failed units** ఆన్ చేయండి.",
    "**Inspection evidence జోడించండి:** Checklist questions మరియు response type జోడించి control సృష్టించండి. Configuration tab లో Active status, scope, failure action, మరియు saved checklist నిర్ధారించండి.",
  ]),
  "inspection-to-capa": guide("Manufacturing → Quality", [
    "**ముందుగా inspections configure చేయండి:** వర్తించే inspection configuration సృష్టించి activate చేయండి. Plant configuration fallback; మరింత specific scopes దానిని override చేస్తాయి.",
    "**ఒకే production source ఎంచుకోండి:** **Work Order** లేదా available, non-expired **Lot**—రెండింటిలో ఒకదాని నుంచే inspection సృష్టించండి. Required total quantity మరియు sampling quantity నమోదు చేయండి.",
    "**ప్రతి sample రికార్డు చేయండి:** Serial లేదా lot sample నమోదు చేసి checks పూర్తి చేయండి. Failed sample save చేయడానికి **Defect code** మరియు **Severity** అవసరం.",
    "**Hold scope ఎంచుకోండి:** Inspection reject చేసినప్పుడు failed serials మాత్రమే లేదా మొత్తం lot ను hold చేయండి. Inspection-local defects మరియు plant **Defects** list records వేర్వేరు.",
    "**Deployment availability నిర్ధారించండి:** NCR మరియు CAPA actions deployment మరియు permission‌పై ఆధారపడవచ్చు. Working create action లేకపోతే workflow available అని చెప్పకుండా implementation owner‌తో enablement నిర్ధారించండి.",
  ]),
  "repair-and-rework": guide(
    "Mfg → Repair & Rework → Debug Queue, Repair Queue, Repair Out, మరియు Rework Board",
    [
      "**Failed RSN‌ను Repair‌కు పంపండి:** **Debug Queue**లో RSN తెరిచి failure evidence, route context, మరియు previous attempts review చేయండి. Forge **Send to Repair** చూపినప్పుడు మాత్రమే ఎంచుకుని Repair Level, available 4M cause details, diagnosis notes నమోదు చేసి submit చేయండి; status **Queued for Repair** అయిందో చూడండి.",
      "**Repair ప్రారంభించండి:** **Repair Queue**లో అదే RSN తెరిచి failure evidence, Repair Station, attempt history, మరియు status తనిఖీ చేయండి. **Start Repair** ఎంచుకుని prompted fields పూర్తి చేసి job **In Repair** అయిందో నిర్ధారించండి.",
      "**Repair complete చేయండి:** Work పూర్తయిన తర్వాత మాత్రమే **Complete Repair** ఎంచుకోండి. **Repair Successful** లేదా **No Fault Found**, confirmed 4M category, repair minutes, cost, notes, మరియు evidence నమోదు చేయండి. Submit చేసి **Pending QC** అయిందో చూడండి. ఇదే QC handoff; వేరే Send to QC action లేదు.",
      "**QCలో approve చేయండి:** **Repair Out**లో **Pending QC** RSN తెరిచి timeline, result, costs, notes, మరియు evidence review చేయండి. Forge చూపినప్పుడు **QC Pass** ఎంచుకుని required notes జోడించండి; refresh తర్వాత **QC Passed** status మరియు timelineలో ఉందో చూడండి.",
      "**QC తర్వాత release చేయండి:** QC-passed recordకు Forge **Release** చూపినప్పుడు మాత్రమే ఉపయోగించండి. Destination లేదా next step నిర్ధారించి ఒక్కసారి submit చేసి resulting status verify చేయండి.",
      "**QCలో reject చేయండి:** Verification fail అయితే available **QC Reject** action ఉపయోగించి required reason మరియు notes నమోదు చేయండి. Refresh చేసి resulting status మరియు timeline చూడండి; RSN Repair లేదా Reworkకు తిరిగిందని assume చేయవద్దు.",
      "**Repairకు తిరిగిన RSN:** Post-rejection status లేదా displayed action Repairకు పంపితే **Repair Queue**లో new attempt ప్రారంభించి issue సరిచేసి new evidence నమోదు చేసి complete చేయండి; మళ్లీ **Pending QC** చేరిందో చూడండి.",
      "**Reworkకు పంపి complete చేయండి:** Approved RSNకు Forge చూపే Rework disposition మాత్రమే ఉపయోగించండి. Controlled symptom, reason, మరియు routing information నమోదు చేసి **Rework Board**లో card track చేయండి. **Record work** ద్వారా attempt మరియు evidence నమోదు చేసి displayed result column చేరిందో verify చేయండి.",
      "**Approved dispositionకు మాత్రమే Scrap:** **Report Scrap** లేదా Scrap action available మరియు approved అయినప్పుడు మాత్రమే controlled reason, evidence, మరియు approval trail నమోదు చేయండి; Scrap Register status verify చేయండి.",
      "**Forge error వస్తే ఆపండి:** State-changing actionను repeat చేయవద్దు; success అని assume చేయవద్దు. RSN మరియు visible status ఉంచి error report చేయండి.",
    ],
  ),
  "hold-scrap-teardown": guide("Manufacturing → Quality or Scrap & Teardown", [
    "**సరైన hold సృష్టించండి:** **Quality → Hold Management → Create Hold** తెరవండి. ముందుగా Hold Level ఎంచుకోండి; ఇది required target మరియు operational impact ను మారుస్తుంది.",
    "**Required hold fields పూర్తి చేయండి:** Target మరియు **Reason** ఎంచుకోండి. Notes optional; Work Order hold కు optional expected release date జోడించవచ్చు.",
    "**Approval నియమాలు పాటించండి:** Inventory lot, vendor, మరియు date-code holds **Submit for Approval** ఉపయోగిస్తాయి; Quality approve చేసే వరకు అవి inactive. Work Order hold ఆ order యొక్క మొత్తం production ను pause చేస్తుంది.",
    "**Scrap ను upstream లో track చేయండి:** ముందుగా **Scrap Reasons** configure చేయండి. **Scrap Register** Pending Approval, Approved, Executed, మరియు Rejected dispatches track చేస్తుంది; ఇందులో create action లేదు.",
    "**Teardown సరిగ్గా ప్రారంభించండి:** Executed Scrap dispatch ను **Send to teardown** తో పంపిన తర్వాత మాత్రమే Teardown order కనిపిస్తుంది. Donor serial మరియు scrap dispatch recovered Components కు linked గా ఉంటాయి.",
  ]),
  "scrap-register": guide("Mfg → Scrap & Teardown → Scrap Register", [
    "**Register తెరవండి:** **Scrap & Teardown** తెరిచి **Scrap Register** ఎంచుకోండి. ఇది review queue; create action లేదు.",
    "**Status view ఎంచుకోండి:** సరైన dispatch state కోసం **All**, **Pending Approval**, **Approved**, **Executed**, లేదా **Rejected** ఉపయోగించండి.",
    "**Scope సెట్ చేయండి:** Source, Category, Reason, Line, Station, Work Order, Product, లేదా Date Range ద్వారా filter చేసి, source data మారితే **Refresh** ఉపయోగించండి.",
    "**Dispatch evidence review చేయండి:** Action తీసుకునే ముందు dispatch number, source, unit లేదా quantity, Product, Work Order, Station, reason, proposer, status, మరియు age సరైనవో చూడండి.",
    "**Approval flow కాపాడండి:** Record eligible state‌లో ఉండి required evidence review చేసినప్పుడు మాత్రమే approve, execute, reject, లేదా teardown‌కు పంపండి. Action తర్వాత updated status మరియు evidence‌ను నిర్ధారించండి.",
  ]),
  "scrap-reasons": guide("Mfg → Scrap & Teardown → Scrap Reasons", [
    "**Scrap Reasons తెరవండి:** **Scrap & Teardown → Scrap Reasons** తెరవండి. Obsolete categories లేదా reasons చూడాల్సినప్పుడు మాత్రమే **Show inactive** ఉపయోగించండి.",
    "**Taxonomy ప్రారంభించే విధానం ఎంచుకోండి:** Standard categories కోసం **Seed industry defaults**, manual category కోసం **Add category** ఎంచుకోండి.",
    "**Manual category నమోదు చేయండి:** **Code** మరియు **Name** required. Description optional; Sort Order category స్థానం నిర్ణయిస్తుంది.",
    "**Category కింద reason codes నిర్వహించండి:** స్పష్టమైన, duplicate కాని reasons జోడించి, ప్రస్తుతం selectable entries మాత్రమే active‌గా ఉంచండి.",
    "**Existing taxonomy సమీక్షించండి:** జాబితా ఖాళీగా ఉంటే approved taxonomy ప్రకారం industry defaults seed చేయండి లేదా manual categories జోడించండి. Production‌లో ఉపయోగించే ముందు selected Plant‌లో active reasons అందుబాటులో ఉన్నాయని నిర్ధారించండి.",
  ]),
  packaging: guide("Manufacturing → Packaging & Shipping → Packaging", [
    "**Packaging తెరవండి:** **Packaging & Shipping** తెరిచి **Packaging** ఎంచుకోండి.",
    "**Product hierarchy configure చేయండి:** **Packing Configuration** తెరిచి Product ఎంచుకుని product-specific container type నిర్వచించండి. **Product**, **Name**, మరియు **Code** తప్పనిసరి; Code 2–10 alphanumeric characters ను అంగీకరిస్తుంది.",
    "**Leaf లేదా parent behavior ఎంచుకోండి:** Finished-unit serials ను నేరుగా bind చేసే leaf కోసం **Child Container Type** ఖాళీగా ఉంచండి; లేకపోతే Device → Box → Carton → Pallet hierarchy కోసం అనుమతించిన child ను ఎంచుకోండి.",
    "**Container సృష్టించండి:** Packaging Dashboard కు తిరిగి వెళ్లి **Create Container** ఎంచుకోండి. Product ఎంచుకుని, తప్పనిసరి **Container Type** మరియు **Work Order ID** ఎంచుకోండి; రెండూ ఉండే వరకు Create enable కాదు.",
    "**Packaging సమీక్షించి పూర్తి చేయండి:** Generated UID తెరిచి device count, weight and dimensions, linked Work Order, label state, మరియు History చూడండి. UID template optional; లేకపోతే Fynd ERP default format ఉపయోగిస్తుంది.",
  ]),
  shipments: guide("Mfg → Packaging & Shipping → Shipments", [
    "**Shipments తెరవండి:** **Packaging & Shipping** తెరిచి **Shipments** ఎంచుకోండి.",
    "**Existing shipment వెతకండి:** ASN లేదా destination ద్వారా search చేయండి; Work Order, Product, Status, మరియు Date Range filters ఉపయోగించండి. List‌లో ASN, Work Order, destination, contents, carrier, status, dates, మరియు actions కనిపిస్తాయి.",
    "**Valid source data ఉన్నప్పుడు మాత్రమే shipment ప్రారంభించండి:** **New Shipment** ఎంచుకోండి. Work Order optional; **Product** మరియు **Address line 1** required. Destination, carrier, optional invoice లేదా vendor-lot details, మరియు notes పూర్తి చేయండి.",
    "**Created record verify చేయండి:** Shipment verification‌కు వెళ్లే ముందు కొత్త record expected destination, contents, carrier, status, మరియు dates‌తో list‌లో ఉందో చూడండి.",
    "**Shipment prerequisites నిర్ధారించండి:** Form submit చేసే ముందు approved Product, destination, carrier, మరియు source records ఉపయోగించండి. సృష్టించిన Shipment verification screen‌లో selectable‌గా ఉండి expected details చూపుతుందో నిర్ధారించండి.",
  ]),
  "containers-and-labels": guide("Manufacturing → Packaging & Shipping", [
    "**Container hierarchy నిర్మించండి:** **Packing Configuration** లో ముందుగా leaf సృష్టించి, తర్వాత ప్రతి parent కు అనుమతించిన **Child Container Type** ఎంచుకోండి. Child ఎంచుకున్న వెంటనే **Max child count** తప్పనిసరి అవుతుంది.",
    "**Identity మరియు limits configure చేయండి:** Container-specific **UID Template**, sequence reset scope, dimensions, weight range, మరియు tolerance ఎంచుకోండి. Unit-serial pattern ను తిరిగి ఉపయోగిస్తే UID collision రావచ్చు.",
    "**Parent container సృష్టించండి:** Packaging Dashboard లో Product, parent Container Type, మరియు completed Work Order ఎంచుకోండి. Generated UID ఎంచుకున్న template ను అనుసరిస్తుంది.",
    "**Eligible identity pack చేయండి:** **Pack by UID** లో finished serial, device UID, child UID, identifier, లేదా task ID scan చేయండి. Valid unit configured leaf container ను స్వయంచాలకంగా సృష్టించి parent లో pack చేస్తుంది; capacity enforce అవుతుంది.",
    "**Label print చేసి verify చేయండి:** Carton label print చేసి carton UID, model, quantity, unit serial, మరియు QR codes తనిఖీ చేయండి. Source records లో లేని values ఖాళీగా ఉంటాయి; traceability కోసం History మరియు Reprint ఉపయోగించండి.",
  ]),
  "shipment-verification": guide(
    "Manufacturing → Packaging & Shipping → Shipment Verification",
    [
      "**ముందుగా Shipment ఎంచుకోండి:** **Shipment Verification** తెరవండి. **Shipment** తప్పనిసరి; Shipment ఎంచుకునే వరకు **Container Type**, verification counts, container rows, మరియు Export అందుబాటులో ఉండవు.",
      "**Governing rule పాటించండి:** Active **Shipment Rule** selected container configuration ను కలిగి ఉండి, container count మరియు maximum-weight limits ను అనుమతించాలి. ఏ rule apply అవుతుందో priority నిర్ణయిస్తుంది.",
      "**Shipping Gate తనిఖీ చేయండి:** Verification ముందు applicable approved Purchase Order quantity‌కు positive remaining balance ఉందో నిర్ధారించండి.",
      "**అవసరమైతే ASN export configure చేయండి:** ASN Excel columns client- లేదా product-scoped template నుండి వస్తాయి. Export‌పై ఆధారపడే ముందు selected scope‌కు required template configured ఉందో నిర్ధారించండి.",
      "**Prerequisite path verify చేయండి:** Approved records‌తో Shipment సృష్టించి, rule matching, positive gate balance, container verification, మరియు ASN output‌ను end to end నిర్ధారించండి.",
    ],
  ),
  "traceability-genealogy-recall": guide(
    "Manufacturing → Traceability → Master Traceability",
    [
      "**తప్పనిసరి dossier scope సెట్ చేయండి:** **Master Traceability** లో filters కలిపి పనిచేస్తాయి; parent selection చేసిన తర్వాత dependent Product filters తెరుచుకుంటాయి. Specific identifier list ఇతర filters ను override చేస్తుంది; కనీసం ఒక scope ఎంచుకునే వరకు **Generate Dossier** disabled గా ఉంటుంది.",
      "**Report output ఎంచుకోండి:** అవసరమైన unit, route, quality, genealogy, identifier, tool, checklist, packaging, లేదా shipment sheets మాత్రమే ఎంచుకోండి. Generation asynchronous; completed files **Recent exports** లో ఉంటాయి. Exported unit count selected scope‌కు సరిపోతుందో నిర్ధారించండి.",
      "**Stage Timeline requirements అన్నీ పూర్తి చేయండి:** Date range, కనీసం ఒక Work Order, మరియు 1–50 Operations అవసరం. Date range‌కు required indicator కనిపించకపోయినా field పూర్తి చేయండి.",
      "**సరైన దిశలో genealogy అనుసరించండి:** Full tree pallet, carton, box, device, product, Component, లేదా batch identifiers స్వీకరిస్తుంది. **Downstream** finished identity నుండి Components/lots వరకు వెళుతుంది; **Upstream** lot నుండి finished units వైపు వెళుతుంది.",
      "**Affected population కనుగొనండి:** **Find Affected Units** లో Batch/Lot Number లేదా Component Serial ద్వారా వెతకండి. Results expected finished serials మరియు related Work Orders‌ను చూపుతున్నాయో నిర్ధారించండి.",
      "**Recall assignment‌పై ఆధారపడే ముందు verify చేయండి:** Recall సృష్టించడానికి Title మరియు Severity తప్పనిసరి. Selected batch లేదా tasks affected units‌ను populate చేస్తున్నాయా, saved notice వాటిని record చేస్తున్నదా నిర్ధారించండి.",
    ],
  ),
  dashboards: guide(
    "Manufacturing → Dashboard, Work Orders, Production Tasks, and Route Logs",
    [
      "**Current Plant నుండి ప్రారంభించండి:** Dashboard selected Plant కోసం setup readiness, active Work Orders, production Stations, active Products, Clients, Projects, production completion, మరియు quality targets చూపిస్తుంది.",
      "**Schedule risk గుర్తించండి:** **Work Orders** లో Status, Priority, మరియు Due Date ను కలిపి చూడండి. Past-due active records **Delayed** గా గుర్తించబడతాయి; completed original Work Order‌ను active repair Work Order నుంచి Work Order, Line, మరియు status ఆధారంగా వేరు చేయండి.",
      "**Work Order metrics అర్థం చేసుకోండి:** Completed Work Order‌లో completed/total tasks, units per hour, takt/cycle time, yield, మరియు total execution time సమీక్షించండి. Yield అంటే passed quality steps ÷ completed steps; displayed target‌తో పోల్చండి.",
      "**Live progress board ఉపయోగించండి:** **Track Progress** default గా ప్రతి 30 seconds కు auto-refresh అవుతుంది; Station filter, completed highlight, samples-only, sorting, మరియు fullscreen controls ఉన్నాయి.",
      "**Task context నిర్ధారించండి:** Production Tasks Serial, task ID, grouping, Work Order, Line, Product/Routing, మరియు status చూపిస్తుంది. ఒకే serial కు later repair task సహా ఒకటి కంటే ఎక్కువ task records ఉండవచ్చు; చర్యకు ముందు Work Order మరియు Line నిర్ధారించండి.",
      "**Execution evidence ధృవీకరించండి:** Route Log totals current filters ను ప్రతిబింబిస్తాయి. ప్రతి log Work Order, Product, Routing, Line, Station, operator, timestamp, quality status, మరియు execution status ను భద్రపరుస్తుంది; summary counts underlying records‌కు సరిపోతాయో నిర్ధారించండి.",
    ],
  ),
  "shift-operations": guide("Manufacturing → Shifts & Labor", [
    "**Net working time నిర్ధారించండి:** Unpaid breaks Shift duration నుండి తీసివేయబడతాయి. Displayed net working time, Shift duration నుంచి మొత్తం unpaid break time తీసివేసిన విలువకు సరిపోతుందో నిర్ధారించండి.",
    "**Schedule coverage ధృవీకరించండి:** కొత్త Shift Schedules activate చేసే వరకు Draft‌గా ఉంటాయి. Status మాత్రమే coverage నిరూపించదు; generated shifts per week మరియు calendar coverage‌ను నిర్ధారించండి.",
    "**Required Handover fields పూర్తి చేయండి:** **Shift** మరియు **Handover Date** తప్పనిసరి. Line, outgoing/incoming operators, production/quality/equipment summaries, notes, pending tasks, మరియు checklist items optional.",
    "**Connected operating context రికార్డు చేయండి:** Handover‌ను selected Shift మరియు Line‌కు అనుసంధానించి completed production, quality results, equipment state, safety, మరియు pending repair tasks రికార్డు చేయండి.",
    "**Complete ముందు review చేయండి:** కొత్త Handover **Draft**. Outgoing మరియు Incoming Supervisors‌ను explicit‌గా నిర్ధారించి, తదుపరి Shift review చేసిన తర్వాత మాత్రమే **Complete** ఉపయోగించండి.",
    "**Break Compliance జాగ్రత్తగా అర్థం చేసుకోండి:** Zero Break Logs ఉన్నప్పుడు view 100% compliance మరియు 0 violations చూపవచ్చు; అయితే ఆ percentage compliant breaks జరిగాయనే evidence కాదు. Underlying logs‌ను నిర్ధారించండి; export చేయగల records ఉన్నప్పుడే **Export CSV** అందుబాటులో ఉంటుంది.",
  ]),
  "tools-and-maintenance": guide(
    "Manufacturing → Process & Engineering → Tools and Equipments",
    [
      "**Tool register తెరవండి:** **Process & Engineering → Tools and Equipments** expand చేసి, child **Tools and Equipments** page తెరవండి.",
      "**అవసరమైన identity పూర్తి చేయండి:** **Tool Name, Tool Code, Tool Category, Manufacturer, Model, Station, మరియు Status** required. Tool‌ను అది ఉపయోగించే సరైన Station‌కు assign చేయండి.",
      "**Governed Tool కు మాత్రమే calibration సెట్ చేయండి:** **Requires Calibration** enable చేస్తే optional interval మరియు provider fields కనిపిస్తాయి. Required **Calibration Date, Next Calibration Date, మరియు Result** ఉన్న record వచ్చేవరకు governed Tool **Unknown** గా ఉంటుంది.",
      "**Readiness evidence రికార్డ్ చేయండి:** Calibration result, certificate reference, మరియు next due date నమోదు చేసి current status‌ను నిర్ధారించండి. Override ఉపయోగిస్తే calibration override history లో కనిపిస్తుంది.",
      "**Maintenance Alerts evaluate చేయండి:** **Trigger Maintenance Check** configured maintenance rules ను evaluate చేస్తుంది. 0 alerts అంటే rule match కాలేదని లేదా required rules/source data లేవని అర్థం కావచ్చు; result‌పై ఆధారపడే ముందు రెండింటినీ verify చేయండి. Alert rows ఉన్నప్పుడే **Export** అందుబాటులో ఉంటుంది.",
      "**Maintenance Work Order ను control చేయండి:** **Tool** మరియు **Title** మాత్రమే required; Priority **Medium**, Maintenance Type **Corrective** గా default అవుతాయి. Connected preventive order **Draft → Submitted → Approved** గా మారి, తర్వాత **Start** అందుబాటులోకి వస్తుంది.",
      "**Production timing రక్షించండి:** Tool status, calibration, మరియు maintenance readiness current గా ఉంచండి. Future approved maintenance order ను planned window కు ముందు start చేయవద్దు.",
    ],
  ),
  "reports-and-audit": guide(
    "Traceability → Master Traceability; Production → Work Orders",
    [
      "**Dossier scope సెట్ చేయండి:** **Traceability → Master Traceability → Dossier** తెరవండి. Scope filters optional గా combine అవుతాయి; **Specific identifiers** లో paste లేదా upload చేసే serial-number list మిగతా scope filters ను override చేస్తుంది.",
      "**Report sheets ఎంచుకోండి:** అవసరమైన Unit Summary, Route Detail, tests, sampling, NCR/defects, repair, genealogy, identifiers, Tool Usage, checklist, packaging, మరియు shipment sheets ఎంచుకోండి. Reported unit count selected Work Order scope‌కు సరిపోతుందో నిర్ధారించండి.",
      "**Dossier generate చేసి verify చేయండి:** **Generate Dossier** ఎంచుకుని, download ముందు **Recent exports** లో **COMPLETED**, unit count, మరియు XLSX filename ఉన్నాయో నిర్ధారించండి.",
      "**Work Order export సృష్టించండి:** **Production → Work Orders** లో **Export Work Orders** ఎంచుకుని **Create Data Export** dialog పూర్తి చేయండి. List-page filters inherit కాకపోతే Search, Status, మరియు Priority మళ్లీ apply చేయండి.",
      "**Export evidence verify చేయండి:** Export Details type, format, status, file size, మరియు applied filters ను నిల్వ చేస్తుంది. Job **COMPLETED** అయినా Processed మరియు Progress 0 గా ఉండవచ్చు; ఆధారపడే ముందు processed count మరియు file contents నిర్ధారించండి.",
      "**అందుబాటులో ఉన్న audit history ఉపయోగించండి:** **View all changes** మరియు **Recent Changes** అందుబాటులో ఉన్న actor, action, affected record, మరియు timestamp evidence చూపిస్తాయి. Separate full-history route‌పై ఆధారపడే ముందు required evidence అందులో ఉందో నిర్ధారించండి.",
    ],
  ),
  "first-production-run": guide("Manufacturing → Production → Work Orders", [
    "**ఒక trial Work Order సృష్టించండి:** **Create Work Order** ఎంచుకుని, చిన్న కానీ వాస్తవిక quantity ఉపయోగించండి.",
    "**సిద్ధం చేసి release చేయండి:** serials, capacity, Routing, material, మరియు identifiers నిర్ధారించి, తర్వాత **Release Work Order** ఎంచుకోండి.",
    "**సాధారణ మార్గం రన్ చేయండి:** కనీసం ఒక unit ను ప్రతి అవసరమైన operation ద్వారా పూర్తి చేయండి.",
    "**ఒక exception పరీక్షించండి:** ఒక నియంత్రిత operation ను విఫలం చేసి, దాని Repair లేదా Rework మార్గం పూర్తి చేయండి.",
    "**ముగించి trace చేయండి:** వర్తించే quality, packaging, మరియు shipment steps పూర్తి చేసి, తర్వాత **Master Traceability** లో unit వెతకండి.",
  ]),
  troubleshooting: guide("The affected Fynd ERP module", [
    "**విఫలమైన రికార్డు తెరవండి:** error చూపిస్తున్న Product, Routing, Work Order, Production Task, లేదా shipment కు తిరిగి వెళ్ళండి.",
    "**Validation సందేశం చదవండి:** విఫలమైన check విస్తరించి, ఖచ్చితమైన missing field, relationship, status, లేదా quantity గమనించండి.",
    "**Prerequisites తనిఖీ చేయండి:** వర్తించే విధంగా active BOM, Stations, Repair Stations, Shift, Line assignment, capacity, serials, inventory, మరియు identifiers verify చేయండి.",
    "**Source రికార్డును సరిచేయండి:** linked configuration తెరిచి, అవసరమైన మార్పు చేసి, **Save** ఎంచుకోండి.",
    "**Action మళ్ళీ ప్రయత్నించండి:** అసలు రికార్డుకు తిరిగి వెళ్ళి **Validate**, **Create**, **Release**, లేదా **Complete** మళ్ళీ ఎంచుకోండి.",
  ]),
};
